def.bzl
deps.bzl

Add copyright notice in .bzl files

---

README.rst

Update README.rst for release 0.8

---

README.rst

Simple fix of the README.rst file.

Fix README.rst table.

---

cmd/gazelle/diff.go

Don't invoke the "diff" command if the contents haven't changed.
Don't call Sync() on every write. Just closing the file suffices.
Before this change, diffing a repo with 1600 BUILD files would take 60 seconds.
After the change, it takes 2 seconds.

Improve performance of gazelle --mode=diff

---

BUILD.bazel
def.bzl

gazelle rule: make prefix attribute optional

---

README.rst

[skip ci]
[ci skip]
Fixes bazelbuild/rules_go#1158

Add compatibility table

---

README.rst

Update README.rst in preparation of 0.9 release

---

cmd/gazelle/BUILD.bazel
internal/common/BUILD.bazel
internal/config/BUILD.bazel
internal/merger/BUILD.bazel
internal/merger/fix.go
internal/merger/fix_test.go
internal/packages/BUILD.bazel
internal/pathtools/BUILD.bazel
internal/repos/BUILD.bazel
internal/resolve/BUILD.bazel
internal/resolve/gen_std_package_list/BUILD.bazel
internal/rules/BUILD.bazel
internal/version/BUILD.bazel
internal/wspace/BUILD.bazel
vendor/github.com/pelletier/go-toml/cmd/BUILD.bazel
vendor/github.com/pelletier/go-toml/cmd/tomljson/BUILD.bazel
vendor/github.com/pelletier/go-toml/cmd/tomll/BUILD.bazel

Remove importpath from go_binary, go_test

---

Design.rst

Gazelle design document

---

internal/packages/walk.go
internal/packages/walk_test.go

This flag defines a comma-separated list of globs. Bazel will descend into
symlinks that match the globs.
Bazel itself follows symlinks, except for those to build directories (bazel-bin,
etc). This change allows repositories that uses symlinks to work more properly.

Add -follow_symlinks flag

---

README.rst
repository.rst

Document repository rules

---

README.rst

Update boilerplate for 0.10.1

---

README.rst

Update setup boilerplate for rules_go 0.10.3

---

README.rst

Update README for release 0.11.0

---

README.rst

* Updated rules_go version and sha for 0.11.1 in boilerplate.
* Formatted and improved directive documentation.
* Expanded fix transformation documentation.

Update README.rst with new rules_go version and better documentation

---

README.rst

Announce release 0.12.0 and update boilerplate

---

cmd/gazelle/update-repos.go
internal/language/go/package.go
internal/language/go/testdata/bin_with_tests/bin_test.go

Like the title suggests, this fixes some of the go fmt and go vet errors.

Fix go fmt/vet errors

---

internal/resolve/index.go

internal/index: include repo name in indexed label

---

README.rst

Also, document fix for gazelle load.
Fixes #267

Fix proto directive documentation [skip ci]

---

README.rst

Clarify documentation for proto_group [skip ci]

---

README.rst
repository.rst

Link to proto conflicts FAQ and update go_repository doc [skip ci]

---

README.rst

Update README.rst and add a section on dependency resolution [skip ci]

---

internal/repos/modules.go
internal/repos/modules_test.go

This PR fixes https://github.com/bazelbuild/bazel-gazelle/issues/343

Better parsing of go.mod rules

---

repository.rst

go_repository: document how to ignore vendor [skip ci]

---

cmd/gazelle/fix-update.go
cmd/gazelle/integration_test.go

Stop indexing generated rules when -index=false

---

cmd/autogazelle/autogazelle.bash

autogazelle: echo to stderr

---

internal/gazelle.bash.in

gazelle: call set_groot when invoked by Bazel

---

cmd/gazelle/fix-update.go
cmd/gazelle/integration_test.go

runFixUpdate now saves the configuration for each visited subdirectory
in the corresponding visitRecord. The configuration is passed to
later language.Resolve calls for rules in that directory.
This allows the Go extension to use the prefix directive when deciding
how to resolve imports that couldn't be resolved with the index.
Fixes #412

cmd/gazelle: save configurations for dependency resolution

---

internal/go_repository.bzl

GOCACHE must be set for Go 1.12 if it can't be derived from other
environment variables.
Also, disable module mode so we build out of vendor. I don't think
-mod=vendor will work in Go 1.9 which is still theoretically
supported.
Updates bazelbuild/rules_go#1892

go_repository: set GOCACHE when building fetch_repo and gazelle

---

cmd/gazelle/update-repos.go
repo/BUILD.bazel
repo/dep.go
repo/godep.go
repo/import_test.go
repo/modules.go
repo/repo.go

This is pretty straightforward - It handles the basic fileformat for godep, and follows the same function layout for `importRepoRulesDep`

Add support for godep (https://github.com/tools/godep)

---

BUILD.bazel
WORKSPACE

Updates bazelbuild/rules_go#1932

Use nogo with vet = True

---

cmd/gazelle/integration_test.go
go.mod
go.sum
language/go/BUILD.bazel
repo/BUILD.bazel
rule/merge.go
rule/rule.go
vendor/github.com/bazelbuild/buildtools/build/lex.go
vendor/github.com/bazelbuild/buildtools/build/parse.y
vendor/github.com/bazelbuild/buildtools/build/parse.y.go
vendor/github.com/bazelbuild/buildtools/build/print.go
vendor/github.com/bazelbuild/buildtools/build/rewrite.go
vendor/github.com/bazelbuild/buildtools/build/rule.go
vendor/github.com/bazelbuild/buildtools/build/syntax.go
vendor/github.com/bazelbuild/buildtools/build/walk.go
vendor/modules.txt

Upgrade github.com/bazelbuild/buildtools to latest

---

internal/BUILD.bazel
repo/repo.go

Also, fix //internal:repository_rules_test,
which is broken for some reason.

repo: add unstable comment

---

WORKSPACE

Needed for importpath_aliases support.

Update rules_go to master as of 2019-06-28

---

README.rst

just realized a new version was released so wanted to update the reference here.

rules_go 0.18.7

---

internal/go_repository.bzl

* GOPRIVATE, GONOPROXY, GOSUMDB, and GONOSUMDB are now passed through
to gazelle when invoked by go_repository.
* GOSUMDB is set to "off" for fetch_repo. In module mode, the zip sum
is a mandatory attribute of go_repository, and we don't need to look
it up.
Updates #579

go_repository: respect proxy and sumdb privacy environment variables

---

internal/go_repository_tools.bzl

bazel on Windows does not create symbolic links in a way that we can
check this.

go_repository: don't check tools source list on windows

---

internal/go_repository_tools.bzl

go_repository: don't assume PATH is set

---

README.rst

Keep in line with rules_go README

Use rules_go 0.21.0 in README

---

cmd/gazelle/integration_test.go
language/go/testdata/service/service.proto
language/go/testdata/service_gogo/service.proto
language/go/testdata/service_gogo_subdir_reset/foo.proto
language/go/testdata/service_gogo_subdir_reset/sub/bar.proto
language/proto/fileinfo.go
language/proto/fileinfo_test.go

language/proto: Fixed service definition regexp

---

language/go/resolve.go
pathtools/path.go
walk/walk.go

Fix `go vet` issues.

---

language/go/config.go
language/go/generate.go
language/go/package.go

Exporting go.InferImportPath

---

language/proto/generate.go
language/proto/generate_test.go
language/proto/testdata/generated/BUILD.old
language/proto/testdata/generated/BUILD.want

This reverts commit 172c75494e80fba549a8cbe970df1cc34a9914fc.
Fixed #731

Revert "proto_library for generated proto files (#720)"

---

language/go/testdata/cgolib_with_build_tags/BUILD.want
rule/platform.go

language/go: add missing entries to KnownPlatforms

---

cmd/fetch_repo/module.go
internal/go_repository_cache.bzl
internal/go_repository_test.go

go_repository_cache: use -modcacherw if available

---

BUILD.bazel
cmd/gazelle/BUILD.bazel

all: exclude .idea in root directory

---

README.rst
WORKSPACE

Update boilerplate for v0.22.1; update to rules_go v0.24.3

Update boilerplate for v0.22.1; update to rules_go v0.24.3

---

label/label.go

label: fix documentation for Name

---

README.rst

doc: add "Compatibility with Go" section to README [skip ci]

---

README.rst

Update boilerplate for v0.22.1 [skip ci]

Update boilerplate for v0.22.1 [skip ci]

---

def.bzl
internal/go_repository_test.go
internal/runner_test.go

gazelle rule: support update-repos command

---

cmd/gazelle/diff.go

Cleanup
> cmd/gazelle
Removes unused / redundant code.

cleanup unused variable warning in diff.go; reuse rel

---

repo/remote.go

* Fix a typo in the temporary module path: previously it ended with a
literal '\n', which is not valid.
* Add a 'go 1.15' declaration.
* Run 'go get -d pkg' before 'go list pkg' since -mod=readonly is now
the default.
* Refactor error handling.
Fixes #972

repo: fix module commands for Go 1.16

---

cmd/generate_repo_config/generate_repo_config.go
internal/go_repository_test.go

go_repository: include build_naming_convention in configuration file

---

deps.bzl
go.mod
go.sum
vendor/github.com/google/go-cmp/cmp/compare.go
vendor/github.com/google/go-cmp/cmp/export_panic.go
vendor/github.com/google/go-cmp/cmp/export_unsafe.go
vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
vendor/github.com/google/go-cmp/cmp/internal/function/func.go
vendor/github.com/google/go-cmp/cmp/internal/value/name.go
vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
vendor/github.com/google/go-cmp/cmp/options.go
vendor/github.com/google/go-cmp/cmp/path.go
vendor/github.com/google/go-cmp/cmp/report.go
vendor/github.com/google/go-cmp/cmp/report_compare.go
vendor/github.com/google/go-cmp/cmp/report_references.go
vendor/github.com/google/go-cmp/cmp/report_reflect.go
vendor/github.com/google/go-cmp/cmp/report_slices.go
vendor/github.com/google/go-cmp/cmp/report_text.go
vendor/github.com/google/go-cmp/cmp/report_value.go
vendor/modules.txt

Upgrade Google go-cmp to v0.5.4

---

cmd/gazelle/integration_test.go
language/go/generate.go

Bug fix
language/go
Fixes #960

go/visibility: expand visibility to other repos that are sibling to internal/

---

walk/config.go
walk/walk_test.go

Feature
cmd/gazelle
Gazelle now can recognize .bazelignore files
Fixes #318

Respect .bazelignore

---

README.rst

Galleze -> Gazelle

---

README.rst

triag,e -> triage

---

README.rst
WORKSPACE

Also update versions in README.rst examples.

Update to Go 1.17 in WORKSPACE

---

rule/rule.go
rule/rule_test.go

Added `rule.AddAlias` func to support loading aliased symbols

---

rule/BUILD.bazel
rule/merge.go
rule/merge_test.go

Bug fix
cmd/gazelle
Currently the `private` attribute isn't copied.
Fixes #

Merge the private attribute

---

README.rst
extend.md
internal/extend_docs.bzl

Preview: https://github.com/alexeagle/bazel-gazelle/tree/patch-1#supported-languages

Move list of supported languages to top of README

---

README.rst

Documentation
N/A
Update README to latest release
N/A

Update rules example in README to v0.25.0

---

def.bzl

Bug fix
cmd/gazelle
Fixes #1241
Fixes #1241

Allow static dependency resolution for Gazelle rule

---

language/go/lang.go
language/lang.go

Fix typo in comment

---

README.rst

Documentation
README
Document the Java extension.

Document Java extension

---

README.rst

Documentation
README
It uses Markdown, should use RST
n/a, see following PR summary template text:
> Small bug fixes and documentation improvements don't need issues.

Fix RST URL errors for rules_jvm

---

rule/rule.go
rule/rule_test.go

Feature
rule
This PR sorts the `.Loads` in a macro file when `SortMacro()` is called. This is needed because loads do not need to be provided in a specific order, and can get very messy as the number of Load statements gets large.
If the user is calling SortMacros, they already would prefer to have this macro in a clean/tidy state.
Adds additional feature improvement to #696

SortMacro() should also sort the Loads

---

rule/rule.go
rule/rule_test.go

Feature
rule
> I agree we should not attempt to sort WORKSPACE. There's often some complicated interdependence between repositories declared there, so the order is important.
> 
> Sorting rules declared in macros seems less obvious, but Gazelle probably (already) can't update macros where the order is important, so I think it makes sense to always sort. If it turns out to be a problem, we can add a directive or something later to control it.
As mentioned in a discussion with @linzhp and @jayconrod:
This change also sorts rules by `Kind()` when running `SortMacro()` for cases when there are multiple kinds of rules under the same `defName`
**Issues**
Adds …

SortMacro() should also sort rules by Kind()

---

README.rst

Documentation
REDME
Because we have Gazelle 0.27.0 released, we should ask people to use it

Update README to use Gazelle v0.27.0

---

WORKSPACE

Other
all
Upgrade the Go toolchain to 1.19, making sure Gazelle can be built and tested with latest Go

Upgrade Go to 1.19

---

rule/rule.go
rule/rule_test.go

> Bug fix
> all
Fixes a panic in the file.Sync logic.
Fixes #1370

fix updateStmt makeslice panic

---

README.rst

Update README.rst with bazel-gazelle v0.28.0

---

deps.bzl

>
Bug fix
workspace deps
Update bazel-skylib, which hasn't happened in more than a year.
Fixes #1290

Update bazel-skylib to 1.3.0.

---

README.rst

Documentation
README file
Adds Swift extension to the language list.
NA

chore: add Swift extension to language list

---

MODULE.bazel

This was missed during the last release.

Update version in MODULE.bazel

---

README.rst

Documentation
None
Gazelle v0.29.0 is released. Updated README to use it

Updated README to use v0.29.0

---

def.bzl

Bug fix
def.bzl
Using `path` relies on legacy external runfiles.

Use `short_path` for `go` in the wrapper

---

README.rst

Fixes the gazelle directive table and add a proper space between lines.

Update gazelle directive documenmtation.

---

internal/gazelle.bash.in

Bug fix
cmd/gazelle
Fix error when running `update-repos` with 0.30.0.
Fixes #1493.
CC: @fmeum @tyler-french @seh

fix: check for gazelle command before adding -repo_config flag

---

internal/go_repository.bzl
repository.md

Documentation
go_repository
Add example on how to use a library with a major version suffix
Fixes #1442
None

Add major version suffix download example

---

MODULE.bazel
internal/bzlmod/non_module_deps.bzl

Work towards https://github.com/bazelbuild/bazel-gazelle/issues/1469

bzlmod: Use first host-compatible SDK to bootstrap Gazelle

---

README.rst
language/go/generate_test.go
walk/config.go
walk/walk.go

Bug fix
all (due to the implementation of the `gazelle:follow` directive)
This serves as a proposed resolution for #1593 but also actually implements the `follow` directive to do so.
Fixes #1593 

Fix and let `# gazelle:follow` accept a glob

---

README.rst

Documentation
README
The link formatting is incorrect.
Documentation doesn't need issues.

Fix wrong Kotlin Support link in README.

---

README.rst

Documentation
n/a
Add [gazelle_rust](https://github.com/Calsign/gazelle_rust), an extension for generating [rules_rust](https://github.com/bazelbuild/rules_rust) targets, to supported languages.
Disclaimer: I am the author of the extension.
n/a
n/a

Add gazelle_rust under supported languages

---

language/go/config.go
language/go/package.go

Other
language/go
Addressing comment on #1597 after submission
N/A

address comments from #1597

---

.bazelci/presubmit.yml
.bazelrc
WORKSPACE

Preparation for https://github.com/bazelbuild/bazel/issues/12821.

Test with incompatible flags

---

rule/rule.go
rule/rule_test.go

Bug fix
rule
Otherwise the shortcut logic in Sync() will prevent the change to be reflected in the syntax tree if no other action sets the updated flag.

rule: set update flag on Rule.AddArg

---

rule/rule.go
rule/rule_test.go

Bug fix
rule
Change the name to be more consistent with the rest of the codebase as request in
https://github.com/bazelbuild/bazel-gazelle/pull/1700#issuecomment-1871246393

rule: rename GetAttrComments -> AttrComments

---

cmd/gazelle/fix.go
cmd/gazelle/fix_test.go
cmd/gazelle/integration_test.go
cmd/generate_repo_config/generate_repo_config.go
cmd/move_labels/move_labels.go
config/config_test.go
internal/go_repository_test.go
internal/list_repository_tools_srcs.go
internal/runner_test.go
internal/wspace/finder_test.go
language/go/fileinfo_go_test.go
language/go/fileinfo_test.go
language/go/gen_std_package_list/gen_std_package_list.go
language/go/generate_test.go
language/go/modules.go
language/go/utils.go
language/proto/fileinfo.go
language/proto/fileinfo_test.go
language/proto/gen/gen_known_imports.go
language/proto/generate_test.go
repo/remote.go
repo/repo_test.go
testtools/files.go

Other
all
ioutil is deprecated, stop using it

Remove ioutil usage

---

README.rst

Documentation
`README.rst`
The Swift gazelle plugin lives in a different repository.
N/A

doc: fix link to Swift gazelle plugin

---

label/BUILD.bazel
label/label.go
rule/value.go

Other
`label`/`rule`
As discussed in https://github.com/bazelbuild/bazel-gazelle/pull/1705#issuecomment-1877119206

implement expression conversions via BzlExprValue interface

---

rule/rule.go
rule/rule_test.go

> Feature
rule
Alternative to #1713

rule: make value sorting configurable (alternative implementation)

---

internal/go_repository.bzl

Small error message fix. Noticed when got an error message that was mentioning importpath that I have actually specified and despite that got an error.

nit: fix error message in go_repository

---

language/go/generate.go

resolve https://github.com/bazelbuild/bazel-gazelle/issues/1638

allow go_visibility directive to change command package's visibility

---

MODULE.bazel

This PR creates a new release for Gazelle

prepare release 0.37.0

---

README.rst

This PR updates the readme contents for the latest releases of rules_go and gazelle

update readmes for latest release

---

cmd/gazelle/fix-update.go

Other
all
I think kind mapping is unrelated to whether indexing is enabled or not?

refactor: process KindMap even when not indexing

---

walk/walk.go

refactor: move walk util methods into struct

---

rule/rule.go

Perf improvement
gazelle core
This is a simple change that is a ~2%+ improvement on our medium-sized repo. (The 2% is easily measurable; there is also decreased GC pressure which is spread out)
Fixes #

perf: Improve rule.Kind

---

MODULE.bazel
go.mod

Bug fix
cmd/gazelle
This is needed to pick up the `qnx` and `osx` platforms from https://github.com/bazelbuild/rules_go/commit/eb9a7af825d95b0dd2fc2b07ce91665a8882c797.
Fixes #

Update rules_go dep to v0.50.1

---

MODULE.bazel

Let the Publish to BCR app maintain the module version

---

MODULE.bazel

Remove explicit empty `version` argument

---

.bcr/metadata.template.json
MODULE.bazel

Bug fix
BCR
The new style also isn't supported by Publish to BCR and a fix is in flight: https://github.com/bazel-contrib/publish-to-bcr/pull/175
Fixes #

Revert to empty version and update repo metadata

---

testtools/files.go

Bug fix
testtools
Small fix to allow newlines in `expectedExitCode.txt` files which can be added automatically by formatters.
N/A

fix: allow for newlines in expectedExitCode.txt

---

walk/walk.go

> Other
> all
Minor refactoring which will make further improvements easier.

refactor: simplify walk configuration, func signatures

---

BUILD.bazel
README.rst
docs/BUILD.bazel
extend.rst
extensions.md
internal/bzlmod/BUILD.bazel
internal/bzlmod/go_deps.bzl
internal/repository_docs.bzl
repository.md
repository.rst

Documentation
go_deps
Document the `go_deps` extension.
Also remove some ancient and unsupported repo rules from the docs.
Fixes #

Add docs for `go_deps` extension

---

internal/bzlmod/go_deps.bzl

Drops a stray `continue` that could result in incorrect Go module versions being reported if they are declared by a module further down in the tree than one that declares a `bazel_dep`.
Warnings now look like this:
```
Mismatch between versions requested for Go module github.com/cloudflare/circl:
bazel_dep version (MODULE.bazel): 1.3.7 (as "circl")
Go module version (go.mod):       1.3.8
Either ensure that you have
bazel_dep(module_name = "circl", version = "1.3.8")
in your MODULE.bazel file or downgrade the Go module version via
bazel run @my_rules_go//go:go -- get github.com/cloudflare/circl@v1.3.7
...
The following Go modules were required by the root module at the given versions, but were implicitly updated to higher versions due to transitive dependencies: …
```

Fix version resolution with bazel_deps and improve warnings

---

internal/bzlmod/default_gazelle_overrides.bzl

Other
cmd/gazelle
Proto generation must be disabled as generated proto bindings are already available in the repo.

Add more k8s.io default overrides

---

internal/bzlmod/default_gazelle_overrides.bzl

Other
internal/bzlmod
Enable build file generation on a subpath to work around https://github.com/cncf/xds/issues/104.

Add build file generation override for cncf/xds

---

walk/walk.go

perf: do not build trie for directories not being traversed

---

extend.md
internal/extend_docs.bzl

>
> Bug fix
> Feature
> Other
> For example:
>
> language/go
> cmd/gazelle
> all
Fixes #

Fix a typo in the target name, and use relative target path

---

walk/config.go
walk/walk.go

There's 2 commits here both simplifying it in different ways.
Other
all
Cleanup regarding https://github.com/bazel-contrib/bazel-gazelle/pull/2039#discussion_r1964845284

refactor: simplify walkDir signature

---

walk/walk.go

The `fs.DirEntry` result was only ever used as a boolean and leads to confusion regarding what the return result should be used for.
refactor
all
simplification

refactor: simplify symlink follow logic

---

cmd/gazelle/update-repos.go

This PR enables CPU and Memory profiling capabilities in `gazelle update-repos`
Resolves #2057
Tested locally with `gazelle update-repos`

feat(update-repos): allow users to profile gazelle update-repos

---

internal/bzlmod/go_mod.bzl
tests/bzlmod/go_mod_test.bzl

See https://go.dev/doc/modules/gomod-ref#tool and
https://go.dev/doc/go1.24#tools.
Fixes #2031
Feature
all
Don't fail parsing of go.mod if it contains a tool directive.
Fixes #2031

Support (and ignore) ‘tool’ directive in go.mod files.

---

walk/walk_test.go

Bug fix
walk
Broken since #2044. But BenchmarkWalk needs to follow the contract for Configurer.
For #1891
Part 1/4

walk: fix BenchmarkWalk

---

.bazelrc

Work around bazelbuild/continuous-integration#2269

Work around incompatibility between zlib and clang 17

---

cmd/gazelle/fix-update.go

Documentation
cmd/gazelle
A slight refinement on inline comments. I noticed that there where some comments that referred to go, but the relevant code is used for all languages.
Fixes #

Cleanup: Just updating comments as I read

---

MODULE.bazel
internal/go_repository.bzl
tests/bcr/go_mod/tests.bzl
tests/bzl_deps/BUILD.bazel
tests/cli/BUILD.bazel
tests/visibility_attr/BUILD.bazel
tests/visibility_attr/child/BUILD.bazel

Bug fix
all
Updating rules_go is required to get rid of implicit loads: https://github.com/bazel-contrib/rules_go/commit/e8adba26a407fbea9354a6d88f6f97bf3ae1106c
Fixes #2088

Run buildifier to add explicit loads and update rules_go

---

internal/bzlmod/default_gazelle_overrides.bzl

Other
cmd/gazelle
Proto generation must be disabled as generated proto bindings are already available in the repo.

Add k8s.io/cri-api k8s.io/apiserver default overrides

---

.bcr/presubmit.yml

This is the recommended test setup.

Test against latest release candidates in BCR presubmit

---

cmd/gazelle/diff.go

Bug fix
cmd/gazelle
Aligns behavior of `mode=diff` with other modes, by ensuring that newline stripping only occurs when generating patch files.
Fixes #2164

Realign diff mode exit code with other modes.

---

cmd/gazelle/diff.go
cmd/gazelle/diff_test.go

Other
cmd/gazelle
Adding unit tests to verify `mode=diff` functionality with and without newlines present.
Updates #2165
This is adding unit tests for a PR that was already approved.
#2164

Adding unit test to ensure behavior of mode=diff

---

walk/walk.go

Other
all
Remove some unreachable code
Fixes #

refactor: remove unreachable code
