bazel-contrib/bazel-gazelle

- config/platform.go
- packages/fileinfo.go
- packages/fileinfo_go.go
- packages/fileinfo_go_test.go
- packages/fileinfo_test.go
- packages/package.go
- packages/package_test.go
- packages/walk.go
- packages/walk_test.go
- rules/generator.go
- testdata/repo/cgolib/BUILD.want
PackageStrings needed a new invariant: strings must not be duplicated
across sets. For example, the same string cannot be OS-specific and
platform-specific. Bazel rejects build files where this is the case
for deps.
This change introduces platformStringsBuilder. Strings are added to
sets, and information is stored about which set each string belongs
to. The Map and Clean methods are removed; when PlatformStrings is
built, it is already clean.
This affects option strings somewhat. Unprocessed groups of options
are stored as strings with OptSeparator between each option. rules is
now responsible for splitting and quoting these.
This means order is no longer preserved for option strings (they will
be sorted when PlatformStrings is built). We couldn't actually
guarantee order before: for …
> Rewrite packages.PlatformStrings (again)

- cmd/gazelle/BUILD.bazel
- cmd/gazelle/fix-update.go
- cmd/gazelle/fix_test.go
- cmd/gazelle/flags.go
- cmd/gazelle/gazelle.go
- cmd/gazelle/integration_test.go
* Moved everything related to fix and update commands into fix-update.go
* Renamed main.go to gazelle.go
* Adjusted flag parsing.
> cmd/gazelle: split fix/update functionality into new file

- cmd/gazelle/integration_test.go
- config/constants.go
- merger/fix.go
- merger/fix_test.go
- merger/merger.go
- rules/generator.go
- rules/generator_test.go
- testdata/repo/service/BUILD.want
* If a .proto file has a service definition, we will now generate a
go_proto_library rule with a compilers dependency on
"@io_bazel_rules_go//proto:go_grpc" instead of a go_grpc_library.
* Existing go_grpc_library rules will be fixed. This is a minor fix,
since it doesn't rename, move, or delete rules, so it will run in
update mode.
Fixes #8
> Migrate go_grpc_library to go_proto_library with compilers

- resolve/index.go
- resolve/label.go
- resolve/resolve.go
- resolve/resolve_test.go
Add selfImportError, which is now returned by
RuleIndex.findRuleByImport and related methods when a rule imports
itself (which is common with protos).
Resolver methods treat this error the same as standardImportError: no
dependency is emitted.
Fixes #45
> resolve: detect when a rule imports itself

- packages/fileinfo.go
- packages/fileinfo_go.go
- packages/fileinfo_go_test.go
- packages/package.go
- packages/walk.go
- packages/walk_test.go
- rules/generator.go
- rules/generator_test.go
> packages: extract importpath from proto go_package options

- def.bzl
The extra_args (and args, via the fallback logic) are no longer being
added to the generated bash script.
> def.bzl: fix extra_args.

- cmd/gazelle/fix-update.go
- internal/merger/merger.go
- internal/merger/merger_test.go
- internal/packages/walk.go
- internal/packages/walk_test.go
- internal/resolve/index.go
- internal/resolve/resolve_test.go
runFixUpdate now merges generated rules into existing build files
before adding the rules in the merged file to the library index with
AddRulesFromFile. This avoids the need to add existing and generated
rules to the index separately. It also simplifies the index, since we
don't need to track generated and replaced rules.
Also: the '# gazelle:ignore' directive is now handled earlier in
packages.Walk instead of merger.MergeFile. This avoids extra work and
spurious error messages.
Fixes #67
> resolve: add rules to index after pre-resolve merge

- internal/merger/merger.go
- internal/rules/generator.go
- internal/rules/testdata/repo/allcgolib/BUILD.want
- internal/rules/testdata/repo/bin/BUILD.want
- internal/rules/testdata/repo/bin_with_tests/BUILD.want
- internal/rules/testdata/repo/cgolib/BUILD.want
- internal/rules/testdata/repo/cgolib_with_build_tags/BUILD.want
- internal/rules/testdata/repo/default_visibility/BUILD.want
- internal/rules/testdata/repo/default_visibility/cmd/BUILD.want
- internal/rules/testdata/repo/lib/BUILD.want
- internal/rules/testdata/repo/main_test_only/BUILD.want
- internal/rules/testdata/repo/platforms/BUILD.want
- internal/rules/testdata/repo/tests_import_testdata/BUILD.want
- internal/rules/testdata/repo/tests_with_testdata/BUILD.want
importpath is optional for these rules. Gazelle won't generate it, but
it won't remove importpath from existing rules (for now).
Also: rewrote merger init function for MergeableAttrs to be more declarative
> generator: don't generate importpath attributes for go_binary or go_test

- deps.bzl
- internal/repos/BUILD.bazel
- vendor/BUILD.bazel
- vendor/github.com/pelletier/go-toml/BUILD.bazel
- vendor/github.com/pelletier/go-toml/cmd/BUILD.bazel
- vendor/github.com/pelletier/go-toml/cmd/tomljson/BUILD.bazel
- vendor/github.com/pelletier/go-toml/cmd/tomll/BUILD.bazel
- vendor/github.com/pelletier/go-toml/query/BUILD.bazel
local_repository paths are relative to the directory containing the
main WORKSPACE file. Gazelle declared a local_repository in the
gazelle_dependencies macro for go-toml with a relative path pointing
to the vendor directory. This works inside the bazel_gazelle
workspace, but it breaks other repositories that import and use the
gazelle_dependencies macro.
> Switch to normal vendoring for go-toml

- internal/config/directives.go
- internal/config/directives_test.go
- internal/packages/walk.go
> Disable proto rule generation by default in vendor

- cmd/gazelle/diff.go
- cmd/gazelle/fix-update.go
- cmd/gazelle/fix.go
- cmd/gazelle/fix_test.go
- cmd/gazelle/print.go
This flag allows users to specify a directory where build files will
be written. There is also -experimental_out_suffix, which adds a
suffix to generated build file names.
This will be used for experimenting with new repository rules. The
flags will be removed at some point, but the functionality will
remain.
> cmd/gazelle: add -experimental_out_dir flag

- cmd/gazelle/BUILD.bazel
- cmd/gazelle/fix-update.go
- internal/label/BUILD.bazel
- internal/label/label.go
- internal/label/label_test.go
- internal/label/labeler.go
- internal/label/labeler_test.go
- internal/merger/BUILD.bazel
- internal/merger/merger.go
- internal/pathtools/path.go
- internal/repos/BUILD.bazel
- internal/repos/dep.go
- internal/resolve/BUILD.bazel
- internal/resolve/index.go
- internal/resolve/resolve.go
- internal/resolve/resolve_external.go
- internal/resolve/resolve_external_test.go
- internal/resolve/resolve_test.go
- internal/resolve/resolve_vendored.go
- internal/rules/BUILD.bazel
- internal/rules/generator.go
- internal/rules/generator_test.go
This preemptively breaks some dependency cycles.
Also: move relBaseName to pathtools
> internal/label: move Label and Labeler into new package

- internal/merger/merger.go
Gazelle won't modify or delete this attribute if it's set
in existing rules.
Fixes #86
> internal/merger: make "compilers" attribute unmergeable

- internal/merger/merger.go
- internal/merger/merger_test.go
Gazelle will now delete a rule after merging when the following
conditions are true:
* No sources were found for the rule.
* After merging, none of the attributes "srcs", "deps", "embed", or
"proto" were defined.
* The rule has no "# keep" comment at the top level.
Fixes #80
> internal/merger: delete empty rules with unmergeable attributes

- README.rst
Bazel complains when you try to override a native repository rule
after a load statement. This shows how to load rules_go and Gazelle in
a way that avoids that.
Fixes #95
[skip ci]
[ci skip]
> Fix setup instructions in README.rst

- WORKSPACE
- cmd/gazelle/fix-update.go
- cmd/gazelle/update-repos.go
- internal/repos/BUILD.bazel
- internal/repos/remote.go
- internal/repos/remote_test.go
- internal/repos/repo.go
- internal/repos/repo_test.go
- internal/resolve/BUILD.bazel
- internal/resolve/resolve.go
- internal/resolve/resolve_external.go
- internal/resolve/resolve_external_test.go
- internal/resolve/resolve_test.go
The update-repos command can now add or update go_repository rules by
import path. To use:
gazelle update-repos example.com/repo1 example.com/repo2
This will automatically discover the remote, VCS, and latest commit
for each repository containing the named packages. If a repository
already exists in WORKSPACE, it will be updated in place.
This functionality replaces wtool, which will be deleted soon after
this lands.
Related #56
> update-repos: add or update repository rules by import path

- cmd/gazelle/fix-update.go
- internal/config/config.go
- internal/config/directives.go
- internal/config/directives_test.go
If the proto mode is explicitly set to the default mode (via the
command line or directive), it will no longer be overridden by an
inferred legacy or disabled mode. It can still be overridden by an
explicit directive in a subdirectory.
Fixes #104
> internal/config: inferred proto mode can't override explicit default

- internal/config/config_test.go
- internal/config/directives.go
- internal/config/platform.go
- 1 missing format argument in test error message
- 1 removal of variable shadowing
- 2 loop range simplifications
> Address some minor warning thrown by linters.

- internal/merger/fix.go
- internal/merger/merger.go
- internal/merger/merger_test.go
Previously, Gazelle would merge a generated rule with an existing rule
if the existing rule had the same name and kind. This change makes the
matching algorithm more flexible.
* The kind must always match. This may be relaxed in the future.
* If the name doesn't match any existing rule, Gazelle will consider
other attributes based on the kind. For example, when matching
go_library, Gazelle will look for matching importpath attributes.
* go_binary rules will match any go_binary rules in the same
build file.
Fixes #106
Related #99
Fixes #17
> internal/merger: more flexible rule matching

- cmd/gazelle/BUILD.bazel
I don't see any reason not to. I do it manually by passing `--features` to `bazel run`, since my `libstdc++` is broken.
> run gazelle in pure mode

- internal/label/label.go
- internal/label/label_test.go
//a/b should have name "b", not "a/b". Also "_" is allowed in package names.
> internal/label: fix a parse error with implicit names

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
- internal/packages/package.go
- internal/packages/walk.go
- internal/packages/walk_test.go
- internal/rules/generator_test.go
This is a tool to update labels in a tree of build files after it's
been moved from another place. This is especially useful for vendoring
repositories that already have build files.
Fixes #63
> cmd/gazelle: delete rules in directories which have no source files

- cmd/gazelle/fix-update.go
- internal/wspace/finder.go
- internal/wspace/finder_test.go
Find now accepts relative paths (it calls filepath.Abs first). It was
previously misused in update-repos.go.
Fixes #118
> internal/wspace: accept relative paths

- internal/packages/fileinfo_proto.go
- internal/packages/fileinfo_proto_test.go
Proto files can fill in the `go_package` option in at least three different ways (per https://github.com/golang/protobuf/issues/139):
```proto
option go_package = "foo";
option go_package = "github.com/example/foo";
option go_package = "github.com/example/foo;bar";
```
Gazelle was only handling the latter two cases, where the option referred to a full import path. With this change, it only treats the option as an import path when it really looks like one. ([This is similar to what `protoc-gen-go` does](https://github.com/golang/protobuf/blob/bbd03ef6da3a115852eaf24c8a1c46aeb39aa175/protoc-gen-go/generator/generator.go#L272-L295).)
Fixes #124.
> Don't infer an import path from a simple package name in a proto file

- internal/overlay_repository.bzl
These are drop-in replacements for http_archive and git_repository
with the added feature that you can copy in an "overlay" set of files
using custom names. The overlay is specified as a dictionary mapping
labels to relative paths in the destination repository.
In the future, these rules will be an alternative to
go_repository. Build files may be pre-generated using Gazelle, and
then copied into repositories using an overlay.
For now, these rules are not exposed in def.bzl and are not public yet.
> internal/overlay_repository.bzl: add experimental overlay rules

- cmd/move_labels/BUILD.bazel
- cmd/move_labels/move_labels.go
- cmd/move_labels/move_labels_test.go
- internal/label/label.go
- internal/label/label_test.go
This is a tool to update labels in a tree of build files after it's
been moved from another place. This is especially useful for vendoring
repositories that already have build files.
Fixes #63
> cmd/move_labels: add tool for updating labels after move

- WORKSPACE
- internal/overlay_repository.bzl
- internal/wspace/finder_test.go
* In overlay repository rules, resolve labels before downloading the
repo. This is a backport of bazelbuild/rules_go#1349.
* Update io_bazel_rules_go to tip of master.
* Fix //internal/wspace:go_default_test, which was broken on macOS.
> Update overlay repository and rules_go

- internal/resolve/resolve.go
- internal/resolve/resolve_test.go
go_proto_compiler is responsible for adding these automatically. They
no longer need to be specified explicitly.
Fixes #46
Related #141
> Don't resolve go_proto_library dependencies on well known types

- cmd/fetch_repo/BUILD.bazel
Test was copied over earlier, just not run.
> Add test rule for fetch_repo

- cmd/gazelle/integration_test.go
- internal/merger/fix.go
- internal/merger/fix_test.go
- internal/packages/package.go
- internal/rules/generator.go
- internal/rules/generator_test.go
- internal/rules/testdata/repo/cgolib_with_build_tags/BUILD.want
- internal/rules/testdata/repo/gen_and_exclude/BUILD.want
- internal/rules/testdata/repo/platforms/BUILD.want
Platform-specfic srcs, separated with select expressions, have caused
a few problems. If the goos and goarch attributes of go_binary are
used, the wrong set of sources may be compiled. rules like go_path
will get filtered lists of sources without any way to get the
unfiltered list.
Separating sources is largely unnecessary, since rules_go also filters
sources at execution time. Therefore, this separation is being removed
by Gazelle.
* Rules generated by gazelle will now have flat srcs lists.
* Existing srcs lists will be flattened by "gazelle update" before
merging. Sources that appear multiple times will be de-duplicated,
and comments will be consolidated.
Note that Gazelle still filters sources, it just doesn't generate select
expresions for them anymore. Unbuildable sources (e.g., with …
> Stop using select in srcs

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
- cmd/gazelle/update-repos.go
- deps.bzl
- internal/merger/fix.go
- internal/merger/fix_test.go
- internal/merger/merger.go
* gazelle update-repos and gazelle fix will now change a load of
go_repository from @io_bazel_rules_go to @bazel_gazelle.
* If a new load needs to be inserted, it will be after any calls to
go_rules_dependencies, go_register_toolchains, and
gazelle_dependencies.
> Replace loads of go_repository from rules_go

- internal/config/constants.go
- internal/resolve/resolve.go
- internal/resolve/resolve_test.go
Gazelle will now resolve imports of
github.com/golang/protobuf/ptypes/X to
@io_bazel_rules_go//proto/wkt:x_go_proto.
Fixes #159, bazelbuild/rules_go#1386
> Resolve Go WKT imports to rules_go

- cmd/gazelle/fix-update.go
- internal/config/config.go
Gazelle usually ignores symlinks, but it may follow them if they point
to directories outside of the repo root (after all symlinks are
resolved).
With this change, Gazelle evaluates symlinks in the repo root. Without
this, Gazelle incorrectly decides to follow symlinks.
> Evaluate symlinks in repo root

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
- cmd/gazelle/update-repos.go
- internal/config/directives.go
- internal/merger/fix.go
When `gazelle fix` or `gazelle update-repos` are run now, Gazelle
loads go_repository from @bazel_gazelle instead of @io_bazel_rules_go.
This is problematic for repositories that haven't updated to the new
Gazelle yet.
Gazelle now checks for @bazel_gazelle (or a gazelle:repo directive)
when modifying the WORKSPACE file. If it's needed but not present,
Gazelle will print an error.
Unfortunately, the repo can't be loaded automatically without a
hardcoding versions and sha256 sums, accessing the network, or Bazel
directory hackery.
> Check that bazel_gazelle is loaded when fixing the WORKSPACE file

- BUILD.bazel
- cmd/gazelle/BUILD.bazel
- internal/label/labeler.go
- internal/label/labeler_test.go
- internal/merger/fix.go
- internal/merger/fix_test.go
- internal/packages/BUILD.bazel
- internal/packages/fileinfo.go
- internal/packages/fileinfo_go.go
- internal/packages/fileinfo_go_test.go
- internal/packages/fileinfo_test.go
- internal/packages/package.go
- internal/resolve/resolve.go
- internal/resolve/resolve_test.go
- internal/rules/BUILD.bazel
- internal/rules/generator.go
- internal/rules/generator_test.go
- internal/rules/testdata/repo/lib/BUILD.want
- internal/rules/testdata/repo/platforms/BUILD.want
- internal/rules/testdata/repo/tests_import_testdata/BUILD.want
- internal/rules/testdata/repo/tests_with_testdata/BUILD.want
- vendor/github.com/bazelbuild/buildtools/build/BUILD.bazel
- vendor/github.com/bazelbuild/buildtools/tables/BUILD.bazel
- vendor/github.com/pelletier/go-toml/BUILD.bazel
- vendor/github.com/pelletier/go-toml/cmd/BUILD.bazel
- vendor/github.com/pelletier/go-toml/cmd/tomljson/BUILD.bazel
- vendor/github.com/pelletier/go-toml/cmd/tomll/BUILD.bazel
- vendor/github.com/pelletier/go-toml/query/BUILD.bazel
* Gazelle no longer generates separate `go_default_test` and `go_default_xtest` targets for internal tests. A single `go_test` is generated containing sources for both internal and external parts. rules_go has been able to sort these out for a while.
* `gazelle fix` will squash existing `go_default_xtest` rules into `go_default_test` (or just rename if there is no `go_default_test`).
* That required a fair amount of refactoring to the squash functionality. I'm still not happy with this though; we need a replacement for `build.Rule` so we can work at a higher level of abstraction.
* `Resolver.ResolveRule` now treats imports provided by embeds as self-imports, so they won't show up in `deps`. Before this fix, tests got broken when they listed the library under test in `embeds` and `deps`. …
> Squash internal and external go_tests

- internal/merger/fix.go
- internal/merger/fix_test.go
The importpath attribute on go_binary and go_test was recently
un-deprecated, and Gazelle should not remove it anymore. It's used by
go_path and potentially other tools to place source files.
> Remove fix transformation removing go_binary, go_test importpath

- internal/resolve/resolve.go
- internal/resolve/resolve_test.go
When Go code generated from protos (via go_proto_library) import WKT
packages, they implicitly depend on targets in
@io_bazel_rules_go//proto/wkt. When static Go code imports the same
packages, Gazelle can resolve the dependencies differently. This
results in conflicting dependencies in many builds.
With this change, Gazelle has special cases for every target in
@io_bazel_rules_go//proto/wkt.
Fixes #159
> Add all special cases for Go importing WKT proto packages

- cmd/gazelle/BUILD.bazel
- cmd/gazelle/fix-update.go
- internal/generator/BUILD.bazel
- internal/generator/generator.go
- internal/generator/generator_test.go
- internal/packages/BUILD.bazel
- internal/packages/fileinfo_go_test.go
- internal/packages/package.go
- internal/packages/package_test.go
- internal/packages/walk_test.go
- internal/repos/BUILD.bazel
- internal/repos/repo.go
- internal/rule/BUILD.bazel
- internal/rule/platform_strings.go
- internal/rule/rule.go
- internal/rule/sort_labels.go
- internal/rule/value.go
* generator.KeyValue and GlobValue are moved to rule.
* generator.newValue is moved and renamed to rule.ExprFromValue.
* generator.newRule and emptyRule and removed to rule
temporarily. These will be replaced with the new rule editing
abstraction soon.
* generator/sort_labels.go is moved to rule temporarily. The rule
editing abstraction will do this automatically.
* packages.PlatformStrings is moved to rule.
> Extract types from generator and packages into new rule package

- cmd/gazelle/integration_test.go
- internal/packages/package.go
- internal/packages/walk.go
Previously, when entering a vendor directory, the importmap prefix was
set to the workspace name (read from WORKSPACE) concatenated with the
relative path in the repository. This was originally intended to be
just a unique value for disambiguating packages.
importmap is now used when formatting source file names. In
particular, it is used to place files in go_path. Gazelle should make
importmaps match what is expected in a GOPATH directory as much as
possible.
Unfortunately, this will result in some build file churn, but it seems
much better to fix this here than to add convoluted, error-prone logic
to go_path and anything else that uses importmap.
Fixes bazelbuild/rules_go#1509
Fixes bazelbuild/rules_go#1450
Fixes bazelbuild/rules_go#1406
> Set importmap in vendor to prefix concatenated with relative path

- cmd/gazelle/fix-update.go
This fixes an error that occurs when Gazelle's positional command line
arguments are symbolic links.
> Evaluate symlinks in positional arguments

- README.rst
- WORKSPACE
Also, use a newer version of rules_go in WORKSPACE.
Related bazelbuild/rules_go#1515
> Update gazelle boilerplate to use @bazel_tools repo rules

- internal/merger/fix.go
- internal/merger/fix_test.go
migrateLibraryEmbed was converting library attributes to embed in all
rules, including rules not generated by Gazelle. We should only do
this for Go rules.
Fixes #211
> fix: only migrate library attributes for Go rules

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
- internal/merger/merger.go
This fixes an issue where deps attributes in rules with "# keep"
comments were getting replaced. We were modifying rules directly after
the pre-resolve merge without checking for "# keep" comments. Instead,
dependency resolution should modify generated rules. The merger will
respect "# keep" comments during the post-resolve merge.
Fixes #212
> resolve: modify generated rules instead of merged rules

- WORKSPACE
- cmd/gazelle/BUILD.bazel
- cmd/gazelle/fix-update.go
- cmd/gazelle/update-repos.go
- internal/config/BUILD.bazel
- internal/config/config.go
- internal/config/config_test.go
- internal/packages/walk.go
* Move handling of -repo_root to config.CommonConfigurer. -repo_root
now behaves the same across commands: in fix and update, if
-repo_root is unspecified, and one positional argument is given, we
no longer search that for the repository root.
* Move fix, update, and update-repos flags into Configurers. This
makes flag handling a lot more uniform. There are still a lot of Go
flags in fix-update that will be moved later.
* Update to a new version of rules_go (bazel_test was broken with
bazel 0.14. This has been fixed on master).
> More config refactoring

- WORKSPACE
- internal/generator/generator.go
- internal/generator/generator_test.go
- internal/merger/BUILD.bazel
- internal/merger/merger.go
- internal/packages/BUILD.bazel
- internal/repos/BUILD.bazel
- internal/resolve/BUILD.bazel
- internal/resolve/resolve.go
- internal/rule/rule.go
- internal/rule/rule_test.go
- vendor/github.com/bazelbuild/buildtools/build/BUILD.bazel
- vendor/github.com/bazelbuild/buildtools/tables/BUILD.bazel
- vendor/github.com/pelletier/go-toml/BUILD.bazel
- vendor/github.com/pelletier/go-toml/cmd/BUILD.bazel
- vendor/github.com/pelletier/go-toml/cmd/tomljson/BUILD.bazel
- vendor/github.com/pelletier/go-toml/cmd/tomll/BUILD.bazel
- vendor/github.com/pelletier/go-toml/query/BUILD.bazel
Private attributes are now stored in a separate map and are accessed
through separate methods. They no longer need a special prefix and no
longer need to be convertible to bzl.Expr.
Also:
* Update io_bazel_rules_go in WORKSPACE to get a bazel_test that
doesn't use --nomaster_blazerc, which causes an error in Bazel 0.14.
* Update build files.
> rule: separate private attributes from regular attributes

- cmd/fetch_repo/BUILD.bazel
- deps.bzl
- internal/go_repository.bzl
- internal/repos/BUILD.bazel
- internal/resolve/BUILD.bazel
- vendor/golang.org/x/tools/go/vcs/BUILD.bazel
- vendor/golang.org/x/tools/go/vcs/discovery.go
- vendor/golang.org/x/tools/go/vcs/env.go
- vendor/golang.org/x/tools/go/vcs/http.go
- vendor/golang.org/x/tools/go/vcs/vcs.go
- vendor/golang.org/x/tools/go/vcs/vcs_test.go
Keeping an external repository for @org_golang_x_tools in sync with
rules_go is too much work. We just need this one tiny package.
Also:
* Make go_repository_tools use vendored packages. Not sure why it was
working before.
* Format .bzl files.
> Vendor golang.org/x/tools/go/vcs

- internal/rule/rule.go
- internal/rule/rule_test.go
Before this fix, the index of load statements and rules (stored in
baseStmt) was not updated when the file was synced. It would no longer
point to the correct statement in the build file if insertions or
deletions occurred in earlier parts of the file.
> Update statement indices after rule.File.Sync

- internal/go_repository.bzl
Signed-off-by: Bin Lu <bin.lu@arm.com>
> Go link tool need to find gcc on Arm platform

- internal/repos/remote.go
Old versions of git don't understand this argument and exit with
code 129.
Fixes #238
> Don't pass "--" argument to git ls-remote

- internal/language/go/fileinfo.go
- internal/language/go/fileinfo_test.go
"race" and "msan" may or may not be enabled, and the compile builder
will filter these sources appropriately. We should ignore these tags,
just like we ignore cgo and release tags.
Fixes #233
> internal/language/go: ignore "race" and "msan" tags

- internal/go_repository.bzl
- internal/language/go/fileinfo.go
- Fix fileinfo.go to handle Windows paths.
- Pass skylark files as strings.
> Windows Fixes

- cmd/gazelle/fix-update.go
- internal/config/BUILD.bazel
- internal/config/directives.go
- internal/config/directives_test.go
- internal/label/label.go
- internal/language/go/generate.go
- internal/language/go/generate_test.go
- internal/language/lang.go
- internal/language/proto/generate.go
- internal/language/proto/generate_test.go
* Language.GenerateRules now accepts an otherEmpty parameter, a list
of empty rules that may be deleted.
* label.Rel can remove the repo name for labels in the same repo.
* Removed dead config.InferProtoMode.
Related bazelbuild/rules_go#1548
> Miscelleneous changes before adding new proto modes

- internal/overlay_repository.bzl
`cp` is not a recognized command on Windows.
> Use symlink for overlay files.

- README.rst
- internal/language/go/generate.go
- internal/language/go/resolve.go
- internal/language/go/resolve_test.go
- internal/language/proto/config.go
- internal/language/proto/generate.go
- internal/language/proto/resolve.go
Similar to disable mode in that no proto_library or go_proto_library
rules will be generated. Additionally, all special cases for WKTs and
Google APIs in the dependency resolution will be disabled. This is
useful for avoiding build-time dependencies on protoc.
Related bazelbuild/rules_go#1548
>  internal/language/proto: disable_global mode

- cmd/gazelle/integration_test.go
- internal/flag/flag.go
- internal/language/go/config.go
- internal/language/proto/config.go
flag documentation states that Value.String may be called with a zero
valued receiver, such as a nil pointer. In fact, these methods may be
called with a non-nil receiver that points to a zero-valued object.
Fixes #256
> cmd/gazelle: fix panics when generating help text

- internal/language/go/generate.go
- internal/language/go/resolve.go
- internal/language/go/resolve_test.go
Several commonly used libraries in github.com/golang/protobuf depend
on WKTs. We have two versions of these libraries: one that depends on
pre-generated WKT libraries, and one that depends on
build-time-generated WKT libraries. This change adds special cases for
these import paths.
> internal/language/go: special cases for ptypes and other libs

- internal/language/go/resolve.go
- internal/language/go/resolve_test.go
- internal/language/proto/resolve.go
- internal/repos/remote_test.go
- internal/resolve/index.go
The FindResult struct returned by RuleIndex.FindRulesByImport now
includes Embeds, a list of labels of embedded rules. This includes
transitive embeds.
FindResult.IsSelfImport returns whether a FindResult matches a given
label or contains the label in Embeds. When this is true, callers
should report an error or omit the dependency.
Fixes #247
> internal/resolve: provide self-import check including embeds

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
- internal/language/go/fix.go
- internal/rule/rule.go
Remove loads of "gazelle" from "@io_bazel_rules_go//go:def.bzl". Load
instead from "@bazel_gazelle//:def.bzl".
Fixes #239
> internal/language/go: fix load of gazelle macro

- README.rst
- internal/language/go/config.go
- internal/language/go/config_test.go
Gazelle will now read the "prefix" attribute from a gazelle rule if
the prefix is not set on the command line or in a directive. This
removes an unintuitive sharp edge.
Also, update README.rst. Much earlier, the prefix attribute was
mandatory. This is no longer the case. The readme now advises people
to use the directive instead of the attribute.
> internal/language/go: read prefix attribute from gazelle rule

- cmd/gazelle/BUILD.bazel
This avoids the dependency on bazel --feature flags and system libc. The idea is the same as in https://github.com/bazelbuild/rules_go/pull/1615.
> Explicitly specify build mode for Gazelle binary

- cmd/gazelle/diff.go
- cmd/gazelle/fix-update.go
- cmd/gazelle/fix.go
- cmd/gazelle/fix_test.go
- cmd/gazelle/gazelle.go
- cmd/gazelle/integration_test.go
- cmd/gazelle/print.go
- cmd/gazelle/update-repos.go
- internal/config/config.go
- internal/config/config_test.go
- internal/language/go/config_test.go
- internal/language/go/fix_test.go
- internal/language/go/generate_test.go
- internal/language/go/resolve_test.go
- internal/language/proto/generate_test.go
- internal/language/proto/resolve.go
- internal/language/proto/resolve_test.go
- internal/merger/merger.go
- internal/merger/merger_test.go
- internal/repos/import_test.go
- internal/repos/repo_test.go
- internal/resolve/index.go
- internal/rule/merge.go
- internal/rule/rule.go
- internal/rule/rule_test.go
- internal/walk/walk.go
* The flags -experimental_{read,write}_build_files_dir may now be used
to read and write build files to alternate directories, which may be
outside of the repository root.
* When a build file is read from an alternate directory, the build
file in the source directory is ignored.
* When a build file is written to an alternate directory, any existing
build file in that directory is replaced. The build file in the
source directory is not updated.
> Experimental: read and write build files in alternate directories

- internal/go_repository.bzl
I'm trying to package up Bazel watcher for Nix, but I'm running into an issue where the SSL certificate fails. It fails because nix builds in a sandbox that has no /etc in path. I need to export GIT_SSL_CAINFO in order for git to find the tls certs.
> go_repository should allow the env var GIT_SSL_CAINFO

- internal/language/go/BUILD.bazel
- internal/language/go/config_test.go
- internal/language/go/fileinfo_go_test.go
- internal/language/go/fileinfo_test.go
- internal/language/go/fix_test.go
- internal/language/go/generate_test.go
- internal/language/go/resolve_test.go
- internal/language/proto/BUILD.bazel
- internal/language/proto/generate_test.go
- internal/testtools/BUILD.bazel
- internal/testtools/config.go
- internal/walk/BUILD.bazel
- internal/walk/walk_test.go
testtools currently provides one function, NewTestConfig, which
produces a config.Config for tests in other packages. internal/walk,
internal/language/proto, and internal/language/go are migrated to use
this. This should reduce the amount of hackery around test
configuration.
> internal/testtools: new package for test utilities

- cmd/gazelle/fix-update.go
- internal/language/go/config_test.go
- internal/language/proto/generate_test.go
- internal/walk/config.go
- internal/walk/walk.go
- internal/walk/walk_test.go
internal/walk.Configurer is now public. A walk.Configurer
implementation must be included in the cexts. This normalizes handling
of configuration within walk.
Also, a small change to the way walkConfig tracks excluded files: each
excluded file is a path relative to the repository root instead of a
path relative to the current directory.
> internal/walk: make Configurer public

- internal/gazelle.bash.in
The script produced by the gazelle rule tries to set GOROOT to the SDK
used by rules_go. This depends on runfiles. With this change, the
script will read the MANIFEST file if runfile symlinks aren't
present. It will also skip setting GOROOT if it fails.
Fixes #321
> Make gazelle rule work on Windows

- internal/walk/walk_test.go
Walk was getting confused by a symlink in the temporary
directory. This only happened with go test, not with Bazel.
> Fix internal/walk.TestUpdateDirs on macOS

- cmd/gazelle/BUILD.bazel
- cmd/gazelle/diff.go
- cmd/gazelle/diff_test.go
- cmd/gazelle/fix-update.go
- cmd/gazelle/fix.go
- cmd/gazelle/fix_test.go
- cmd/gazelle/print.go
- go.mod
- go.sum
- vendor/github.com/pmezard/go-difflib/LICENSE
- vendor/github.com/pmezard/go-difflib/difflib/BUILD.bazel
- vendor/github.com/pmezard/go-difflib/difflib/difflib.go
- vendor/modules.txt
* -mode=diff now uses github.com/pmezard/go-difflib to produce
unified diffs instead of shelling out to diff -u.
* diff filenames are normally relative paths within the workspace (the
"from" path is /dev/null for new files).
* When -experimental_{read,write}_build_files_dir are in use, those
files are shown in the diff instead. The original file will come
from the read directory.
* A new flag is added: -patch=path. When used with -mode=diff, gazelle
writes the diffs to the given file.
> cmd/gazelle: fix and update commands can now write patch files

- def.bzl
- internal/gazelle.bash.in
* find_runfile is new function used to locate runfiles. This is used
to locate the go tool and the gazelle executable.
* BUILD_WORKSPACE_DIRECTORY is used instead of dereferencing the
WORKSPACE symlink.
Fixes #321
> Fixes for gazelle rule

- cmd/gazelle/BUILD.bazel
- cmd/gazelle/diff_test.go
- cmd/gazelle/fix_test.go
- cmd/gazelle/integration_test.go
- cmd/move_labels/BUILD.bazel
- cmd/move_labels/move_labels_test.go
- internal/testtools/BUILD.bazel
- internal/testtools/files.go
- internal/walk/walk_test.go
Moved the various implementations of createFiles, checkFiles into
testtools. This should simplify testing, and it should fix those
annoying symlink errors on darwin once and for all.
> internal/testtools: CreateFiles, CheckFiles

- README.rst
- cmd/gazelle/fix-update.go
- internal/language/go/config_test.go
- internal/language/go/resolve.go
- internal/language/go/resolve_test.go
- internal/language/proto/generate_test.go
- internal/language/proto/resolve.go
- internal/language/proto/resolve_test.go
- internal/resolve/BUILD.bazel
- internal/resolve/config.go
- internal/resolve/index.go
Users can now write directives like:
"# gazelle:resolve source-lang [import-lang] import-string label"
to override normal dependency resolution rules. These overrides behave
like normal configuration directives: they are effective in the
directory of the build file that contains them as well as
subdirectories.
Fixes #217
> internal/resolve: add gazelle:resolve directive

- internal/go_repository.bzl
git uses this to locate $HOME/.gitconfig, which may include settings
that go_repository should observe.
Fixes #330
> go_repository: pass HOME to fetch_repo

- internal/language/go/resolve.go
- internal/language/go/resolve_test.go
The import "google.golang.org/grpc" now resolves to the label
"@org_golang_google_grpc//:go_default_library" when proto rule
generation is enabled.
go_proto_library adds this dependency implicitly when the go_grpc
compiler is used. If google.golang.org/grpc is vendored and gazelle
resolves the vendored version, that causes conflicts which are
difficult to resolve.
This can be bypassed by disabling proto rule generation or using the
new "# gazelle:resolve" directive.
Fixes #217
> internal/language/go: special case for google.golang.org/grpc

- README.rst
- internal/walk/config.go
- internal/walk/walk.go
- internal/walk/walk_test.go
'# gazelle:follow link' directives can now be written in build
files. Gazelle will symbolic links to directories named in these
directives. Gazelle normally doesn't follow symbolic links within a
repository.
Care must be taken to avoid visiting a directory more than once. The
'# gazelle:exclude' directive may be used for this.
> internal/walk: add follow directives to follow symlinks

- internal/go_repository.bzl
while bazel will respect NO_PROXY but bazel-gazelle doesn't respect. So NO_PROXY should be add into env_list
> add NO_PROXY in env_keys while fetching repos for respecting system's NO_PROXY

- README.rst
- internal/repos/BUILD.bazel
- internal/walk/BUILD.bazel
- internal/walk/config.go
-exclude=foo/bar is equivalent to "# gazelle:exclude foo/bar" in the
root build file.
The motivation for this is to provide a simple way to exclude the
vendor directory in go_repository rules, but in a language-neutral
way.
Fixes #300
> internal/walk: add -exclude command line option

- internal/language/go/fileinfo.go
- internal/language/go/testdata/cgolib/BUILD.want
- internal/language/go/testdata/cgolib/foo.go
Previously, if a cgo file in the project root contained a directive
like `#cgo CPPFLAGS: -I${SRCDIR}/foo`, it would be expanded to
-I/foo. It will now be expanded to -I./foo, which gets simplified to
-Ifoo.
Fixes #348
> internal/language/go: replace ${SRCDIR} with "." in project root

- language/go/resolve.go
- language/go/resolve_test.go
rules_go and bazel-gazelle both have workspace names that don't follow
normal naming conventions. Both are typically declared with
http_archive instead of go_repository. When libraries from these
repositories are imported, Gazelle will fail to generate correct
labels.
This change adds special cases for these repositories in language/go.
Fixes #363
> language/go: add special cases for rules_go and gazelle imports

- language/go/config.go
- language/go/fix.go
- language/go/generate.go
- language/go/package.go
- language/go/resolve.go
- language/proto/config.go
The Go extension no longer requires the proto extension to be run
first. If the proto extension is not run, it should behave as if the
proto extension ran in "disable_global" mode.
Fixes #364
> language/go: break hard dependency on language/proto

- def.bzl
Deprecated in https://github.com/bazelbuild/bazel-skylib/pull/58
> Don't use deprecated lib.bzl

- WORKSPACE
Bazel 0.20 deprecates APIs used in older versions of rules_go.
> Update rules_go dependency to 0.16.2

- def.bzl
- deps.bzl
Progress towards https://github.com/bazelbuild/rules_go/issues/1829
> Explicitly export symbols that need it, reformat files with Buildifier

- internal/go_repository.bzl
Currently, the builds for helper utilities `fetch_repo` and `gazelle` aren't deterministic, and have hashes that change depending on where they're built.  Since these are built as repository rules, it makes it tricky to prefetch dependencies using [`bazel sync`](https://blog.bazel.build/2018/07/09/bazel-sync-and-resolved-file.html), since the hash of dependencies will change per-build.
These changes build the helper utilities with the appropriate set of flags to ensure that they're deterministic; this can be tested by running `strings path-to-gazelle | egrep '(\/bazel\/|\/tmp\/)'`.
Let me know if this works for you folks!  All tests pass locally on Linux with these changes.
> Make helper tool build deterministic

- language/go/fileinfo.go
- language/go/fileinfo_test.go
- language/go/generate.go
- walk/walk.go
- walk/walk_test.go
Go considers these hidden files and does not build them. The logic for
filtering these should be in the Go extension instead of walk, since
other languages don't have the same rule.
Fixes #395
> walk: don't exclude file names starting with "_"

- repo/dep.go
- repo/import_test.go
`bazel-gazelle/cmd/fetch_repo` command requires `--vcs` to be present when  `--remote` is present.  As a result, when there is `source` field in dep lock file, the `vcs` field should be populated for the resulting `go_repository` rules as well. Otherwise the subsequent bazel build will fail when it is calling gazelle to fetch external libraries.
> populating VCS field when go_repository's remote is not null

- walk/walk.go
- walk/walk_test.go
As discussed in #164, Go allows to import packages under hidden directories. If that happens, there is no way to generate build files for those packages. On the other hand, if there are unbuildable Go files in hidden directories, but Gazelle generates build files for them, it is easy to exclude them with `# gazelle: exclude` directives, the same strategy with "testdata"
Our scenario: in some of our projects, we check in the generated code under `.gen` directories. Those directories should be treated as regular Go package.
Fixed #164
> Include hidden directories during walking

- repo/modules.go
- repo/modules_test.go
Go modules use three forms of pseudoversions (per go help modules).
Adjust the regexp used for extracting commit hashes to match the second
and third types. (also block-quote the relevant documentation)
fixes: #417
> repo: There are three go pseudoversion formats

- cmd/gazelle/diff.go
- cmd/gazelle/diff_test.go
- cmd/gazelle/fix-update.go
- cmd/gazelle/gazelle.go
Return status code 1 when mode is diff and there are changes.
I've tried to work according to your comments in #366. Apologies for strange syntax/undesirable naming, this is the first time I've written any go code.
> Exit error status when diff and run in diff mode

- cmd/move_labels/move_labels.go
- go.mod
- go.sum
- vendor/github.com/bazelbuild/buildtools/build/lex.go
- vendor/github.com/bazelbuild/buildtools/build/parse.y
- vendor/github.com/bazelbuild/buildtools/build/parse.y.go
- vendor/github.com/bazelbuild/buildtools/build/print.go
- vendor/github.com/bazelbuild/buildtools/build/rewrite.go
- vendor/github.com/bazelbuild/buildtools/build/syntax.go
- vendor/github.com/bazelbuild/buildtools/build/walk.go
- vendor/modules.txt
* Update github.com/bazelbuild/buildtools. In the latest version,
build.WalkOnce recurses into children of LoadStmt.
* Remove workaround in cmd/move_labels that recursed into children of
LoadStmt.
> cmd/move_labels: remove workaround for LoadStmt

- language/go/resolve.go
- language/go/resolve_test.go
This should be resolved to the canonical external location in modes
where go_proto_library is in use.
> language/go: special case for github.com/golang/protobuf/proto

- language/proto/config.go
- language/proto/config_test.go
Gazelle was printing the build file path instead of `proto_strip_import_prefix` when prefix is invalid. This PR fixes that.
> fixed error message

- testtools/files.go
This makes the output from the t.Error function report that it
is coming from the actual test instead of from the testtools
library.
> Add t.Helper() to all the testtools helper methods

- language/proto/generate.go
- language/proto/testdata/protos/BUILD.old
- language/proto/testdata/protos/BUILD.want
In the course of developing #448 , I identified a bug that results in non-proto files
being included in the srcs of generated proto_library rules, if any generated
proto files were present in that directory.
This change updates the existing protos test case that identifies that bug and
makes the small fix.
This scenario seems unlikely to come up in practice, so it's possible that no one has actually run into it.
> proto/generate: fix inclusion of generated files in proto_library targets

- cmd/fetch_repo/BUILD.bazel
- cmd/fetch_repo/fetch_repo.go
- cmd/fetch_repo/module.go
- cmd/fetch_repo/vcs.go
- deps.bzl
- internal/BUILD.bazel
- internal/go_repository.bzl
- internal/list_repository_tools_srcs.go
- repository.rst
go_repository has two new attributes: version and sum. If version is
specified, go_repository will run in module mode (distinct from
repository mode and http mode). version and sum must be specified
together.
In module mode, go_repository invokes fetch_repo with -version and
-sum arguments. fetch_repo will run "go mod download" to retrieve the
module.
Fixes #400
> go_repository: support modules

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
- cmd/gazelle/metaresolver.go
- language/go/resolve_test.go
- language/proto/resolve_test.go
- resolve/index.go
This previously assumed a *rule.File would be present for every kind mapping,
which is not the case for packages that lack a pre-existing BUILD file. This
change indexes the mapped kinds by the package relative path instead, with ""
denoting "ignore mapped kinds". This also adds a test to identify the problem
and verify the fix.
Fixes #469
> map_kind directive: fix bug in handling of packages lacking a BUILD file

- walk/config.go
- walk/walk.go
- walk/walk_test.go
As a special case, a build file may exclude its own directory. This is
similar to "# gazelle:ignore" but it also covers subdirectories.
Updates #472
> walk: allow "# gazelle:exclude ."

- language/go/resolve.go
The old error message is not very useful: it is difficult to scan
visually, once you scan it it is not clear what it means, it offers no
suggestions at all what to do to fix the issue, and is very difficult to
google a solution for.
The new error is somewhat more verbose, but uses clearer language
(where the issue is comes first, details later) and offers clear ways
to resolve the issue.
Handles #478 in part.
> Clarifies "ambiguous import" message

- cmd/gazelle/BUILD.bazel
- cmd/gazelle/update-repos.go
- cmd/gazelle/update_repos_test.go
`build_extra_args` of `go_repository` rules is a list. However, Gazelle passed it as a string, causing build failures in the resulting `go_repository` rules. This PR fixed that.
> build_extra_args should be a list

- cmd/gazelle/fix-update.go
- cmd/gazelle/update-repos.go
- internal/go_repository.bzl
- language/go/config.go
- language/go/resolve.go
- language/go/resolve_test.go
- repo/remote.go
- repo/remote_test.go
- repo/stubs_test.go
This change adds a new flag to the Go extension,
-go_experimental_module_mode. It is off by default, but is turned on
when go_repository runs in module mode or when a go.mod file is
found. In the future, this flag will be removed, and we'll always run
in module mode.
When enabled, this flag changes how remote dependency resolution
works. Instead of using golang.org/x/tools/go/vcs (which does not
know about modules), we'll use "GO111MODULE=on go list <path>" in a
temporary directory. No special cases are enabled, but known
repositories from WORKSPACE and -known_repo arguments will be
observed.
Fixes #473
> language/go: experimental module mode

- internal/go_repository.bzl
Many tools support or even prefer the lowercase version of the {http,https,no}_proxy environment variables. This PR adds support for passing the lowercase version through Gazelle.
For example:
* Golang supports both versions but the uppercase takes precedence (https://github.com/golang/net/blob/d196dffd7c2beec1957382065df08bcc353b9706/http/httpproxy/proxy.go#L91-L98)
* curl gives precedence to the lowercase version of all 3 variables but accepts the uppercase version for HTTPS_PROXY and NO_PROXY (https://github.com/curl/curl/blob/e3a53e3efb942a5446a22725340e36af63f1632e/lib/url.c#L2430-L2446)
> Support lowercase version of *_proxy env vars

- repo/remote.go
Without this, `go list` will not use the Bazel-provided Go SDK, since `GOROOT` is ignored.
> Use findGoTool() for "go list"

- internal/go_repository.bzl
- repository.rst
go_repository now provides a "replace" attribute. This allows an
alternative module to be downloaded. The "version" and "sum"
attributes are used on the replacement, not the original
module. Gazelle is run as if it were on the original module though, so
import paths and labels will be the same.
Fixes #488
> go_repository: replace attribute

- language/go/kinds.go
- repo/import_test.go
- repo/modules.go
- repo/repo.go
- repo/stubs_test.go
I think this may also partially address the issue raised in #407, that the replace directive in go.mod is not handled properly.
I noticed this at first when trying to add [Pulumi](https://github.com/pulumi/pulumi/) as a third_party dependency.
```
gazelle: error parsing "go.mod": exit status 1
```
With this patch I am able to directly run an `update-reps` and generate a proper `go_repository`.
For a given `go.mod`:
```
require (
github.com/Nvveen/Gotty v0.0.0-20170406111628-a8b993ba6abd
)
replace (
github.com/Nvveen/Gotty => github.com/ijc25/Gotty v0.0.0-20170406111628-a8b993ba6abd
)
```
Gazelle will produce:
```
go_repository(
name = "com_github_nvveen_gotty",
importpath = "github.com/Nvveen/Gotty",
replace = "github.com/ijc25/Gotty",
sum = …
```
> Add support for the replace directive in go.mod 

- language/go/resolve.go
- language/go/resolve_test.go
`google/protobuf/compiler/plugin.proto` was incorrectly written as `google/protobuf/compiler_plugin.proto` which doesn't exist in https://github.com/protocolbuffers/protobuf/tree/master/src/google/protobuf.
> language/go: fix typo s|compiler_plugin|compiler/plugin| in wkt map

- internal/go_repository.bzl
These environment variables allow the `ssh` implementation to be overridden when cloning a Go repository with SSH.
> go_repository: Support GIT_SSH and GIT_SSH_COMMAND env vars

- internal/go_repository.bzl
Gazelle considers most errors non-fatal. It prints warnings and exits 0.
go_repository should at least print these.
Updates #498, but this is by no means a complete solution.
> go_repository: print stderr, even on success

- repo/import_test.go
- repo/modules.go
- repo/stubs_test.go
`go list -m -json all` can list the same importpath twice, one with a replace directive and one without. This change fixes `update-repos` to properly handle the case when multiple modules are listed with the same importpath.
Fixes #521
> Don't override modules with replace directives

- repo/remote.go
https://github.com/bazelbuild/bazel-gazelle/pull/522 updated go_repository to print Gazelle warnings.
For `ls-remote` and `go list` failures the error is always printed as something like `exit status 1`.
This change updates the error messages to be something like 
`exit status 1 : failure printed to stderr`
> Improve error logging for go_repository

- cmd/fetch_repo/vcs.go
- deps.bzl
- internal/BUILD.bazel
- internal/go_repository.bzl
gazelle_dependencies will now detect any declared Go SDK
repository. It may use a go_download_sdk with goos and goarch set to
the host platform, or a go_host_sdk, or an SDK named "go_sdk".
If an appropriate repository can't be discovered, gazelle_dependencies
accepts a go_sdk parameter, which can be used to set the name.
Updates bazelbuild/rules_go#1507
> go_repository: don't require a repository named "go_sdk"

- internal/go_repository.bzl
- repository.rst
#394 
Adds the `GO_REPOSITORY_USE_HOST_CACHE` environment variable, which when set will tell `go_repository` to share the user's module cache. This is achieved by having Bazel's go toolchain use the same `GOPATH` and `GOCACHE` as the local go toolchain.
> GO_REPOSITORY_USE_HOST_CACHE enables a shared mod cache

- internal/go_repository.bzl
The test wether there were build files in a go_repository were done
before actually fetching it, making gazelle always generate BUILD files,
instead of doing it automatically.
This fixes build_file_generation="auto".
> Detect BUILD files after fetching the repo

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
I found this bug when mapping a second kind in my project. I wrote a test that reproduces it and fixed it.
> map_kind: fix bug in merging loads for multiple mappings

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
- deps.bzl
- go.mod
- internal/go_repository.bzl
- internal/go_repository_cache.bzl
- internal/go_repository_tools.bzl
'gazelle fix' and 'gazelle update' now accept -repo_config, the path
to a file where information about repositories can be loaded. By
default, this is WORKSPACE in the repository root directory.
'gazelle fix' and 'gazelle update-repos' still update the WORKSPACE
file in the repository root directory when this flag is set.
go_repository passes the path to @//:WORKSPACE to -repo_config.
go_repository resolves @//:WORKSPACE and any files mentioned in
'# gazelle:repository_macro' directives. When these files, all
go_repository rules will be invalidated. It should not be necessary to
download cached repositories (except vcs repositories; see #549).
On a Macbook Pro, it takes about 22.5s to re-evaluate 70 cached,
invalidated go_repository rules for github.com/gohugoio/hugo. If this
becomes a …
> go_repository: read configuration from main WORKSPACE

- README.rst
- extend.rst
> Document community extensions [skip ci]

- cmd/BUILD.bazel
- deps.bzl
- internal/BUILD.bazel
- internal/go_repository.bzl
- internal/go_repository_test.go
- internal/language/BUILD.bazel
- internal/language/test_filegroup/lang.go
- repository.rst
* Updated to rules_go at master to get compatibility fixes, new features for
minimal module compatibility, and `go_bazel_test`.
* Rewrote `//internal:repository_rules_test` to `//internal:go_repository_test`.
The old test was broken by incompatible changes in new versions of Bazel.
The new test uses a new integration testing framework. We should be able
to improve `go_repository` test coverage in the future.
* Added `//internal/language/test_filegroup`, an extension that generates
`all_files` `filegroup` targets in each package. This is needed for
`go_bazel_test`, since it explicitly depends files in repositories under test.
* Generated filegroups with the new extension.
> Fix go_repository configuration

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
- cmd/gazelle/version.go
- internal/go_repository.bzl
- language/go/config.go
- language/go/generate.go
- language/go/package.go
- language/go/resolve.go
- language/go/resolve_test.go
- repo/remote.go
* The Go extension now accepts flags -go_repository_mode and
-go_repository_module_mode.
* The Go extension will emit importpath_aliases attributes for
libraries with importpath set if -go_repository_mode was set,
Gazelle is in module mode, the prefix is actually a prefix of
importpath, the prefix contains a semantic import
version suffix, and the prefix was set in the root package.
Such a library can be imported with more than one import path.
* The minimum version of rules_go is now 0.19.0, since support for
importpath_aliases is needed.
* When initializing RemoteCache, which is used to resolve external
import paths, if we have a known import path that contains a
semantic import version suffix, but we don't have a known import
path for the path without the suffix, we create an aliases. …
> language/go: implement minimal module compatibility

- internal/go_repository.bzl
When urls attribute is set, go_repository rule currently throws this error:
```
ERROR: local variable 'generate' is referenced before assignment.
```
This change moves the definition of generate to just before its first use.
> Fix go_repository rule when using urls

- WORKSPACE
- deps.bzl
Also add explicit dependency on org_golang_x_sys, since
go_rules_dependencies no longer provides it.
> Update to rules_go 0.19.0

- internal/go_repository_tools.bzl
- repo/remote.go
- repo/remote_test.go
- repo/stubs_test.go
'gazelle update-repos <modpath>' will now add or update go_repository
rules in module mode. If a rule is not already in module mode, it will
be changed to module mode.
Fixes #505
> update-repos: add or update repositories in module mode

- .bazelci/presubmit.yml
https://github.com/bazelbuild/continuous-integration/issues/759
This will allow you to use the Bazel CI instead of (or in addition to) TravisCI
> Create Bazel CI configuration file

- cmd/fetch_repo/module.go
Without this change, most repos while fetching will print messages like
this on stderr:
.../go_repository.bzl:127:13: fetch_repo: go: finding google.golang.org/api v0.1.0
> Suppress stderr from fetchrepo if successful

- internal/go_repository.bzl
When there is an incompatible attribute to `version`,  `go_repository` prints:
> ERROR: attribute remote: cannot specify both version and %s
This diff fixes that
> fixed an error message

- repo/repo.go
I found these to be missing; I don't know if this is intentional.
Please feel free to reject this PR.
> Read module attributes from macro for remote cache

- internal/go_repository.bzl
- internal/go_repository_test.go
- repository.rst
As discussed in #598, this PR make `go_repository` take a list of Gazelle directives to be written to the root level build file.
This PR supercedes #597 and #598
> go_repository takes Gazelle directives

- README.rst
- cmd/gazelle/BUILD.bazel
- cmd/gazelle/fix_test.go
- cmd/gazelle/integration_test.go
- repo/remote.go
make `bazel run //:gazelle update-repos` can support version select as follow:
```
bazel run //:gazelle update-repos github.com/sirupsen/logrus@v1.4.0
bazel run //:gazelle update-repos github.com/sirupsen/logrus@dae0fa8
```
> repo: add version/commit select for update-repos

- README.rst
To redefine `gotags`, the `define` flag should be used, not the `features`.
> Fix update-repos -build_tags documentation [ci skip]

- cmd/gazelle/integration_test.go
- language/go/fileinfo.go
- language/go/testdata/cgolib_with_build_tags/BUILD.want
- language/go/testdata/gen_and_exclude/BUILD.want
- language/go/testdata/platforms/BUILD.want
- rule/platform.go
Anything that matches `darwin` should match `ios`, but not the other way
around. Same for `android` & `linux`.
Introduce aliases and extend the matching to them.
I haven't tested it in situ but the build files look good. Also, not sure about the `android -> linux` alias.
> Add ios platform and OS aliases

- WORKSPACE
- internal/gazelle_binary.bzl
Necessary to make the go1.13 linker happy.
Corresponding change in go_binary: bazelbuild/rules_go#2135
Also: upgrade to rules_go 0.19.3
> gazelle_binary: set package name to 'main' in GoLibrary

- cmd/autogazelle/autogazelle.bash
When calling `bazel` without parameters, the script was giving an error `$1: unbound variable`.
This fixes it by using an explicit default value of an empty string.
> autogazelle: use default syntax for expanding $1

- cmd/generate_repo_config/generate_repo_config.go
- rule/platform.go
- rule/platform_strings.go
- rule/value.go
This allows types to define custom translation to Starlark
syntax. PlatformStrings implements this interface and uses it to emit
a select expression with Go-specific conditions.
SelectStringListValue is a new type that satisfies BzlExprValue and
translates map[string][]string to a generic select expression.
ExprFromValue now translates maps with string keys (not satisfying
BzlExprValue) as dictionaries.
rule.PlatformStrings and Platform are now deprecated and will be moved
to language/go eventually.
Also: deflake //cmd/generate_repo_config:generate_repo_config_test.
Map iteration order could break it.
Fixes #511
> rule: add BzlExprValue interface and make PlatformStrings use it

- language/go/resolve.go
Other Gazelle extensions may need to resolve Go packages into Bazel labels too. For example, if an extension wants to generate `gomock` rule, the `library` parameter needs to be resolved.
This PR make `golang.resolveGo` public so it can be reused by other extensions.
> Making resolveGo public

- language/go/generate.go
- language/go/generate_test.go
Some generated files may have been consumed by other rules, either handwritten or generated by other extensions. The `go` extension should not add them into the `go_default_library` rule in such case.
> Excluding consumed generated files from go_library

- cmd/gazelle/integration_test.go
- language/go/config.go
- language/go/generate.go
- pathtools/path.go
This change supercedes #637, which was reverted.
In #647, Gazelle now reads the repository configuration file (set with
-repo_config; WORKSPACE by default) and adds repository rules to the
Repos list, which all languages may access.
When language/go is configured, it reads Repos and makes a list of
submodules by looking for go_repository rules with importpaths that
have the current module path as a prefix. This is simpler than the
previous approach, which required explicitly adding build_submodule
attributes to go_repository.
When Go libraries and binaries are generated in internal directories,
the submodule list is used to add additional visibility entries.
Fixes #619.
> language/go: simpler submodule visibility

- language/go/resolve.go
Export `IsStandard(imp string) bool` so other Gazelle extensions can reuse that
> Export IsStandard

- internal/go_repository.bzl
This passes through the environment variables `SSL_CERT_FILE` and `SSL_CERT_DIR`, which the Go standard library [will use](https://golang.org/pkg/crypto/x509/) to override the system default locations for SSL root certificates.
This is helpful in cases where either (a) the files aren't at the expected location, or (b) you want to fetch from a server that's using TLS with a non-public root certificate.
> Propagate standard SSL certificate environment variables

- cmd/gazelle/integration_test.go
- cmd/gazelle/update-repos.go
When a `go.mod` file has:
```
require (
github.com/Selvatico/go-mocket v1.0.7
github.com/selvatico/go-mocket v1.0.7
)
```
`gazelle update-repos` would generate two `go_repository` rules with the same name, causing indeterminism in the order of resulting `go_repository` rules. In most cases, users should not import both `github.com/Selvatico/go-mocket` and `github.com/selvatico/go-mocket` in the same module, so `gazelle update-repos` should report errors. However, if that's what users really want, they should to add a `replace` statement in the `go.mod` file like this:
```
require (
github.com/Selvatico/go-mocket v1.0.7
github.com/selvatico/go-mocket v0.0.0-00010101000000-000000000000
)
replace github.com/selvatico/go-mocket => github.com/Selvatico/go-mocket v1.0.7
```
In this case, only …
> Prevent Gazelle from generating duplicate repository rules

- language/go/def.bzl
- language/go/gen_std_package_list/BUILD.bazel
This is a workaround for a visibility issue, possibly introduced by
the --incompatible_remap_main_repo flag or something similar.
We should stop using go_rule though.
Fixes #676
Updates bazelbuild/rules_go#2302
> language/go: workaround Bazel compatibility issue

- cmd/gazelle/integration_test.go
- language/go/testdata/default_visibility/BUILD.want
- language/go/testdata/importmap/BUILD.want
- language/go/testdata/proto_package_mode/BUILD.want
- language/go/testdata/proto_package_mode_extras/BUILD.want
- language/go/testdata/protos/BUILD.want
- language/go/testdata/protos_explicit_default/BUILD.want
- language/go/testdata/protos_gogo/BUILD.want
- language/go/testdata/protos_gogo_subdir_reset/BUILD.want
- language/go/testdata/protos_gogo_subdir_reset/sub/BUILD.want
- language/go/testdata/service/BUILD.want
- language/go/testdata/service_gogo/BUILD.want
- language/go/testdata/service_gogo_subdir_reset/BUILD.want
- language/go/testdata/service_gogo_subdir_reset/sub/BUILD.want
- language/proto/kinds.go
- language/proto/testdata/default_visibility/BUILD.want
- language/proto/testdata/import_prefix/BUILD.want
- language/proto/testdata/multiple_packages/default_mode/BUILD.want
- language/proto/testdata/multiple_packages/package_mode/BUILD.want
- language/proto/testdata/multiple_packages/package_mode_group/BUILD.want
- language/proto/testdata/protos/BUILD.want
- language/proto/testdata/strip_import_prefix/BUILD.want
The native Protobuf rules are deprecated and will be replaced by
Starlark rules. As a first step towards this goal, starting with
Bazel 3.0, these rules will require explicit load statements.
See https://github.com/bazelbuild/bazel/issues/8922
This PR teaches gazelle to emit load statements for `proto_library`,
so Go projects can migrate using familiar tools.
Fixes #638
> Teach gazelle to add load statements for `proto_library`

- label/label.go
- label/label_test.go
Currently ImportPathToBazelRepoName converts `-`s and `.`s to `_`s. This does
not appear to be required by Bazel's repo name conventions, but may
follow best practices. Unfortunately, this means characters valid for
import paths cause build failures, like `git.sr.ht/~sircmpwn/go-example`.
This change replaces all non-word, `\W` or `[^A-Za-z0-9_]` characters, not
just `-` and `.`, with `_`.
This change also preallocates reversed, since its length is known.
> label: trim non-word chars for import path to repo

- language/go/update.go
> language/go: sort imported go_repository rules before returning

- cmd/gazelle/BUILD.bazel
- cmd/gazelle/integration_test.go
- cmd/gazelle/update-repos.go
In update-repos, if the -to_macro flag is used on a macro that isn't
mentioned in a '# gazelle:repository_macro' directive in WORKSPACE,
add a directive.
Gazelle needs to be able to read repositories from WORKSPACE for
accurate and efficient dependency resolution. Macros must be declared
with '# gazelle:repository_macro'. It's a common mistake to use
'-to_macro', then call the macro without declaring it. This change
removes that sharp edge by adding a call with a directive
automatically. If a call is already present without a directive, a
directive will be added, but if a directive is present without a
call, it will be left alone.
Updates #689
Fixes #680
Updates #665
> update-repos: add repository macro call and directive if missing

- cmd/gazelle/fix-update.go
Normally, Gazelle detects the repository name by reading the WORKSPACE
file and looking for a workspace rule. In go_googleapis, the proper
workspace name is com_google_googleapis. Before
bazelbuild/rules_go#2355, we patched the WORKSPACE file before running
Gazelle so the repository name would be set to
go_googleapis. Unfortunately, in newer versions of Bazel, WORKSPACE is
overwritten, so the patch doesn't apply.
This change just adds a hack to set the repository name to
go_googleapis if com_google_googleapis is detected.
Updates bazelbuild/rules_go#2387
> cmd/gazelle: hack to fix repository name hfor @go_googleapis

- language/proto/generate.go
- language/proto/generate_test.go
- language/proto/testdata/generated/BUILD.old
- language/proto/testdata/generated/BUILD.want
When a package only has generated proto files but no regular proto files, Gazelle should still generate `proto_library` for the generated proto files.
> proto_library for generated proto files

- cmd/gazelle/integration_test.go
- language/proto/kinds.go
- merger/merger.go
- merger/merger_test.go
When #730 was opened, it was based on top of #720. So the tests were passing on #730. However, #720 was reverted on master before #730 was merged. When merging #730 onto master, its tests started to fail. This PR reverted #743 and fixed the failing tests
Fixed #742
> Fixing failing tests

- cmd/gazelle/integration_test.go
- language/go/kinds.go
- language/go/update.go
Bug fix
language/go
It fixes `update-repos -build_tags`. It fixes #711 which caused the tags not to be emitted correctly when generating `go_repository` rules, and also drive-by fixes the `build_tags` attribute of said rules to merge correctly (ie. across subsequent `update-repos` calls).
Fixes #711
> update-repos: fix build_tags emitting

- README.rst
- deps.bzl
- go.mod
- go.sum
- vendor/github.com/bmatcuk/doublestar/.gitignore
- vendor/github.com/bmatcuk/doublestar/.travis.yml
- vendor/github.com/bmatcuk/doublestar/LICENSE
- vendor/github.com/bmatcuk/doublestar/README.md
- vendor/github.com/bmatcuk/doublestar/doublestar.go
- vendor/github.com/bmatcuk/doublestar/go.mod
- vendor/modules.txt
- walk/BUILD.bazel
- walk/config.go
- walk/config_test.go
- walk/walk_test.go
To make editors happy we generate the equivalent `.pb.go` for all `go_proto_library` targets, the `.gen.go` for all `go_embed_data` and then create a symbolic link to those files from Bazel's sandbox back to the source code. I'm pretty that's not the best approach, but it has worked for months. However, there's an issue with Gazelle where it tries to add these files to the target. It happens randomly as most of the time it ignores them, but I've noticed it happens mostly if the symlink got broken (bazel clean or other reason).
This pull request allows us to ignore files based on [path.Match](https://pkg.go.dev/path?tab=doc#Match) pattern relative location in the repository.
closes #750
> walk: convert gazelle:exclude to a doublestar.Match pattern

- language/proto/generate.go
- language/proto/generate_test.go
Bug fix
language/proto
Some generated files may have been consumed by other rules, either handwritten or generated by other extensions. The go extension should not add them into the proto_library rule in such case.
https://github.com/bazelbuild/bazel-gazelle/issues/731
> Excluding consumed generated files from proto_library

- cmd/gazelle/BUILD.bazel
- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
- cmd/gazelle/update-repos.go
- cmd/move_labels/BUILD.bazel
- cmd/move_labels/move_labels.go
- config/config.go
- internal/wspace/finder.go
- internal/wspace/finder_test.go
Bug fix
internal/wspace
Makes WORKSPACE root detection work with `WORKSPACE.bazel` filename
Fixes #764
> Update WORKSPACE finder to support "WORKSPACE.bazel" file name

- README.rst
- cmd/gazelle/fix-update.go
- cmd/gazelle/fix_test.go
- cmd/gazelle/gazelle.go
- cmd/gazelle/integration_test.go
- cmd/gazelle/update-repos.go
- config/config.go
- config/config_test.go
- testtools/files.go
This adds a `-lang` flag and `gazelle:lang` directive to restrict the languages
composed by Gazelle.
Fixes #687
> config: add configuration for selecting languages to process

- rule/rule.go
- rule/rule_test.go
My understanding of the "internal packages" behavior is that it should extend to
rules directly in the internal package, not just its subdirectories.
Add some tests to verify behavior.
> rule.CheckInternalVisibility: scope rules internally when composing internal/BUILD

- cmd/autogazelle/client_unix.go
- cmd/autogazelle/server_unix.go
- walk/BUILD.bazel
walk/config_test.go was not being run.
autogazelle was buildable on js,wasm for some reason.
> Update build files

- internal/go_repository_cache.bzl
- internal/go_repository_config.bzl
"cat" doesn't exist on Windows, and it seems
cleaner to use a built-in anyway.
Tested: Manually on Windows, and bazel test //...
The latter fails some tests, presumably because of
other Windows incompatibilities like autogazelle.
> Use repository_ctx.read() instead of "cat".

- language/go/BUILD.bazel
- language/proto/BUILD.bazel
- language/proto/gen/BUILD.bazel
- language/proto/gen/def.bzl
genrules are not supported on Windows without a dependency
on mingw. We replace them with a small custom bzl rule.
The new rule should be 1:1 compatible with what the genrule
was doing.
Bug fix is probably the closest I guess?
language/go
Replaces genrules with custom bzl rules, so we can work without msys on Windows.
> Remove use of genrules for computing known imports.

- def.bzl
- extend.rst
- internal/gazelle_binary.bzl
go_archive_aspect should no longer be used anywhere. It probably
should have been deleted before v0.21.0. gazelle_binary has been using
it for cross compilation though.
With this change, go_transition_rule is used for cross-compilation
instead.
Cross-compilation in gazelle_binary should be removed entirely in the
future though. It requires private functionality in rules_go, and it
doesn't seem useful.
For bazelbuild/rules_go#2523
Updates #803
> gazelle_binary: use transition instead of aspect

- README.rst
- language/go/resolve_test.go
- language/proto/BUILD.bazel
- language/proto/config.go
- language/proto/kinds.go
- language/proto/resolve.go
- language/proto/resolve_test.go
proto_library rules will now be indexed based on their import_prefix
and strip_import_prefix attributes, not the corresponding
directives. Generally, these will be consistent, but using the actual
attributes will let Gazelle correctly index hand-written targets and
targets with '# keep' directives.
The import_prefix and strip_import_prefix attributes are now
mergeable, so Gazelle may replace or delete existing attributes.
Fixes #805
> language/proto: adjust indexing for {strip_,}import_prefix attrs

- deps.bzl
- go.mod
- go.sum
- testtools/BUILD.bazel
- testtools/files.go
- vendor/github.com/google/go-cmp/LICENSE
- vendor/github.com/google/go-cmp/cmp/compare.go
- vendor/github.com/google/go-cmp/cmp/export_panic.go
- vendor/github.com/google/go-cmp/cmp/export_unsafe.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
- vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
- vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
- vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
- vendor/github.com/google/go-cmp/cmp/internal/function/func.go
- vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
- vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
- vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
- vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
- vendor/github.com/google/go-cmp/cmp/options.go
- vendor/github.com/google/go-cmp/cmp/path.go
- vendor/github.com/google/go-cmp/cmp/report.go
- vendor/github.com/google/go-cmp/cmp/report_compare.go
- vendor/github.com/google/go-cmp/cmp/report_reflect.go
- vendor/github.com/google/go-cmp/cmp/report_slices.go
- vendor/github.com/google/go-cmp/cmp/report_text.go
- vendor/github.com/google/go-cmp/cmp/report_value.go
- vendor/modules.txt
Instead of printing both files out and asking the user to visually diff,
perform the diff for the user and print it out.
>
Other
Usability improvement
* `testtools`
This adds a dependency on, and then uses the `go-cmp` which is released by Google. This package is widely used both inside and out of Google for comparison testing and has good performance characteristics (it won't allocate 500mb of ram just for fun).
None, this is simple enough that you should be able to accept/reject on the face of it. No problems if you want to reject, this just made building the `skylib` plugin …
> Use go-cmp to provide file differences

- cmd/fetch_repo/module.go
- internal/go_repository.bzl
Bug fix
cmd/fetch_repo
When `GO111MODULE=off` externally, fetch_repo fails with errors like:
```
ERROR: An error occurred during the fetch of repository 'com_github_bazelbuild_buildtools':
failed to fetch com_github_bazelbuild_buildtools: fetch_repo: unexpected end of JSON input
ERROR: Skipping '//:gazelle': no such package '@com_github_bazelbuild_buildtools//buildifier': failed to fetch com_github_bazelbuild_buildtools: fetch_repo: unexpected end of JSON input
```
Which give no information about the root cause. This PR print out more information from stderr of `go mod` command when there are errors and explicit turn on `GO111MODULE` before running `go mod` to …
> Setting GO111MODULE=on in fetch_repo

- cmd/gazelle/integration_test.go
- cmd/gazelle/update-repos.go
- rule/rule.go
- rule/rule_test.go
Developers working on the same repo may add external repos simultaneously. Appending new repos to the end often results in merge conflict. This PR sort repo rules by name to reduce the chance of conflict.
Note the it only sorts rules in macros by not in WORKSPACE, as the latter may have some repo rules that are better to keep at the top because of their importance, e.g., loading rules_go, gazelle, setting up go toolchain.
cc @blico
> Sorting repo rules in macros by name

- cmd/gazelle/diff.go
- cmd/gazelle/fix.go
- cmd/gazelle/fix_test.go
- rule/rule.go
Feature
Adds the `Content` field to `rule.File`, which contains the file's underlying disk content. `file.Content` is then used by `gazelle/fix` and `gazelle/diff` to avoid unnecessary file operations.
Fixes #807
> fix-update: only write changed build files to disk 

- language/go/generate.go
- language/go/testdata/filter_pbgo/BUILD.want
- language/go/testdata/filter_pbgo/a.pb.go
- language/go/testdata/filter_pbgo/a.proto
- language/go/testdata/filter_pbgo/a_grpc.pb.go
- language/go/testdata/filter_pbgo/b.pb.go
The new APIv2 proto compiler,
google.golang.org/protobuf/cmd/protoc-gen-go, does not generate gRPC
stubs in .pb.go files. Instead, a separate compiler,
google.golang.org/grpc/cmd/protoc-gen-go-grpc, will generate gRPC code
in _grpc.pb.go files.
With this change, Gazelle will exclude _grpc.pb.go files in addition
to .pb.go files when there's a matching .proto file in the same
directory. This should prevent conflicts between definitions in
generated .pb.go files and static _grpc.pb.go files.
The gRPC compiler is not part of a released version yet, but it's
already being used to generate code checked into gRPC 1.30.0. This
change should fix the build issue in #819, though I'm not entirely
sure it's safe to generate that code using protoc-gen-go from APIv1,
so I'll leave that issue open to …
> language/go: exclude _grpc.pb.go files matching .proto files

- cmd/gazelle/print.go
> Feature
> For example:
>
> language/go
Adds file name to -mode=print. This will permit a gazelle check mode that ignores CRLF line endings, which gazelle normally does not emit.
> Add file name to -mode=print

- BUILD.bazel
- WORKSPACE
- cmd/autogazelle/BUILD.bazel
- cmd/fetch_repo/BUILD.bazel
- cmd/gazelle/BUILD.bazel
- cmd/generate_repo_config/BUILD.bazel
- cmd/move_labels/BUILD.bazel
- config/BUILD.bazel
- deps.bzl
- flag/BUILD.bazel
- internal/BUILD.bazel
- internal/gazelle_binary.bzl
- internal/gazellebinarytest/BUILD.bazel
- internal/language/test_filegroup/BUILD.bazel
- internal/version/BUILD.bazel
- internal/wspace/BUILD.bazel
- label/BUILD.bazel
- language/BUILD.bazel
- language/go/BUILD.bazel
- language/go/gen_std_package_list/BUILD.bazel
- language/proto/BUILD.bazel
- language/proto/gen/BUILD.bazel
- merger/BUILD.bazel
- pathtools/BUILD.bazel
- repo/BUILD.bazel
- resolve/BUILD.bazel
- rule/BUILD.bazel
- testtools/BUILD.bazel
- walk/BUILD.bazel
* Set naming convention in main build file.
* Add gazelle:repository declarations in WORKSPACE for repos in gazelle_dependencies.
* Run 'gazelle fix'.
* Manual fixes for manually written targets.
> Migrate Gazelle to Go import_alias naming convention

- README.rst
- language/go/config.go
- language/go/resolve.go
- language/go/resolve_test.go
Allows the user to set the default Go naming convention used when
resolving imports of packages in external repositories with unknown
naming conventions.
For #5
> language/go: add go_naming_convention_extern flag and directive

- language/go/generate.go
- language/go/resolve.go
The target was generated for github.com/golang/protobuf/generator.
It should be github.com/golang/protobuf/protoc-gen-go/generator.
Fixes #872
> language/go: fix "extra" target for protoc-gen-go/generator

- README.rst
- cmd/gazelle/integration_test.go
- resolve/index.go
This disables processing of rules for languages which are disabled via the -lang
flag. Concretely, this halves the time it takes for Gazelle to update our Go
rules by skipping processing of all closure_js rules. 
That's partially because processing JS is sort of slow, but I think the basic idea here is sound. 
Updates #687
> cmd/gazelle: add resolvers for activated languages only

- language/go/config.go
- language/go/fix.go
- language/go/fix_test.go
- language/go/resolve.go
- language/go/resolve_test.go
* Rename goNamingConventionExtern to goNamingConventionExternal,
together with the flag and directive. No need to abbrev.
* Only migrate go_library if it matches the expected import path for
the directory. This avoids migrating the wrong target when there are
multiple go_libraries in the same directory.
* Only migrate go_test if it embeds the library.
* When fixing rules, don't add an embed attribute to go_test.
For #5
> language/go: fix remaining naming convention issues

- language/go/generate.go
- language/go/resolve.go
Hardcode logic for resolving go_tool_library dependencies, since it
can be done statically in most cases. Previously, the logic depended
on the naming convention, which breaks with import_alias.
For #872
> language/go: fix dependency resolution for go_tool_library

- cmd/gazelle/BUILD.bazel
- internal/gazelle_binary.bzl
This PR removes mode attributes (goos, goarch, race, etc.) from the
gazelle_binary rule. These attributes were implemented using private
files in rules_go, so supporting them is blocking changes in the
rules_go implementation.
These attributes should probably never be used. gazelle_binary should
generally be built for the host configuration (by 'bazel run' or
'bazel build' without configuration flags). If a binary is still
needed in a different configuration, that may still be accomplished
with command-line flags like --platforms or
--@io_bazel_rules_go//go/config:race.
Fixes #803
> gazelle_binary: remove mode attributes

- README.rst
> doc: fix flag and directive names for go_naming_convention_external [skip ci]

- README.rst
> doc: fix go_naming_convention default [skip ci]

- cmd/gazelle/integration_test.go
- language/go/fileinfo.go
- language/go/generate.go
- language/go/package.go
- language/go/testdata/platforms/BUILD.want
- language/go/testdata/platforms/generic_test.go
- language/go/testdata/platforms/suffix_linux_test.go
Other
language/go
`go_test` may [recompile](https://github.com/bazelbuild/rules_go/blob/c69d159acddfeb3a6849e105ec7a57542cac8987/go/private/rules/test.bzl#L245) external test archive where there embedded libraries. For packages with only external tests, this is not necessary and may slow down the build. This PR parse the test files to see if there are any internal tests. If not, the generated `go_test` will not embed `go_default_library`.
> Avoid embedding go_library when there is no internal test

- cmd/gazelle/integration_test.go
- cmd/generate_repo_config/generate_repo_config.go
- internal/go_repository.bzl
- language/go/config.go
- language/go/fileinfo.go
- repo/repo.go
We prefer to read RULES_GO_VERSION from @io_bazel_rules_go//go:def.bzl,
but that won't be available if the bazel-out symlink hasn't been
created yet.
As a fallback, look for the io_bazel_rules_go declaration in
WORKSPACE, and try to extract the version from the URLS.
Fixes #780
> language/go: infer rules_go version from WORKSPACE

- internal/gazelle_binary.bzl
Before rules_go v0.23.0, rules were required to have an _stdlib
attribute, which was usually provided via the go_rules wrapper. Now,
that dependency comes from _go_context_data. Adding an extra edge
keeps us compatible with older versions.
Fixes #896
> gazelle_binary: add extra _stdlib attr for older rules_go versions

- .bazelci/presubmit.yml
- cmd/gazelle/fix-update.go
- cmd/gazelle/fix_test.go
- cmd/gazelle/gazelle.go
- cmd/gazelle/integration_test.go
- cmd/gazelle/update-repos.go
- config/config.go
- def.bzl
- internal/BUILD.bazel
- internal/gazelle.bash.in
- internal/go_repository_test.go
- internal/runner_test.go
- language/go/modules.go
This reverts commit 024ada3b0a179ea03ddb8b8b979b4f27194e0834,
rolling forward PR #830, reverted in #844.
The runner script no longer changes directories before invoking
Gazelle. It also no longer supports being invoked without Bazel (to my
knowledge, no one does that).
Instead, Gazelle uses BUILD_WORKSPACE_DIRECTORY (if set) to resolve
relative paths on the command line. The effective working directory is
saved in config.Config, so extensions may access it. That should be
used instead of os.Getwd.
This is needed so that extensions may look up runfiles.
Fixes #827
> gazelle rule: simplify runner script

- repository.rst
build_naming_convention was misaligned.
> doc: fix alignment in go_repository attr table [skip ci]

- cmd/gazelle/integration_test.go
- language/go/modules.go
Bug fix
> language/go
gazelle update-repos
Allow update-repos to operate in-place rather than through a temp copy.  Previously, any go.mod files containing relative on-disk replace directives would completely break update-repos, since the temp copy's relative paths would all be broken.
Fixes #650
> update-repos can work with a go.mod file in place

- README.rst
This is from feedback from [this comment](https://github.com/bazelbuild/bazel-gazelle/issues/924#issuecomment-702357953)
Documentation
`README`
Fixes #
> Add a few clarifications to the README

- cmd/gazelle/diff.go
- cmd/gazelle/diff_test.go
Bug fix
cmd/gazelle
`-mode=diff` doesn't handle the generation of empty files the same way as `-mode=fix` does.
Fix won't actually print out empty files, but diff says the empty file should contain a single newline (due to how `difflib.SplitLines` handles the empty string).
#925
The test I added actually passes without this change, so it's not actually helpful. I'd love assistance turning it into something which requires this change to pass, and would fail otherwise.
> diff: make a non-existing file match an empty generation

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
- walk/walk.go
- walk/walk_test.go
Introduces `walk.UpdateSubdirsMode` set by `fix-update` when `--index=false` and `--r=true`. 
In this mode, Gazelle only visits and updates the directories given to it and their subdirectories.
Before, with this configuration Gazelle would visit all of the directories in the repository which is
unnecessary because `--index=false`.
Fixes #945
> walk: UpdateSubdirsMode

- cmd/gazelle/integration_test.go
- cmd/gazelle/metaresolver.go
- resolve/index.go
Previously, rules with a mapped kind added to the RuleIndex would not
be importable.
The MetaResolver records mapped kinds generated by recorded associated
with the package. When looking up an import, we do not have the
associated package. This change addresses that by storing the language
name on the ruleRecord itself, obviating the need to look up the
Resolver.
The additional test for this scenario fails prior to this change and
succeeds as a result of it.
Fixes #943
> support dependencies on mapped kinds

- README.rst
- deps.bzl
- internal/go_repository_cache.bzl
- internal/go_repository_test.go
* add parameter `go_env` to rule `gazelle_dependencies`
* add documentation describing new parameter `go_env` in README.rst
* add unit test for inclusion of values in `external/bazel_gazelle_go_repository_cache/go.env`
Feature
go_repository
Fixes #966 
Open questions:
1. Use a blacklist for GOROOT / GOPATH / GOCACHE or use same whitelist as in go_repository.bzl? ( see line 68 in internal/go_repository_cache.bzl )
2. How to test black/whitelist which will need different WORKSPACE for each test?
> gazelle_dependencies: add support to set project specific go env variables

- def.bzl
This enables callers to pass labels of generated files to Gazelle.
Fixes #867
> gazelle rule: add data attribute

- language/proto/config.go
- language/proto/config_test.go
Bug fix
language/proto
In `go_repository` rules, all Gazelle directives are at the root level BUILD.bazel. We should allow setting `proto_strip_import_prefix` at the root BUILD.bazel without warnings
> Allow setting proto_strip_import_prefix from root BUILD.bazel

- cmd/gazelle/integration_test.go
- language/go/modules.go
Starting in Go 1.16, 'go mod download' adds missing sums to go.sum.
We don't want that in update-repos though. 'go mod download' should be
run in a temporary directory with the same arguments.
Fixes #990
> language/go: don't let 'go mod download' edit go.sum

- label/label.go
- label/label_test.go
> Bug fix
This fix changes the variable `labelRepoRegexp` to properly parse labels starting with `@//`, which exist to reference the main repository. This is legal via [bazel_specs](https://docs.bazel.build/versions/master/build-ref.html#labels) for referencing the main repository from an external reference.
Fixes #1001
Test file also updated to reflect properly parsed labels
> Label fix: properly parse external references to the main repository

- language/go/modules.go
Bug fix
cmd/gazelle
Starting from version 1.16, go list doesn't list all modules if sum is missing. The -e flag is required to get back the old behavior.
Fixes #1018
> gazelle: add -e flag for go list 1.16

- def.bzl
Bug fix
wrapper script
#911 previously attempted to fix #827, but did not actually do so.
In particular, the runfiles for the gazelle_bin were correctly collecting transitive runfiles for the language plugins, but the runfiles for the gazelle wrapper script were not correctly aggregating them
This small fix repairs that by merging the runfiles from the binary into the wrapper script.
Fixes #827
> Correctly propagate runfiles from gazelle_bin to gazelle

- language/go/embed.go
- language/go/testdata/embedsrcs/BUILD.want
- language/go/testdata/embedsrcs/embedsrcs.go
When embedResolver is created, we now gather all embeddable files and
directories into a tree instead of a list.
When embedResolver.resolve matches a pattern, it visits every node in
the tree. This ensures we can recursively embed all files in a
directory except hidden files.
Fixes #1013
> language/go: rewrite embedResolver to use a tree structure

- walk/BUILD.bazel
- walk/walk_test.go
> Test improvement
> cmd/gazelle
cmp.Diff outputs a much nicer error message when comparing lists. Example:
```
--- FAIL: TestExcludeSelf (0.00s)
walk_test.go:278: Walk relative paths (-want +got):
[]string{
-       "b/d",
-       "b",
-       "e",
"",
}
```
I found this helpful when debugging walk_test.
> walk_test: switch reflect.DeepEqual to cmp.Diff

- merger/merger_test.go
- rule/merge.go
Bug fix
all
I have an optional list argument that may or may not exist on a rule, in the current configuration, `mergeExprs` can return nil if it encounters an empty destination list, which panics when passed to `SetAttr`.
I think a simple fix for this is to `DelAttr` on values that return `nil` (with no errors) in `mergeExprs`.
Didn't make an issue for this.
> Change merge behavior to remove attrs instead of panicking

- README.rst
Documentation
It updates the description of the `go_prefix` flag, since the [go_prefix rule no longer exists](https://github.com/bazelbuild/rules_go/issues/721).  Hopefully my understanding is correct.
> Updated documentation of go_prefix flag

- README.rst
Documentation
It includes a reference to the Gazelle directive documentation in `proto_import_prefix` flag description, because there is more explanation of `proto_import_prefix` in the directives section.
> Include reference to proto_import_prefix Gazelle directive

- README.rst
- repository.rst
Documentation
It includes a reference to the Gazelle directive documentation in the `build_naming_convention` attribute of the `go_repository` rule and the `go_naming_convention` flag description, because there is more explanation of `go_naming_convention` in the directives section.
> Include links to go_naming_convention directive

- cmd/gazelle/update-repos.go
fixes #1065
Skip saving files if file content did not change.
This will improve the speed of analysis phase after invoking gazelle.
> do not update files if content did not change

- walk/config.go
- walk/walk_test.go
Bug fix
walk
https://github.com/bazelbuild/bazel-gazelle/commit/d1bb5647f653ae920ae368d12adc6eab0500005a Introduced breaking changes that prevent gazelle updates for existing repositories, due to issues with how .bazelignore is parsed (see https://github.com/bazelbuild/bazel-gazelle/issues/1070). Additionally, this feature should not be enabled by default, as it reduces performance.
Fixes #1070
Fixes #1026
This feature should be implemented in a way that is backwards compatible before being merged to master.
> Revert "Respect .bazelignore (#1022)" 

- internal/go_repository_cache.bzl
Feature
go_repository
`GOMODCACHE` was added in Go 1.15. Let's read it when `GO_REPOSITORY_USE_HOST_CACHE==1`.
> Honor host GOMODCACHE when GO_REPOSITORY_USE_HOST_CACHE

- language/go/generate.go
This package was recently added as a dependency of astutil in order to
handle generics. With this change, Gazelle will generate a
go_tool_library target for this package.
> language/go: add golang.org/x/tools/internal/typeparams to nogo deps list

- rule/BUILD.bazel
- rule/rule_test.go
- rule/value.go
- rule/value_test.go
Bug fix
rule
It fixes the marshaling of GlobValue with non empty excludes.
```go
log.Printf("%s", bzl.FormatString(ExprFromValue(GlobValue{
Patterns: []string{"a", "b"},
Excludes: []string{"c", "d"},
})))
```
Invalid, see [Functions - Glob](https://docs.bazel.build/versions/main/be/functions.html#glob).
```
glob(
[
"a",
"b",
],
"excludes": [
"c",
"d",
],
)
```
```
glob(
[
"a",
"b",
],
exclude = [
"c",
"d",
],
)
```
I have not filed an issue.
---
f596991 Fix "exclude" token parsing
<br/>
3f0d09d test: Add e2e test
<br/>
> Fix "exclude" token parsing

- label/label.go
- label/label_test.go
Bug fix
label
Allows external references to the main repository (starting with "@//") to properly work in gazelle resolve statements:
`gazelle:resolve something @//some_path:to_something`. This scenario is legal in Bazel, and therefore is a bug that needs fixing/patches because it is not properly handled with Gazelle.
From [bazel specs](https://docs.bazel.build/versions/main/build-ref.html#labels):
> Labels starting with @// are references to the main repository, which will still work even from external repositories. Therefore @//a/b/c is different from //a/b/c when referenced from an external repository. The former refers back to the main repository, while …
> Have label properly resolve directives starting with "@//"

- extend.rst
Documentation
This PR adds a link to a new Gazelle extension, gazelle_cabal.
> extend: link to gazelle_cabal

- internal/go_repository.bzl
Feature
go_repository
The URLs that `go_repository` downloads libraries from may need authentication. We need to support the authentication tokens saved in `.netrc` similar to what `http_archive` does.
** Which issues(s) does this PR fix?
Fixes #847
** Other notes for review
This is a re-implementation of #848 by addressing @jayconrod's comments there. Besides fixes in the code, these are the responses to Jay's comments:
> Could you confirm that Bazel 1.2.0 provides these functions, and if not, what is the oldest version of Bazel that does? I'd like to make sure we're not breaking compatibility here. If these were added recently, it would be better to copy …
> Read .netrc in go_repository

- def.bzl
This is a followup to #1008 which fixed this problem for the
gazelle_binary but not for the data attribute of the gazelle rule.
Bug fix
cmd/gazelle
We are working on a python extension, where the gazelle binary will have a py_binary in its data deps.
Without this fix, the runfiles of that py_binary are absent at runtime and gazelle fails like
FileNotFoundError: [Errno 2] No such file or directory: '/home/alexeagle/.cache/bazel/_bazel_alexeagle/cdec52671ea8b1684766cfc23dcfc4be/execroot/rules_python/bazel-out/k8-fastbuild/bin/gazelle/g.runfiles/bazel_tools/tools/python/py3wrapper.sh'
> Correctly propagate runfiles from data dependencies to gazelle

- BUILD.bazel
- WORKSPACE
- deps.bzl
- internal/BUILD.bazel
- internal/common.bzl
- internal/go_repository.bzl
- internal/go_repository_cache.bzl
- internal/go_repository_config.bzl
- internal/go_repository_tools.bzl
- language/go/BUILD.bazel
- language/proto/gen/BUILD.bazel
> Other
> all
This adds `bzl_library` targets for Gazelle. This is useful in generating `skydoc`s.
> Add bzl_library targets to Gazelle

- language/go/generate.go
- language/go/testdata/cgolib/BUILD.want
- language/go/testdata/cgolib/foo.go
Bug fix
language/go
`gazelle` and `rules_go` are currently in conflict with the use of `$`-escaped variables in cgo flags. This PR should resolve the discrepancy.
Fixes #1106 
> Escape vars in cgo flags with an extra $

- cmd/autogazelle/BUILD.bazel
- cmd/autogazelle/client_unix.go
- cmd/autogazelle/server_unix.go
I don't know for sure why this was disabled, but the initial commit and
the change to golang to support AF_UNIX on windows were at roughly the
same time in 2018, so that might be the reason.
Other
cmd/autogazelle
This makes 'bazel test //...' work on windows. Currently it dies to a build error, which appears to be unnecessary.
> autogazelle can build on windows

- README.rst
> Document behaviour of extra_args with bazel run

- README.rst
Without specifying this argument, I got a cryptic error like:
```
INFO: Repository bazel_gazelle_go_repository_config instantiated at:
/path/to/repo/WORKSPACE.bazel:85:21: in <toplevel>
/path/to/bazel/cache/external/bazel_gazelle/deps.bzl:80:25: in gazelle_dependencies
Repository rule go_repository_config defined at:
/path/to/bazel/cache/external/bazel_gazelle/internal/go_repository_config.bzl:62:39: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_config':
Traceback (most recent call last):
File "/path/to/bazel/cache/external/bazel_gazelle/internal/go_repository_config.bzl", line 25, column 31, in _go_repository_config_impl
config_path = ctx.path(ctx.attr.config)
Error in path: Not a regular file: /path/to/repo/WORKSPACE
ERROR: …
```
> Add note about WORKSPACE.bazel

- label/label.go
- label/label_test.go
Bug fix
cmd/gazelle
This PR has label.Parse accept repo names with dashes and dots. `gazelle` needs it to process bazel repositories that use these characters in repository names.
Fixes #1082
> Allow dots and dashes at repo names in labels

- README.rst
Updates #1115
Previously, users were implicitly encouraged to place their dependencies AFTER the rules_go / gazelle dependencies have been declared, which causes any new dependencies that we add to take precedence. 
This is undesirable. Recommend that everyone put their dependencies first.
> README: recommend putting dependencies prior to rules_go/gazelle deps

- language/go/modules.go
- language/go/update_import_test.go
Bug fix
language/go
Report error details from `go mod download`
Currently if there are errors from `go mod download`, e.g. if a URL
couldn't be resolved or connected to, the output is swallowed because we
ignore the JSON which describes the error.
This change attempts to best-effort parse the output JSON to find error
description strings, and attach them to the error we report to users.
> Report error details from `go mod download`

- Design.rst
- README.rst
Documentation
cmd/gazelle
Revises doc language for installing cmd/gazelle via Go tooling as `go install pkg@version` has replaced now-deprecated `go get ...` when building and installing executables in module mode.
> Update to install@latest command for builds via Go tooling (cmd/gazelle)

- language/proto/generate.go
- language/proto/generate_test.go
- language/proto/resolve_test.go
- language/proto/testdata/file_mode/bar.proto
- language/proto/testdata/file_mode/foo.proto
Bug fix
language/proto
With the recently-added per-file mode for the proto generator, imports of `.proto` files within the same package don't generate dependencies.
Fixes #1157
> language/proto: don't skip same-package imports in per-file mode

- merger/BUILD.bazel
- merger/fix.go
- merger/fix_test.go
Feature
`merger`
Some language implementations may try to add helper functions as
`CallExpr`s, e.g. in rules_python the `requirement` function, or in
rules_jvm_external the `artifact` function. This allows for parsing
these out and adding `load` statements for them.
See also: #981, #978, #1087 (but does not fully fix them).
This approach was suggested in [this comment](https://github.com/bazelbuild/bazel-gazelle/issues/978#issuecomment-755431161).
> FixLoad loads helper functions, not just rules

- internal/go_repository.bzl
Otherwise Bazel presents this time as spent 'fetching' which is not accurate, the user isn't waiting on network at this point.
Include a link to an issue about how to remediate this Gazelle generation being too slow.
See #1190
> Add a progress reporting before running gazelle

- internal/generationtest/generation_test.go
Bug fix
testtools
On https://github.com/bazelbuild/bazel-gazelle/pull/1195, I discovered that `generation_test` does not work on windows.
Fixes https://github.com/bazelbuild/bazel-gazelle/issues/1199
> fix(tests): use filepath instead of path to handle Windows.

- .bazelci/presubmit.yml
- BUILD.bazel
- internal/BUILD.bazel
- walk/BUILD.bazel
#1202 highlights the value in verifying the repo's BUILD.bazel files are up-to-date during CI.
> ci: Add gazelle check

- cmd/gazelle/integration_test.go
- resolve/index.go
A Resolver can be overriden, this is the case by example for all rules
from the map_kind operation.
This layer must be transparent while comparing two resolvers.
Bug fix
resolve
These modifications provide an abstraction of the inverseMapKindResolver to compare two Resolver objects.
Fixes #1162
Thank you @blico for the test <3.
> resolve: improve matching of two resolvers (#1162)

- internal/go_repository.bzl
Currently, if a `go_repository` rule is in HTTP mode and has `build_file_generation = on` it can result in unnecessary calls to `download_and_extract` while the `@bazel_gazelle_go_repository_tools` and `@bazel_gazelle_go_repository_cache` labels are still not available. Note that redundant fetches can be unavoidable when in HTTP mode and `build_file_generation = auto` because the rule needs to fetch and examine the repo to determine if it requires `@bazel_gazelle_go_repository_tools`.
For more info about repository rule restarting see:
https://docs.bazel.build/versions/5.0.0/skylark/repository_rules.html#when-is-the-implementation-function-executed 
Resolve #1175
> go_repository: avoid unnecessary fetches in HTTP mode

- language/go/generate.go
- language/go/lang.go
- language/go/testdata/embedsrcs/m_dir/o_go/o.go
Bug fix
language/go
Fixes a bug where Gazelle was failing to embed files of a subdir, if it contained buildable subdirs.
For example, Gazelle would not find `bar.txt` for `//go:embed foo/bar.txt` if `foo` also contained a package `baz` which had go files.
`goPkgRels` is currently being used to determine if a directory is embeddable and if a `testdata` directory can be added as a `data` attribute. These two cases are the same unless a subdir contains buildable subdirs, in which the directory should still be embeddable but if it is `testdata` it should not be added as a `data` attribute.
The fix is to ensure `goPkgRels` correctly reflects whether a dir is a go …
> language/go: support embedding subdirs containing buildable subdirs

- internal/generationtest/generationtest.bzl
Without using `Label()` it is always relative to the workspace the macro is used instead of where the macro defined within bazel-gazelle.
> fix(tests): fix gazelle_generation_test usage outside gazelle repo

- README.rst
- WORKSPACE
In preparation for minor release
> Update to Go 1.18 and rules_go v0.31.0 in WORKSPACE and README.rst

- testtools/files.go
Today fixing the `expectedStderr.txt` inserts the stdout instead of stderr...
> fix(tests): fix gazelle_generation_test expected stderr update

- extend.md
- internal/extend_docs.bzl
Documentation
N/A
I want to add a practical example of using multiple languages in gazelle_binary. This was a pain point for me when first trying to use gazelle for both go and python so hopefully this is a good addition to provide a foundation for others to use.
N//A
> Update extend.md with a practical languages example

- WORKSPACE
- internal/BUILD.bazel
- internal/gazelle_binary.bzl
- internal/gazelle_binary_test.bzl
Bug fix
internal/gazelle_binary
These changes make the import aliases for the generated Go code in gazelle_binary longer to avoid collisions.
Without theses changes, importing 2 gazelle extensions with the same base path would fail to build the gazelle binary:
```starlark
gazelle_binary(
name = "gazelle_bin",
languages = [
"@bazel_skylib//gazelle/bzl",
"@rules_python//gazelle:gazelle_python_binary",
],
)
```
```console
$ bazel build //:gazelle_bin
[...  snip]
bazel-out/darwin-fastbuild/bin/gazelle_bin_/langs.go:10:2: gazelle_ redeclared in this block
bazel-out/darwin-fastbuild/bin/gazelle_bin_/langs.go:9:2: other declaration of gazelle_ …
```
> fix: Remove gazelle_binary import collision

- label/label.go
- label/label_test.go
Bug fix
label
Broadens the accepted names in labels.
These are documented at https://docs.bazel.build/versions/main/build-ref.html#name
> Broaden label name regex

- testtools/files.go
gazelle_generation_test uses the golden output to check the gazelle run results.
However, gazelle may occasionally output the full workspace path in logs, which
makes the test unreproducible, thus impossible to generate a golden output.
This CL replaces the workspace path in the output with a constant token, to make
the tests reproducible.
(Actually, this won't work on windows, as the output path will be with backward
slashes and the golden files are with forward slashes. But I'll leave it as it
is for the sake of testing.)
> gazelle_generation_test: redact workspace path from output

- language/go/testdata/proto_package_mode/BUILD.want
- language/go/testdata/proto_package_mode_extras/BUILD.want
- language/proto/generate.go
- language/proto/generate_test.go
- language/proto/testdata/default_visibility/BUILD.want
- language/proto/testdata/file_mode/BUILD.want
- language/proto/testdata/import_prefix/BUILD.want
- language/proto/testdata/multiple_packages/default_mode/BUILD.want
- language/proto/testdata/multiple_packages/package_mode/BUILD.want
- language/proto/testdata/multiple_packages/package_mode_group/BUILD.want
- language/proto/testdata/multiple_packages/package_mode_group/bar1.proto
- language/proto/testdata/multiple_packages/package_mode_group/bar2.proto
- language/proto/testdata/multiple_packages/package_mode_group/foo1.proto
- language/proto/testdata/multiple_packages/package_mode_group/foo2.proto
- language/proto/testdata/protos/BUILD.want
- language/proto/testdata/strip_import_prefix/BUILD.want
Bug fix
language/proto
Fixes an issue where dependencies would be missed in the case where an
import was of a proto file in the same directory but from a different
target, such an when using `proto_group`. This would cause Gazelle to
generate `proto_library` and `go_proto_library` targets that could not
be built.
Fixes #1219
> fix(lang/proto): include imports from different targets

- language/go/modules.go
- language/go/update_import_test.go
Bug fix
language/go
Handle wrapped errors
`go mod download` returns a different error structure than `go list`, as
documented at https://go.dev/ref/mod#go-mod-download and https://go.dev/ref/mod#go-list-m
We were previously parsing these assuming they had the same structure,
instead, parse them separately.
Also, prevent infinite looping on invalid JSON.
> Handle wrapped errors

- language/go/BUILD.bazel
- language/go/config_test.go
- language/go/fileinfo_go_test.go
- language/go/fileinfo_test.go
Other
language/go
`reflect.DeepEqual` is a poorer chose when choosing to compare test results. For example, `DeepEqual` will only compare pointer values using their memory address, rather than the underlying value in the type.
This is a pre-factor to make #1243 easier to review (per review feedback)
Fixes #1099 
> Go: Update tests to use cmp.Diff instead of reflect.DeepEqual

- language/go/generate.go
Bug fix
language/go
After #1197, Gazelle prints out the following warning every time it visits a directory without any `gazelle:prefix`, even the directory has no Go files:
```
gazelle: could not infer import path: /foo/bar: go prefix is not set, so importpath can't be determined for rules. Set a prefix with a '# gazelle:prefix' comment or with -go_prefix on the command line
```
The root cause is Gazelle tries to generate package and infer import path even when there is no Go or proto package. The error to infer import path was ignored before #1197. However, we should not infer import path for empty package because it will be inferred later when there is Go …
> Stop inferring import path for empty packages

- label/label.go
- label/label_test.go
Bug fix
label
Don't exclude spaces from the label name regex
In parsing the output of `bazel query`, we found that some files with
spaces in their names are included in the output.
It seems reasonable that all labels that come out of a `bazel query`
should be parsable by this `Label` type; let's just use the raw regex
from the Bazel documentation.
> Don't exclude spaces from the label name regex

- language/go/update_import_test.go
- language/go/utils.go
Bug fix
language/go
Previously, such errors would lead to the following error message:
```
gazelle: json: cannot unmarshal object into Go struct field moduleFromList.Error of type string
```
This is fixed by changing the definition of the `Error` field to be an
object with an Err field of type string, as described at:
https://go.dev/ref/mod#go-list-m
Follow-up to https://github.com/bazelbuild/bazel-gazelle/commit/56d35f8db086bb65ef876f96f7baa7b71516daf8
CC @illicitonion
> Unwrap `go list -m -json` errors correctly

- internal/go_repository_tools_srcs.bzl
- internal/language/test_filegroup/BUILD.bazel
- internal/language/test_filegroup/lang.go
- language/BUILD.bazel
- language/base.go
In order to help folks extend Gazelle quicker and easier, provide a base
implementation of the language.Language interface where everything is
no-ops.
End users then can simply compose their downstream struct with this
to have a valid implementation to iterate upon.
> language: add BaseLang

- rule/rule.go
- rule/rule_test.go
Feature
`rule`
Allow adding arguments to Rules
This allows supporting patterns like `maybe`, which take a
rule-to-instantiate as a positional argument.
> Allow adding arguments to Rules

- internal/bzlmod/go_mod.bzl
- internal/go_repository_config.bzl
- tests/bcr/.bazelversion
Necessary after https://github.com/bazelbuild/bazel/commit/7f9de9e6f8bd3ede758ec7f11ed76b63dab15384
> bzlmod: Fix canonical label literal after Bazel change

- MODULE.bazel
This is required to allow repositories generated for Go modules to see proto_library.
Work towards https://github.com/bazelbuild/rules_go/issues/3265
> bzlmod: Depend on rules_proto

- cmd/gazelle/fix-update.go
- internal/language/test_filegroup/BUILD.bazel
- internal/language/test_filegroup/lang.go
- language/base.go
- language/lang.go
Feature
`language`
This allows for an explicit notification that it's safe to release
resources needed only for generation (e.g. shutting down background
servers).
> Add DoneGeneratingRules language hook

- extend.md
- internal/generationtest/generation_test.go
- internal/generationtest/generationtest.bzl
- testtools/files.go
Feature
`internal/generationtest`
Allow configuring timeout of generation tests
I've seen a slow generator, when running with high `--runs_per_test` to detect flaky tests, need more than 2 seconds.
> Allow configuring timeout of generation tests

- def.bzl
Bug fix
`gazelle` rule
This PR allows user-specified tags on `gazelle` rule instances.
Currently if a user specifies their own tags on a `gazelle` rule
```starlark
gazelle(
name = "gazelle.go.update",
command = "fix",
prefix = "<REDACTED>",
tags = ["ci"],
)
```
this results in an error:
```text
 -> bazel run //:gazelle
ERROR: Traceback (most recent call last):
File "/Users/dvamstel/<REDACTED>/BUILD.bazel", line 86, column 8, in <toplevel>
gazelle(
File "/private/var/tmp/_bazel_dvamstel/1ae6969914f9a102dcd06aac0525d313/external/bazel_gazelle/def.bzl", line 139, column 20, in gazelle
_gazelle_runner(
Error in …
```
> bug: Allow user-specified tags on gazelle rule

- language/go/generate.go
- language/go/generate_test.go
Bug fix
language/go
Previously, the implementation of the language/go extension's GenerateRules method only considered args.File, and therefore missed scenarios where another extension (as recommended in the Issue) creates a package(default_visibility = ...)
Fixes #783
> language/go should consider default_visibility set by OtherGen (#783)

- MODULE.bazel
- internal/bzlmod/go_deps.bzl
- internal/bzlmod/go_mod.bzl
Feature
bzlmod
These changes are required to allow users of `rules_go` to use all the custom `go_proto_library` compilers defined in its `//proto` package **if they provide their own definitions of them**:
* Make `gazelle` and `protobuf` visible to `go_repository` targets under
their legacy `WORKSPACE` names.
* Expose `build_file_proto_mode` on `go_deps.module`.
> bzlmod: Add support for custom `go_proto_library` compilers

- .bcr/config.yml
- .bcr/metadata.template.json
- .bcr/presubmit.yml
- .bcr/source.template.json
- BUILD.bazel
This uses the https://github.com/bazel-contrib/publish-to-bcr app.
> bzlmod: Set up automated BCR releases

- testtools/files.go
Bug fix
Gazelle generation tests.
The golden file generation didn't respect the user-specified suffix for outfiles. It does now.
According to the guidelines, small bug fixes don't need issues.
> Make `gazelle_generation_test` respect out suffix when generating golden files

- extend.md
- internal/generationtest/generationtest.bzl
Other
`gazelle_generation_test`
This adds the `size` argument to the test. I currently have a very small test case for my custom plugins and want to set the size to small. I could imagine that people have a larger test they want to scale up so they can schedule appropriately.
> Add size argument to `gazelle_generation_test`

- .bazelci/presubmit.yml
- MODULE.bazel
- tests/bcr/.bazelversion
- tests/bcr/MODULE.bazel
Also pin Bazel in `.bazelversion`, which appears to override the `bazel_version` specified in the CI script.
> bzlmod: Update deps and Bazel pin

- language/bazel/visibility/lang.go
- language/bazel/visibility/lang_test.go
Bug fix
language/bazel
Without this change, the `default_visibility` directive will cause a BUILD.bazel file to be authored at every directory down the tree, as opposed to only those that have existing BUILD.bazel. This the notion of default visibility is only tied to rules contained within the same BUILD.bazel, this is unnecessary.
> Fix: Skip default_visibility extension logic if no BUILD.bazel file present

- .bcr/source.template.json
This field is required even if its value is empty.
> bzlmod: Add missing `strip_prefix` field to `source.template.json`

- extend.md
- internal/generationtest/generationtest.bzl
- tests/BUILD.bazel
Feature
all
It allows common test attributes to be set on `gazelle_generation_test`.
Fixes #1376.
With this fix, we could remove the explicit `size` argument in `gazelle_generation_test`. If the reviewers agree, I will go ahead and remove it.
> feat: support common test args in `gazelle_generation_test`

- language/go/generate.go
Feature
language/go
golang.org/x/tools recently moved its facts package from golang.org/x/tools/go/analysis/internal/facts to golang.org/x/tools/internal/facts. We should make both of them public so Gazelle can handle new and old versions of golang.org/x/tools
> Make the new facts pacakge public

- .bcr/metadata.template.json
Fixes https://github.com/bazelbuild/bazel-central-registry/pull/311#discussion_r1041304177 for gazelle
> bzlmod: Add missing repository metadata

- language/go/def.bzl
Become compatible with
`--incompatible_disable_starlark_host_transitions`, which will be flipped in Bazel 7.
https://github.com/bazelbuild/bazel/issues/17032
> Replace `cfg = "host"` with `cfg = "exec"`

- language/go/BUILD.bazel
- language/go/embed.go
- language/go/generate_test.go
Bug fix
language/go
First commit (slightly hacky) makes tests runnable on Windows resolving an ancient TODO.
Second commit fixes issue I filed.
Fixes #1360 
You can see for yourself that the current tests are indeed failing on Windows if you use only the first commit from my PR
> Fix embed on windows

- README.rst
Ecosia's repo is marked as archived, so I've removed the link to it. BenchSci's extension was originally a fork of Ecosia's extension.
Documentation
cmd/gazelle
Update link to nodejs suggestion from archived Ecosia repo to active BenchSci repo
> Add link to BenchSci's rules_nodejs_gazelle extension

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
- repo/BUILD.bazel
- repo/remote.go
- repo/remote_test.go
- vendor/golang.org/x/mod/modfile/print.go
- vendor/golang.org/x/mod/modfile/read.go
- vendor/golang.org/x/mod/modfile/rule.go
- vendor/golang.org/x/mod/modfile/work.go
- vendor/modules.txt
> Bug fix
> language/go
> repo
Opportunistically populates `RemoteCache` from `go.mod` if the Go extension is being used and a `go.mod` file is in the repository root. This doesn't override roots added from `WORKSPACE` (or other configuration file). It should allow static external dependency resolution to succeed more often in `go_repository` when other `go_repository` declarations are outside the main `WORKSPACE` file, for example, in another dependency's macro.
Fixes #1385
This unfortunately introduces more Go-specific code to `//cmd/gazelle`. I don't think there's a good way to do it without …
> repo: opportunistically populate RemoteCache from go.mod

- .bazelrc
- language/proto/BUILD.bazel
Allows rules_go to merge https://github.com/bazelbuild/rules_go/pull/3415.
> Fix Gazelle with `--incompatible_disallow_empty_glob`

- MODULE.bazel
In practice, now that Bazel 6.0.0 has shipped, Gazelle is working about as well as any other supported languages in the ecosystem. Also, if users find bugs with it, those are important and we'll fix them.
> chore: remove experimental warning from bzlmod module

- README.rst
An extra space causes indentation errors when one copy/pastes from the README setup instructions.
Also noticed a typo in one of the URLs for the bazel_gazelle http_archive.
Documentation
> For example:
>
> language/go
> cmd/gazelle
> all
Fixes #
> Fix indentation error in README setup instructions

- language/go/embed.go
- language/go/testdata/embedsrcs/BUILD.want
- language/go/testdata/embedsrcs/embedsrcs.go
- language/go/testdata/embedsrcs/o_dir/_hidden.txt
Feature
language/go
The original support for embedding was added at the time of go1.16.
`go1.18` added the support for `all:`  in https://github.com/golang/go/issues/43854 
This PR adds it here. 
Fixes #1431
> language/go: add //go:embed all:<pattern> support

- language/go/update_import_test.go
- language/go/utils.go
Bug fix
language/go
Fixes the expected format of a struct emitted by `go mod download`.
See https://go.dev/ref/mod#go-mod-download for the specification.
> Fix `go mod download` output expectation for errors

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
Bug fix
cmd/gazelle
Applies map_kind directives to existing rules as well as new ones.
See https://github.com/bazelbuild/bazel-gazelle/issues/1391 for discussion.
Fixes #1391
PR has two commits - the first is adding tests showing the existing behaviour, and the second is changing the behaviour and updating the tests.
> Apply map_kind to existing rules as well as new ones

- BUILD.bazel
- def.bzl
- internal/gazelle.bash.in
- tests/cli/BUILD.bazel
- tests/cli/env_variables_test.bzl
In certain cases it may be useful to have predefined values like GONOSUMDB or others passed into the gazelle helper, with this change the caller to helper can pass those values, and make them part of the code tree instead of a mess of environment variables in the command line.
For example this means someone can now add this to their BUILD.bazel and get a properly working gazelle setup against their ssh private repositories:
```
gazelle(
name = "gazelle",
env = {
"GONOSUMDB": "git.somecompany.com",
"GIT_CONFIG_COUNT": "1",
"GIT_CONFIG_KEY_0": "url.git@git.somecompany.com:.insteadof",
"GIT_CONFIG_VALUE_0": "https://git.somecompany.com",
},
)
```
Feature
cmd/gazelle
**What does this PR do? Why is it …
> feature: gazelle wrapper allows to pass environment variables

- README.rst
N/A
Adds `default_visibility` directive to the directive documentation, added in #783
> Update directive documentation

- language/bazel/visibility/config.go
- language/bazel/visibility/lang_test.go
Bug fix
language/bazel
Previously the logic of this extension accumulated default visibilities to the list across all configurations without any reset. As noted in the attached issue, this is unintuitive and did not add real value so long as multiple directives within the same file can still aggregate values.
Fixes #1467
> Default Visibility extension overwrite on descent (fixes #1467)

- README.rst
- rule/rule.go
- rule/rule_test.go
Feature
rule
Allow the # keep comment to take more text after them for the keep author to add a reference to a ticket or to explain the need for the keep.
> Allow keep to be explained

- internal/bzlmod/go_deps.bzl
- tests/bcr/MODULE.bazel
- tests/bcr/go.mod
We need to only call sums_from_go_mod if the corresponding go.mod file lists at least one dep. [See previous implementation](https://github.com/bazelbuild/bazel-gazelle/commit/97a754c6e45848828b27152fa64ca5dd3003d832#diff-3f46978d0add3c4448fb3dac679f46863ffaa5164f61f410f247179ebd80f6e5L15-L16)
Otherwise we get the following error:
```
File "/.../external/gazelle~override/internal/bzlmod/go_deps.bzl", line 183, column 51, in _go_deps_impl
for entry, new_sum in sums_from_go_mod(module_ctx, from_file_tag.go_mod).items():
File "/.../external/gazelle~override/internal/bzlmod/go_mod.bzl", line 204, column 34, in sums_from_go_mod
go_sum_path = module_ctx.path(go_sum_label)
Error in path: Not a regular file: /.../bazel-gazelle/tests/bcr/go.sum
```
Bug fix
**What …
> fix(bzlmod/go_deps): don't read go.sum for empty go.mod files

- internal/bzlmod/go_deps.bzl
- internal/bzlmod/go_mod.bzl
- internal/bzlmod/utils.bzl
- tests/bcr/MODULE.bazel
- tests/bcr/go.mod
- tests/bcr/go.sum
- tests/bcr/pkg/BUILD.bazel
- tests/bcr/pkg/mvs_test.go
- tests/bzlmod/BUILD.bazel
- tests/bzlmod/go_mod_test.bzl
- tests/bzlmod/utils_test.bzl
Feature
internal/bzlmod/go_mod
This PR adds support for`replace` directives in `go.mod` files. There are multiple acceptible formats for `replace` directives:
```
golang.org/x/net v1.2.3 => example.com/fork/net v1.4.5
golang.org/x/net => example.com/fork/net v1.4.5 (SUPPORT ADDED)
golang.org/x/net v1.2.3 => ./fork/net
golang.org/x/net => ./fork/net
```
For now, we will ONLY allow the second one in the list: replacing a path with a new path and version. Local directories will not be allowed.
Fixes #1449
> feat(bzlmod): support go.mod replace directives

- README.rst
This PR is mentioning [gazelle_haskell_modules](https://github.com/tweag/gazelle_haskell_modules) among existing [gazelle_cabal](https://github.com/tweag/gazelle_cabal).
> README update mentioning gazelle-haskell-modules

- internal/list_repository_tools_srcs.go
This breaks local builds when using IntelliJ with the Bazel plugin.
> Exclude `.ijwb` from repository tools srcs

- internal/bzlmod/go_deps.bzl
Bug fix
bzlmod
Ensures that implicit version upgrade warnings are not emitted for the root module if it uses replace directives to update versions.
> bzlmod: Fix interaction between replace and implicit upgrade check

- internal/go_repository.bzl
Feature
go_repository
Sometimes, specially when dealing with internal reposositories, it may be desirable to be able to pass variables into git through go mod tooling, this change allows someone to add this lines to their bazelrc and use ssh instead of https for their internal repositories:
```
build --repo_env=GONOSUMDB=gitserver.somecompany.com
build --repo_env=GIT_CONFIG_COUNT=1
build --repo_env=GIT_CONFIG_KEY_0=url.git@gitserver.somecompany.com:.insteadof
build --repo_env=GIT_CONFIG_VALUE_0=https://gitserver.somecompany.com
```
Fixes #946 
> feat: allow passing GIT_CONFIG_COUNT and it's related configs

- internal/bzlmod/go_deps.bzl
- tests/bcr/MODULE.bazel
- tests/bcr/patches/testify.patch
- tests/bcr/pkg/mvs_test.go
Feature
internal/bzlmod/go_deps
This adds a new `module_override` tag which allows a user to apply patches to a `go_deps` module.
Fixes #1499
Added a test which applies a patch and asserts on contents from the patched repo.
> feat(bzlmod): add `module_override` tag to allow patching in go_deps

- internal/bzlmod/go_deps.bzl
This fixes a typo. The `build_proto_file_mode` should actually be `build_file_proto_mode`
> fix typo `build_proto_file_mode` in message

- language/go/BUILD.bazel
- language/go/config.go
- tests/bcr/BUILD.bazel
Feature
language/go
If no prefix has been set but a go.mod file is present, use the path in its `module` directive.
This allows simple Go projects to start using Gazelle without specifying any directives.
> language/go: Infer prefix from go.mod

- BUILD.bazel
- MODULE.bazel
- internal/bzlmod/non_module_deps.bzl
All tests pass except for the Stardoc diff tests, which fail due to https://github.com/bazelbuild/bazel/issues/14140.
> Support Bzlmod for gazelle itself

- language/go/fileinfo.go
- rule/platform.go
Before this change `_windows_arm64.go` files were ignored by gazelle.
Bug fix
language/go
This PR adds windows + arm64 as a known platform.
Fixes #1506
> language/go: Add windows arm64 as a known platform.

- internal/bzlmod/directives.bzl
- internal/bzlmod/go_deps.bzl
Bug fix
_bzlmod/go_deps_
Disable protobuf generation for more modules. Include [the "k8s.io/apiextensions-apiserver" Go module](https://pkg.go.dev/k8s.io/apiextensions-apiserver) in the set for which we disable generation of Protocol Buffers files.
While we're here, correct the `go_deps` "module" tag class attribute documentation. In the deprecation notice introduced in #1456, mention the "gazelle_overrides" tag's "directives" attribute as the suggested target for the customizations to move.
Relates to #1451.
I discovered that I couldn't build my Go program that came to rely on this Go module …
> Disable protobuf generation for more modules

- label/label.go
- label/label_test.go
Bug fix
Gazelle extension using the label package
Relax label validation to support `~` characters in repo names.
Fixes #1517
Related change #1508
> Support '~' in label repo

- language/go/fileinfo.go
- rule/platform.go
Bug fix
language/go and rules
Adds support for the "unix" build tag added via https://github.com/golang/go/issues/20322
jackc/pgx is a popular pg lib that currently fails to build with bazel. Requires a local patch to change pgx code. 
https://github.com/jackc/pgx/issues/1520
Fixes #1465
> language/go: Handle `unix` build tag.

- def.bzl
Bug fix
cmd/gazelle
When trying to run an update-repos with a go.mod generated from a genrule() target, the go.mod isn't built as a dependency despite being specified as one with `data`. AFAICT this is because data isn't passed through to sh_binary.
Without the patch, this fails because go.mod doesn't exist:
`bazel run //:gazelle-update-repos`
```
gazelle: error from go list: running '/private/var/tmp/_bazel_preston4tw/416b5eb0536fd56dcbcf19cedbdb737f/external/go_sdk/bin/go /private/var/tmp/_bazel_preston4tw/416b5eb0536fd56dcbcf19cedbdb737f/external/go_sdk/bin/go list -mod=readonly -e -m -json all': go: cannot match "all": go.mod file not found in current …
```
> Pass data arg through to sh_binary if defined

- MODULE.bazel
- internal/bzlmod/go_deps.bzl
- tests/bcr/MODULE.bazel
This fixes a hack to `go_deps` which allows overrides from `rules_go` to still work (even when `rules_go` is not the main module.
This provides a dangerous experience by causing potential confusion regarding where an override could be coming from.
Because of that, this hack should be removed, since it is no longer needed with the latest `0.39.1` of rules_go.
> remove circular override hack

- internal/bzlmod/BUILD.bazel
- internal/bzlmod/default_gazelle_overrides.bzl
- internal/bzlmod/go_deps.bzl
- tests/bcr/MODULE.bazel
- tests/bcr/go.mod
- tests/bcr/go.sum
- tests/bcr/pkg/BUILD.bazel
- tests/bcr/pkg/mvs_test.go
This attribute is required as `build_file_generation` on `go_repository` doesn't have an equivalent directive.
Fixes https://github.com/bazelbuild/bazel-gazelle/issues/1520
> bzlmod: Add `build_file_generation` to `gazelle_override`

- merger/fix.go
- merger/fix_test.go
- merger/merger_test.go
- rule/rule.go
Feature
cmd/gazelle
Bazel allows to pack rules or macros within a struct, e.g. convenience interfaces for `select()`
(see https://github.com/bazelbuild/bazel-skylib/blob/main/lib/selects.bzl)
Changes adds support for macros/rules packed within bazel [struct](https://bazel.build/rules/lib/builtins/struct).
Load statements are not able to insert struct symbols. This is needed in case some macros are packaged into a struct like `selects.config_setting_group`
(see https://github.com/bazelbuild/bazel-skylib/blob/main/lib/selects.bzl#L245).
Any would like to generate `selects.config_setting_group` rule with `rule.LoadInfo`:
```go
{
Name: …
```
> Support macros/rules packed within bazel `struct`

- internal/bzlmod/go_deps.bzl
- internal/bzlmod/go_mod.bzl
- tests/bcr/MODULE.bazel
- tests/bzlmod/go_mod_test.bzl
Feature
go_deps
By returning `module_ctx.extension_metadata` with a list of the direct Go dependencies of the root module, Bazel 6.2.0 and later will generate fixup commands for `use_repo` calls (https://github.com/bazelbuild/bazel/issues/17908).
> bzlmod: Return `extension_metadata` to automate `use_repo` fixes

- language/go/embed.go
- language/go/testdata/embedsrcs/BUILD.want
- language/go/testdata/embedsrcs/embedsrcs.go
- language/go/testdata/embedsrcs/p_dir/build.old/static.txt
> Bug fix
> language/go
A bug  presently exists in `language/go/embed.go` where subdirectories with the name  `build` , e.g. `some/path/build` are being recognized as BUILD files, thereby resulting in those directories being skipped by the embed resolver. Please see more details in the linked issue.
To fix the issue, we only consider a path a `BUILD` or `BUILD.BAZEL` file if they are in fact not a directory.
Fixes #1538
> Fix `go:embed` failing to add `embedsrcs` for subdirectories named build

- internal/bzlmod/default_gazelle_overrides.bzl
- tests/bcr/MODULE.bazel
- tests/bcr/go.mod
- tests/bcr/go.sum
- tests/bcr/pkg/BUILD.bazel
- tests/bcr/pkg/mvs_test.go
Bug fix
Default directives
Sets default build file generation and default directives for `github.com/envoyproxy/protoc-gen-validate`
Fixes an issue when importing `github.com/envoyproxy/protoc-gen-validate` as a go module. This project is built with Bazel. The current (pre-fix) behaviour is for the WORKSPACE file in this project to be unaltered, which causes an error when it is used as a pure go module.
The test case feels a bit light, but it does validate the fix
> Add default directives for github.com/envoyproxy/protoc-gen-validate

- cmd/gazelle/BUILD.bazel
- cmd/gazelle/integration_test.go
- language/go/BUILD.bazel
- language/go/config.go
- language/go/fileinfo.go
- language/go/package.go
- rule/platform_strings.go
- tests/bcr/MODULE.bazel
- tests/bcr/go.mod
- tests/bcr/go.sum
- tests/bcr/pkg/BUILD.bazel
- tests/bcr/pkg/mvs_test.go
- tests/bcr/pkg/platform_lib_unix.go
- tests/bcr/pkg/platform_lib_windows.go
Bug fix
language/go
The constraint labels emitted as `select` keys now use the apparent name of the `rules_go` repository when using Bzlmod, with a fallback to `io_bazel_rules_go` if the `rules_go` module is not a declared `bazel_dep`.
> language/go: Emit apparent repo name of rules_go in select keys

- .bazelrc
Let Bazel always print out test errors, so we don't need to open the log when tests fail
> Output test errors

- README.rst
- language/go/resolve_test.go
- resolve/config.go
Similar to the resolve directive, resolve_regexp will match the import string against a regex instead of a direct string match. This is useful when matching protos which are part of single rule.
Syntax is the same as the resolve directive except that the import string can be a regex.
ie: 
```
```
Partially addresses #817
Feature
resolve/
I didn't add tests yet since I wasn't sure if this implementation agreeable. If we think that this is something that is upstreamable, I will add tests.
Thanks!
> resolve: Add a resolve_regexp directive

- .bazelci/presubmit.yml
I am not sure the value of testing two versions of Ubuntu with the same architecture, especially one of the versions is 7-year old. Let's test macOS arm64 instead, which becomes more and more popular.
Also upgrade to Ubuntu 22.04 for the rest
> Testing on macOS arm64

- README.rst
Documentation
all
This PR repairs the directive table in the Readme file by adding back a missing terminating pipe symbol in a table cell (which cause the whole table not to be rendered), and while there cleaning up a bit of white space near line ends in the same table.
> Fix directive table in Readme file

- internal/bzlmod/default_gazelle_overrides.bzl
> Bug fix
Default Go module configuration
Specify that Gazelle should generate BUILD files for the _github.com/grpc-ecosystem/grpc-gateway/v2_ Go module, since the BUILD files already present in that module's source repository contain references to Bazel repositories that are no longer created automatically by Gazelle.
See [the preceding discussion in the "go" channel](https://bazelbuild.slack.com/archives/CDBP88Z0D/p1689260233455729?thread_ts=1689168021.180399&cid=CDBP88Z0D) of the "Bazel" Slack workspace. There @fmeum suggested this fix.
I'm not sure whether or not we'll need to retain this default value if the upstream …
> Generate BUILD files for grpc-gateway by default

- deps.bzl
Update:
- golang.org/x/exp    v0.0.0-20190121172915-509febef88a4 -> v0.0.0-20230713183714-613f0c0eb8a1
- golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be -> v0.10.0
These were very old dependencies and there is no way to override them to newer ones by Gazelle user.
1. You cannot execute go_repository before calling gazelle_dependencies as @bazel_gazelle_go_repository_cache is not yet ready.
2. If you execute go_repository AFTER calling gazelle_dependences, the previously loaded old verision by gazelle_dependencies takes precendence.
It led to issues like:
- https://github.com/bazelbuild/bazel-gazelle/issues/1468
- https://stackoverflow.com/questions/64929217/bazel-gazelle-error-no-such-package-org-golang-x-tools-go-analysis-internal
Fixes: #1468
> …
> Update: golang.org/x/exp & golang.org/x/oauth2 deps.

- README.rst
README.md
I want to hint at the existence of a Kotlin PoC because I wasn't aware of it first and started implementing my own prototype.
[I am not involved with the creation of the linked PoC]
> [README.rst] Mention kotlin PoC

- internal/bzlmod/go_deps.bzl
- tests/bcr/MODULE.bazel
- tests/bcr/pkg/BUILD.bazel
- tests/bcr/pkg/pkg_test.go
Feature
bzlmod/go_deps
This adds the ability to specify a custom archive to a `go_deps` repository.
It can be used as part of the new tag `archive_override`:
```
go_deps.archive_override(
urls = [
"https://github.com/bazelbuild/buildtools/archive/refs/tags/v6.1.2.tar.gz",
],
strip_prefix = "buildtools-6.1.2",
path = "github.com/bazelbuild/buildtools",
sha256 = "977a0bd4593c8d4c8f45e056d181c35e48aa01ad4f8090bdb84f78dca42f47dc",
)
```
Fixes #1560
Tested in Uber's Go Monorepo, by overwriting to a bad URL:
```
Repository rule go_download_sdk_rule defined at: …
```
> feat(bzlmod): support archive_override in go_deps

- cmd/gazelle/integration_test.go
- cmd/gazelle/update-repos.go
Bug fix
cmd/gazelle
The `WORKSPACE` file should not be updated when `update-repos` is run with `-bzlmod` enabled.
Fixes #1588.
> fix: avoid updating `WORKSPACE` file when running `update-repos` when bzlmod is enabled

- internal/bzlmod/go_mod.bzl
- tests/bzlmod/go_mod_test.bzl
Feature
`go_deps`
Ignores the new `toolchain` directive without errors and also supports fine-grained `go` versions.
> Make `go_deps.from_file` compatible with Go 1.21

- internal/go_repository.bzl
This helps unblock the Go 1.21.0 upgrade
>
> Bug fix
> Feature
> Other
> For example:
>
> language/go
> cmd/gazelle
> all
Fixes #
> go_repository: fix missing default GOPROXY

- cmd/gazelle/fix-update.go
Bug fix
all
fix https://github.com/bazelbuild/bazel-gazelle/pull/1498 to actually support dir named `workspace`
**Notes**
Upon upgrading to the latest gazelle that includes https://github.com/bazelbuild/bazel-gazelle/pull/1498, we're still seeing
```
gazelle: read /private/var/tmp/_bazel_michael/ddd60c3e827a4aa3b925c14f76ccd5bf/external/com_github_sourcegraph_controller_cdktf_gen_tfe/WORKSPACE: is a directory
```
In https://github.com/bazelbuild/bazel-gazelle/pull/1498, we missed that the `FindWORKSPACEFile` will return `/some/path/WORKSPACE` regardless if one can be found. See the final `return` statement. …
> fix: patch support for dir named workspace

- internal/go_repository.bzl
This reverts commit adce430fa38848f0b3805e05f9520e419a41dfd7.
We found an alternative fix to this to this issue in
https://github.com/bazelbuild/rules_go/pull/3666.
>
> Bug fix
> Feature
> Other
> For example:
>
> language/go
> cmd/gazelle
> all
Fixes #
> Revert "go_repository: fix missing default GOPROXY (#1602)"

- go.mod
- go.sum
- vendor/golang.org/x/mod/internal/lazyregexp/lazyre.go
- vendor/golang.org/x/mod/modfile/print.go
- vendor/golang.org/x/mod/modfile/read.go
- vendor/golang.org/x/mod/modfile/rule.go
- vendor/golang.org/x/mod/modfile/work.go
- vendor/golang.org/x/mod/module/module.go
- vendor/golang.org/x/mod/module/pseudo.go
- vendor/golang.org/x/mod/semver/semver.go
- vendor/modules.txt
Bug fix
`go_deps`
This PR builds on the work done in PR #1605, which aims to add support for Go 1.21's updated version scheme.
However, the current `golang.org/x/mod` in the `vendor/` directory is not upgraded and is still using the old regex which does not support patch and prerelease versions.
Without this upgrade, users might get into the following error when running `bazel run //:gazelle`:
```shell
gazelle: reading module paths from /path/to/go.mod: /path/to/go.mod:3: invalid go version '1.21.0': must match format 1.23
```
> Upgrade `golang.org/x/mod` Vendor to Support Go 1.21

- repo/remote.go
- repo/remote_test.go
Bug fix
go_repository
The remote module mapping logic is overly aggressive with its compatibility mappings when it removes the major version from a versioned module path. It will shadow existing modules with an incorrect module path. This breaks recent versions of the AWS GoLang SDK with `go_repository`, for example. The only available work around is manual repository mappings passed to the `go_repository` workspace rule invocation, which should not be necessary.
Fixes #1595
It's possible `jayconrod`'s `TODO` on line 178 is a more appropriate fix here. But absent that, never shadowing seems …
> fix: go_repository: never shadow a module with a compatibility mapping for major versions.

- cmd/gazelle/fix_test.go
- cmd/gazelle/integration_test.go
- language/go/fileinfo.go
- language/go/package.go
- language/go/testdata/default_visibility/cmd/main.go
- language/go/testdata/main_no_bin/BUILD.want
- language/go/testdata/main_no_bin/main.go
Bug fix
language/go
Presently, gazelle generates `go_binary` targets for main packages with library code even if
the library doesn't have a main function. The no-main-function `go_binary` targets don't compile.
This PR updates gazelle to skip generation of `go_binary` for main packages where a main
function isn't present.
The first commits add a test showing the undesirable behavior. The tests pass because we aren't compiling the generated BUILD files -- but if we did compile them, it would fail.
The subsequent commits fix the issue and update the tests.
> bug fix: don't generate invalid go_binary rules for empty main packages

- rule/merge.go
- rule/merge_test.go
- rule/rule.go
- rule/value.go
- rule/value_test.go
> Feature
> - rule
> - merger
Implements merger interface so that `rule.SetAttr` can take arbitrary structs that implement `Merge` method that returns a `bzl.Expr` enabling users to define custom logic for merging attribute values within their BUILD.bazel files
Fixes #1072
Easiest reviewed commit by commit to see the logical progression
This was mainly achieved by storing the original value next to a pre-computed expression on the `rule.attrs` map, then casting to check for the merger interface.
Currently we fallback to the original logic if no merger interface exists on the `src` (or newly …
> Implement Merger interface

- internal/bzlmod/default_gazelle_overrides.bzl
- tests/bcr/MODULE.bazel.lock
Other
bzlmod default config
When updating to v0.32.0 anyone with a transient dependency on `github.com/googleapis/gax-go/v2` will need to add an override `gazelle:proto disable` directive. See here for discussion: https://github.com/bazelbuild/rules_go/issues/3625#issuecomment-1674275131
Adding the directive as a default should prevent a bunch of manual effort.
> Add an entry for "github.com/googleapis/gax-go/v2" to default_gazelle_overrides.bzl

- README.rst
- cmd/autogazelle/README.rst
This PR adds the new version and SHA to the `http_archive` examples in the README
> update readme for v0.33.0

- WORKSPACE
- deps.bzl
- go.sum
- tests/bcr/MODULE.bazel.lock
> Remove golang.org/x/crypto dep

- cmd/gazelle/fix-update.go
- cmd/gazelle/integration_test.go
- language/go/fix.go
Bug fix
`language/go` (misinterpretation of `KindMap`)
`cmd/gazelle` (`KindMap` not applied on empty rules)
Fixes #1440
> Fix map_kind with empty rules

- BUILD.bazel
- internal/is_bazel_module.bzl
- tests/bcr/MODULE.bazel.lock
Bug fix
all
- Add missing `bzl_library` declaration in repo generated by `is_bazel_module`. 
- Add dep to the above target to `//:def`.
NA
I added [a test to rules_swift](https://github.com/bazelbuild/rules_swift/blob/master/test/bzl_test.bzl) to catch these missing declarations. Would the maintainers be open to a PR adding this test to this repo?
> fix: add missing bzl_library declaration and dep

- tests/bzl_deps/BUILD.bazel
- tests/bzl_deps/bzl_test.bzl
- tests/bzl_deps/do_nothing_macro.bzl
Other
all
Provides build-time assurances that `bzl_library` declarations exist and are referenced properly.
Related to #1633.
> chore: add bzl_test to ensure that bzl_library declarations exist

- internal/gazelle.bash.in
This ensures that Gazelle itself or a language linked into it can discover runfiles no matter whether it needs `RUNFILES_MANIFEST_FILE` or `RUNFILES_DIR`. The latter is especially relevant for Python, which is run as part of the Gazelle Python plugin.
> Set runfiles environment variables for Gazelle

- internal/go_repository_tools_srcs.bzl
- internal/language/BUILD.bazel
- internal/language/test_load_for_packed_rules/BUILD.bazel
- internal/language/test_load_for_packed_rules/lang.go
- rule/rule.go
- tests/BUILD.bazel
- tests/bcr/MODULE.bazel.lock
- tests/fix_load_for_packed_rules/BUILD.out
- tests/fix_load_for_packed_rules/README.md
- tests/tools.bzl
Bug fix
internal/language
rule
tests
Bazel allows to pack rules or macros within a struct, e.g. convenience interfaces for select()
(see https://github.com/bazelbuild/bazel-skylib/blob/main/lib/selects.bzl)
Generated rule of `selects.config_setting_group` by [rule.NewRule()](https://github.com/bazelbuild/bazel-gazelle/blob/master/rule/rule.go#L723) is different with the rule parsed from the input file i.e. [ruleFromExpr()](https://github.com/bazelbuild/bazel-gazelle/blob/master/rule/rule.go#L757) in a way of different _kind_ and identifier when fixing loads ([FixLoads()](https://github.com/bazelbuild/bazel-gazelle/blob/master/merger/fix.go#L31)).
Newly …
> Fix kinds and stmt

- internal/go_repository_config.bzl
Bug fix
go_repository
Fixes the following error when gazelle is loaded from WORKSPACE, and `--enable_bzlmod` is set:
```
ERROR: /foo/BUILD.bazel:63:8: every rule of type _gazelle_runner implicitly depends upon
the target '@bazel_gazelle_go_repository_config//:WORKSPACE', but this target could 
not be found because of: no such target '@bazel_gazelle_go_repository_config//:WORKSPACE': 
target 'WORKSPACE' not declared in package '' defined by 
/home/vscode/.cache/bazel/_bazel_vscode/3dbdfd10a1e163b9a670d9ed81dfe3af/external/bazel_gazelle_go_repository_config/BUILD.bazel; however, a source file of this name exists.
(Perhaps add 'exports_files(["WORKSPACE"])' to …
```
> Export workspace file in go_repository_config.bzl

- internal/bzlmod/default_gazelle_overrides.bzl
- tests/bcr/MODULE.bazel.lock
Apparently, github.com/google/gnostic now references modules in github.com/google/gnostic-models. This seems to be related to this PR recent PR: https://github.com/google/gnostic/pull/400
After doing an update that pulled in this new module, we needed to add the directive proposed by this PR similar to how this was already needed for github.com/google/gnostic.
> Add github.com/google/gnostic-models to default_gazelle_overrides.bzl

- label/label.go
- label/label_test.go
Bug fix
gazelle as a library
After upgrading to Bazel 6.4.0, target-determinator, which uses `label.Parse` from Gazelle fails with an error as described in the referenced issue.
Fixes #1650
> Support parsing labels that begin '@@'

- internal/bzlmod/default_gazelle_overrides.bzl
- tests/bcr/MODULE.bazel.lock
I messed up this path. Looks like github.com/googleapis/gnostic directs to github.com/google/gnostic, but there's no equivalent redirect for gnostic-models.
> Fix path for google/gnostic-models

- internal/bzlmod/default_gazelle_overrides.bzl
- internal/bzlmod/go_deps.bzl
- tests/bcr/MODULE.bazel.lock
Fix
bzlmod
When using `bzlmod` the `gazelle_override` doesn't support command line arguments to pass to Gazelle.
This PR adds the `build_extra_args` attribute
Fixes #1647
> fix(bzlmod): allow passing build_extra_args in gazelle_override

- .bcr/metadata.template.json
- .bcr/presubmit.yml
centos7 doesn't support `-std=c++14`.
> Don't run on centos7 in BCR presubmit and add maintainers

- README.rst
- cmd/autogazelle/README.rst
Updating readme for https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.34.0
> update readme for v0.34.0

- internal/bzlmod/go_deps.bzl
- tests/bcr/MODULE.bazel
- tests/bcr/MODULE.bazel.lock
- tests/bcr/patches/buildtools.patch
- tests/bcr/pkg/pkg_test.go
There are times when we need to specify custom `urls`, custom `directives` and custom `patches` to an archive. 
We should allow users to apply `patches` to the `archive_override`, similar to https://docs.bazel.build/versions/5.0.0/skylark/lib/globals.html#archive_override
> feat(bzlmod): allow patches in `archive_override`s

- internal/bzlmod/go_deps.bzl
- tests/bcr/MODULE.bazel.lock
We should not allow users to specify overrides to Go dependencies which aren't defined. This adds a failure case for scenarios when overrides are declared by a user for a path that isn't loaded by the `go_deps` extension.
Fixes #[1668](https://github.com/bazelbuild/bazel-gazelle/issues/1668)
```
tfrench@tfrench-go ~/bazel-gazelle/tests/bcr
% git diff
diff --git a/tests/bcr/MODULE.bazel b/tests/bcr/MODULE.bazel
index 19c0c7e..a37b882 100644
--- a/tests/bcr/MODULE.bazel
+++ b/tests/bcr/MODULE.bazel
@@ -48,6 +48,14 @@ go_deps.module_override(
path = "github.com/stretchr/testify",
)
+go_deps.module_override(
+    patch_strip = 1,
+    patches = [
+        "//patches:testify.patch",
+    ],
+    path = "doesn't exist",
+)
+
go_deps.gazelle_override(
directives = [
tfrench@tfrench-go …
```
> fix(bzlmod): fail on unused overrides

- internal/bzlmod/go_deps.bzl
- internal/bzlmod/go_mod.bzl
- tests/bzlmod/go_mod_test.bzl
Bug fix / Feature
bzlmod support for Go
This adds support for `go.mod` replace directives with a version qualifier as described by https://go.dev/ref/mod#go-mod-file-replace.
Fixes #
> bzlmod: support go.mod replace directives with a version qualifier on the left

- resolve/BUILD.bazel
- resolve/config.go
- resolve/resolve_test.go
Feature
resolve
**Enhancements in Resolve Directive Handling**
This PR addresses the inefficiency of processing `# gazelle:resolve` directives. Previously, the system iterated over a slice for each import to find matching directives, which is very inefficient. This PR introduces two major improvements:
1. **Transition from Slice to Map**: We've shifted from using a slice to a map for storing override configurations. This change reduces lookup time complexity from O(n) to O(1) (or O(length of chain of enclosing dirs containing resolves)). 
2. **Parent-Child Config Structure**: To maintain directory-specific configurations without the overhead of copying maps (which is very inefficient), we've implemented …
> feat(resolve): optimize applying overrides to be efficient

- cmd/gazelle/fix-update.go
Previously, if mapped kinds were in use (i.e. `go_library` -> `go_custom_library`), and `gazelle update` was being run on just one directory, Gazelle's indexing system would fail to correctly index build rules of the mapped-to kind in directories that were not being re-built.
This is because the logic to handle mapped kinds was triggered only when Generate() was run, not for Imports().
This PR solves the issue with the smallest fix. The whole kind-mapping system is honestly kinda messy, and I didn't want to propose a major refactor.
Bug fix
cmd/gazelle
> Fix partial execution with mapped kinds

- rule/rule.go
- rule/rule_test.go
Feature
rule/rule.go
This allows user to attach comments like "# do not sort" to the assignment expressions maintained by rule.go.
rule.Format() calls into buildtools/build.Format() which in turn calls Rewrite(). Rewrite() by default sorts certain label arguments like "deps" and "hdrs". To preventing this sorting it is possible to provide the comment "# do not sort". However this comment needs to be attached to the assignment expression.
In rule.go the assignment expressions are not exposed to the user, making it impossible to attach the comment to it.
See https://github.com/bazelbuild/bazel-gazelle/issues/237#issuecomment-399476945
**Which issues(s) does this …
> rule: add accessor for attribute comments

- cmd/gazelle/fix-update.go
- language/go/config.go
- rule/rule.go
- walk/walk.go
> Other
Optimization and removal of deprecated API usage
> all
`ioutil` is deprecated, usage should be migrated to `os`.
In particular, `os.Readdir` is faster than `ioutil.Readdir` because it does not `stat` all the files to gather extra data which we don't need. On a fairly large repo, a no-op run of Gazelle drops from 2.2s to 1.7s with this patch.
I only changes the `ioutil` usages in the files I was touching anyway, but can change the rest in this PR if it's preferred.
A TODO in the code
> Remove some usage of deprecated ioutil

- def.bzl
Feature
Gazelle runner
This allows Gazelle runner to take Gazelle binary as a single file, so we can pass a pre-built Gazelle binary.
> Allow passing Gazelle binary as a file

- rule/BUILD.bazel
- rule/value.go
- rule/value_test.go
Feature
rule
The Label is a convenient structure for custom logic. Allow its use with the Rule APIs so the user can directly feed structured data back into Gazelle.
> rule: allow usage of Label struct with Rule APIs

- internal/gazelle.bash.in
Bug fix
gazelle-runner
Fixes two shellcheck warnings (https://www.shellcheck.net/wiki/SC2155)
> Fix two shellcheck warnings in gazelle.bash.in

- README.rst
- WORKSPACE
- cmd/autogazelle/README.rst
This PR updates the documentation to reflect the new version of `rules_go` and `gazelle`
> update documentation for 0.35

- internal/bzlmod/default_gazelle_overrides.bzl
`github.com/cockroachdb/errors` contains pre-generated codes for protos.
Other
bzlmod
disable proto for module `github.com/cockroachdb/errors`.
> Add default gazelle override for github.com/cockroachdb/errors.

- internal/bzlmod/go_deps.bzl
- tests/bcr/MODULE.bazel
This PR creates a new tag class `default_gazelle_attributes` which allow the root module to provide default values for the gazelle attributes used to create the `go_deps` repos.
This includes the attributes: `"build_file_generation"`, `"build_extra_args"`, and `"directives"`. 
Default attributes will be applied to an attribute only if there is no `gazelle_override` value. 
If `default_gazelle_attributes` is provided, it will override all path-specific overrides created in `internal/bzlmod/default_gazelle_overrides.bzl`, so users may need to reapply these with `gazelle_override`s.
If a repo has either a `gazelle_override` or there is a `default_gazelle_attributes`, the `"build_file_generation"` attribute will be set to `"on"` unless explicitly set to a different value. This is because …
> feat(bzlmod): allow `default_gazelle_attributes` for `go_deps` extension

- internal/generationtest/generationtest.bzl
Bug fix
internal/generationtest
Using an hardcoded label in `generationtest.bzl` would prevent users that are using the `gazelle_generation_test` macro from using it without explicitly set `repo_name = io_bazel_rules_go` in `MODULE.bazel`.
At the moment, running without `repo_name`:
```bzl
bazel_dep(name = "rules_go", version = "0.46.0")
```
```sh
$ bazel test //...
ERROR: no such package '@@[unknown repo 'io_bazel_rules_go' requested from @@]//go/tools/bazel': The repository '
@@[unknown repo 'io_bazel_rules_go' requested from @@]' could not be resolved: No repository visible as '@io_baze
l_rules_go' from main repository
ERROR: …
```
> fix: wrap generation test labels with Label()

- .bazelci/presubmit.yml
- .bcr/presubmit.yml
- cmd/gazelle/BUILD.bazel
- cmd/gazelle/fix-update.go
- cmd/gazelle/update-repos.go
- config/BUILD.bazel
- config/config.go
- language/proto/constants.go
- language/proto/proto.csv
- language/proto/resolve.go
- tests/bcr/.bazelrc
- tests/bcr/MODULE.bazel
- tests/bcr/go.mod
- tests/bcr/go.sum
- tests/bcr/proto/BUILD.bazel
- tests/bcr/proto/foo.proto
- tests/bcr/proto/foo_test.go
Bug fix
language/proto
config
Uses the user-supplied `repo_name` of the `protobuf` Bazel module when referencing well-known types.
Along the way makes `ModuleToApparentName` public API on `config.Config` for use in the `proto` language. The new API is generally useful for Bzlmod interop, only provides access to immutable data and can, in a Bzlmod-only future, be used to fail when a `bazel_dep` required by a language isn't available.
Fixes #1739
> proto: Add Bzlmod support for well-known types

- internal/bzlmod/default_gazelle_overrides.bzl
Set the go_naming_convention for github.com/google/cel-go
default_gazelle_overrides
I'm not sure why this isn't being auto detected, but I needed to add the override directive for Gazelle to write the imports correctly.
Fixes # (not filed)
I am applying a patch to the repo to change a package visibility, which could be causing the auto detect failure:
```
go_deps.module_override(
path = "github.com/google/cel-go",
patch_strip = 1,
patches = [
"//:build/0001-cel-go-Change-visibility-of-ast-to-public.patch",
],
)
go_deps.gazelle_override(
directives = [
"gazelle:go_naming_convention …
```
> Set go_naming_convention for cel-go

- MODULE.bazel
- internal/bzlmod/go_deps.bzl
- internal/bzlmod/non_module_deps.bzl
- tests/bcr/MODULE.bazel
Feature
With this PR, `go_deps.config(go_env = {...})` can be used to specify environment variables for go_repository, replacing gazelle_dependencies(go_env = ...). They are exported in a way that makes them usable for `@rules_go//go`, which will be done in a follow-up change to rules_go.
I will add documentation after the rules_go change has been merged.
Work towards https://github.com/bazelbuild/rules_go/issues/3814
This is an alternative to https://github.com/bazelbuild/rules_go/pull/3879, on which @linzhp remarked that there is a potential of confusion as `go_env` can't and …
> Add `go_deps.config(env = ...)` as a replacement for `gazelle_dependencies(go_env = ...)`

- internal/go_repository.bzl
Feature
go_repository
This PR adds a warning for not specified sha256 for archive in the go_repository rule which provides the correct checksum.
It simplifies finding and fixing such cases. It is important for reproducible builds and caching.
It is a small change, not sure if issue is needed.
> Warn if integrity not specified for archive_override

- cmd/fetch_repo/BUILD.bazel
- cmd/fetch_repo/module.go
- internal/go_repository.bzl
- internal/go_repository_cache.bzl
- repository.md
- vendor/golang.org/x/mod/sumdb/dirhash/hash.go
- vendor/modules.txt
Feature
go_repository_cache
This PR adds an environment variable GO_REPOSITORY_USE_HOST_MODCACHE, which enables use of only GOMODCACHE without affecting GOPATH and GOCACHE.
And adds a sum verification to fetch_repo tool, since `go mod download` do not verify modules taken from cache.
Fixes #1754
> Use host module cache whithout build cache and verify it

- language/go/build_constraints.go
`purego` is a proposed[1] de-facto build constraint to denote building _only_ Go code.
We must ignore this constraint to make sure that files that toggle on `purego` are added to the Bazel target `srcs` and let the compiler decide if they should be compiled or not.
[1]: https://github.com/golang/go/issues/23172
This is required to land bazelbuild/rules_go#3901 which will enable the de-facto `purego` build constraint to be picked up in the Bazel Go ecosystem automatically when `pure = "on"` is defined in a `go_binary`, etc.
> Ignore `purego` build constraint

- internal/bzlmod/go_deps.bzl
Feature
go_deps
In a follow-up change, `rules_go` will use this path to automatically run `bazel mod tidy` when the content of the file changes.
The change to the contents of `config.json` isn't breaking since we haven't cut a release with it yet.
Work towards #1749
> Expose path to root `go.mod` to rules_go

- BUILD.bazel
Bug fix
go_repository
Fixes: 
> Stardoc documentation generation failed: File /home/coder/.cache/bazel/_bazel_coder/c91ea700cafcab35837a5ae95cae9020/sandbox/linux-sandbox/33/execroot/services/bazel-out/k8-opt-exec-2B5CBBC6/bin/bazel/docs/rules/java/image_stardoc.runfiles/bazel_gazelle/deps.bzl imported '//internal:is_bazel_module.bzl', yet /home/coder/.cache/bazel/_bazel_coder/c91ea700cafcab35837a5ae95cae9020/sandbox/linux-sandbox/33/execroot/services/bazel-out/k8-opt-exec-2B5CBBC6/bin/bazel/docs/rules/java/image_stardoc.runfiles/bazel_gazelle/internal/is_bazel_module.bzl was not found.
Fixes #
> Add is_bazel_module to deps.bzl.

- README.rst
It's a bit confusing for newer users onboarding Gazelle that the only doc available are for WORKSPACE mode.
Add a pointer to BzlMod documentation.
In the longer run, we should start adding `WARNING` log to `update-repos` command to let people know that it should not be used with bzlmod enabled.
> Add a pointer to bzlmod guide

- cmd/fetch_repo/copy_tree.go
- cmd/fetch_repo/go_mod_download.go
- cmd/fetch_repo/module.go
This failure was confusing to our users. We should make more clear error messages in cases when a `GOMODCACHE` might be corrupt.
Resolves #1774
Example failure:
```
ERROR: /home/user/go-code/WORKSPACE:69:26: fetching go_repository rule //external:com_github_bazelbuild_remote_apis: Traceback (most recent call last):
File "/home/user/.cache/bazel/_bazel_tfrench/b97476d719d716accead0f2d5b93104f/external/bazel_gazelle/internal/go_repository.bzl", line 263, column 17, in _go_repository_impl
fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_bazelbuild_remote_apis: fetch_repo: resulting module with sum h1:xhO5v3Ac039HesaPqoVUwOy4WhRRJbmo9om245kp+AY=; expected sum h1:xhO5v3Ac039HesaPqoVUwOy4WhRRJbmo9om245kp+AY=, Please try clearing your module …
```
> [cmd/fetch_repo] make cache corruption failures more clear

- cmd/fetch_repo/go_mod_download.go
In previous change it was passed conditionally so it was separate, now it's always added.
> Nit: pass -modcacherw in exec.Command.

- testtools/files.go
Bug fix
testtools
Normalise newlines on Windows
Otherwise assorted things go wrong when running tests using this infrastructure on Windows where \r\n line endings confuse things.
We've been trying to get the Java gazelle plugin's CI working on Windows, and this is our last blocker.
> Normalise newlines on Windows

- internal/bzlmod/go_mod.bzl
- tests/bcr/go_work/go.mod
- tests/bcr/go_work/go.work
Fix go work use ROOT moddir
It works on https://github.com/stefanpenner/bazel-gazelle/commit/acaa88e691debcbccf87a996e7b9bd00d3e104f2, but fail at master.
cc @stefanpenner
> Fix go.work use ROOT moddir

- def.bzl
Bug fix
cmd/gazelle
Right now we pick Gazelle for the "exec" platform. This isn't correct, because we are not running Gazelle as part of a build action. Instead, we are emitting a shell script that *invokes* Gazelle. That's why we need to make sure it's built for the target platform.
This addresses an issue where Bazel ends up invoking a copy of Gazelle for Linux on my Mac, if I invoke bazel with
--extra_execution_platforms=//my_linux_platform,//my_mac_platform.
n/a
> Ensure the Gazelle binary is built for the right platform

- internal/bzlmod/go_deps.bzl
- tests/bcr/go_mod/MODULE.bazel
Bug fix
go_deps
This allows debug_mode to be passed to each `go_repository` as a global option. It could be further extended to allow on a per-module basis later.
Fixes #1805
> Add support for `debug_mode` option to `go_deps`

- language/go/generate.go
- language/go/resolve_test.go
- language/proto/resolve.go
- language/proto/resolve_test.go
Gazelle used to resolve all generated Go packages from well-known types of proto to their `go_proto_library` targets. This is no longer the case. Even targets like `@io_bazel_rules_go//proto/wkt:descriptor_go_proto` are merely alias to the `go_library` targets of pre-generated code.
This PR:
1. Makes `go_default_library_gen` targets aliases to their `go_default_library` targets. Those targets exist only to resolve the well-known types to their old `go_proto_library` targets under `@io_bazel_rules_go//proto/wkt`
2. Stops Gazelle from resolving to those `go_default_library_gen` targets
3. Stops using `knownGoProtoImports`. They no longer point to `go_proto_library` targets. Their current label are regular Go packages.
I will further remove `knownGoProtoImports` as a follow up PR, because it …
> Remove special resolution of go_proto imports

- cmd/gazelle/fix-update.go
Other - this addresses variable hiding warnings pointed out by `nogo`, and changes no functionality
`cmd/gazelle`
This PR will make `nogo` stop complaining about `gazelle` when it is checking a `bazel` project.
Fixes #1777
> address nogo complaints about variable shadowing

- internal/bzlmod/go_mod.bzl
Bug fix
go_repository
Gazelle can now read `go.work` files. However, it is unable to parse them if they contain a `toolchain` directive. In go.mod files, those directives are already ignored.
n/a
> go_deps: ignore go.work toolchain directive

- internal/go_repository_cache.bzl
> Bug fix
>
> internal
Handles arm64 host platform in `go_repository_cache` repository rule
Fixes #1816 
It might be possible to use this https://bazel.build/rules/lib/builtins/repository_os.html#arch instead of `uname` like rules_go does, but not sure if it breaks Bazel version compatibility. Either way, I kept it similar to existing code to avoid refactor.
> Handle arm64 host platform for MacOS

- walk/config.go
- walk/walk_test.go
Bug fix
all
Bazel supports leading ./ in .bazelignore, so should gazelle
Fixes #
> fix: support leading ./ in .bazelignore

- BUILD.bazel
- MODULE.bazel
- WORKSPACE
- cmd/fetch_repo/BUILD.bazel
- cmd/fetch_repo/errorscompat.go
- cmd/fetch_repo/go_mod_download.go
- go.mod
- internal/go_repository_tools_srcs.bzl
Bug fix
cmd/gazelle
Also test compatibility of fetch_repo and gazelle.
Fixes #1826
> Restore compatibility with Go 1.18

- .bazelci/presubmit.yml
Builds ([example](https://buildkite.com/bazel/bazel-gazelle/builds/4022#01909d11-a3eb-4f13-bfd9-aa98755ba7d2)) are failing because this test is timing out on Mac OS.
Let's temporarily disable this large test to unblock development.
The `//internal:bazel_test` is still run on `ubuntu2204`
> temporarily disable `//internal:bazel_test` on Mac to fix CI

- merger/fix.go
- merger/fix_test.go
If two extensions both import Kinds from the same file, and no load statement for those Kinds is already in the BUILD.bazel file, then Gazelle will add the load statement twice.
In this commit, we fix the issue by updating the tracked loads when a new load is inserted into the index. This will cause future iterations to update the existing load instead of creating a duplicate.
>
Bug fix
cmd/gazelle
This PR fixes a bug where is two extensions each load a statement from the same file, and the file has no load statements at all, duplicate load statements will be added to the top of the file.
**Which issues(s) does …
> [Gazelle] Fix Duplicate Load Bug

- language/proto/fileinfo.go
- language/proto/fileinfo_test.go
Prior to this commit, the regex for determining whether a file had services did not require a space between the word "service" and the service name. This could lead to false alarms, like "message serviceABC". In this commit, we update the regex to only match if there is at least one space between service and the service name.
Bug fix
language/proto
Fixes a bug where the HasServices regex could incorrectly match messages that have "service" at the beginning of its name.
None, small bug fix
> [Proto] Require space between 'service' and service name in regex matching

- language/proto/fileinfo.go
- language/proto/fileinfo_test.go
- language/proto/generate_test.go
In order to construct a fully qualified Java import from the proto file, we need to know the values of the "java_package" option as well as the services, messages, and enums in the proto file. The "java_pacakge" option is already recorded. In this commit, we add support for parsing the names of the services, message, and enums of a proto file and tracking them in the FileInfo struct.
Feature
language/proto
This feature tracks additional information that is parsed from the proto file and tracked in the FileInfo object. This includes the names of all Services, Messages, and Enums in the proto file. This will be helpful for constructing the imports for fully …
> [Proto] Keep track of the names of Services, Messages, and Enums

- testtools/files.go
> Bug fix/ Feature
> gazelle_generation_test
When iterating on new language plugins, it is helpful to have the CheckFiles validation run so that any mismatched BUILD file output can be shown.
Replacing `FailNow` with `Fail` allows for this
Open to making this configurable, but this seems like a better default from the initial implementation 
https://github.com/bazelbuild/bazel-gazelle/commit/62afca5f276a56c1aa40804055a3a121295f53d8#diff-6ced8e81668a603f2efffea7938a66f16185221acdaab6e16f112377e663fbe5R343
> Always check files in generation tests

- internal/go_repository_tools_srcs.bzl
- tools/BUILD.bazel
- tools/override-generator/BUILD.bazel
- tools/override-generator/README.md
- tools/override-generator/main.go
- tools/override-generator/main_test.go
This PR creates a tool that converts either a repository macro file or a WORKSPACE into a set of `go_deps.{}_overrides`. This is supposed to ease the migration to Bzlmod.
For example, if you were to run on this `go_repository` rule:
```
go_repository(
name = "com_github_bazelbuild_bazel_watcher",
build_extra_args = ["-go_naming_convention_external=go_default_library"],
build_file_generation = "off",  # keep
build_file_proto_mode = "disable",
importpath = "github.com/bazelbuild/bazel-watcher",
patch_args = ["-p1"],
patches = [
"//patches:com_github_bazelbuild_bazel_watcher-go-embed.patch",
],
sum = "h1:EfJzkMxJuNBGMVdEvkhiW7pAMwhaegbmAMaFCjLjyTw=",
version = "v0.23.7",
)
```
It would output
```
go_deps = use_extension("@bazel_gazelle//:extensions.bzl", "go_deps")
go_deps.gazelle_override( …
```
> feat(tools): add a tool to automate the generation of go_deps overrides

- label/label.go
- label/label_test.go
Bug fix
label
This accommodates the flip of `--incompatible_use_plus_in_repo_names` in Bazel 8.
> Allow `+` in repo names

- internal/go_repository_cache.bzl
Bug fix
go_repository_cache
Override the **GOTOOLCHAIN** local environment parameter defined by `go env -w` to use the local Go environment made available by `gazelle`.
Fixes #1858
Same fix than https://github.com/bazelbuild/rules_go/pull/3660 in [rules_go](https://github.com/bazelbuild/rules_go).
> go_repository_cache: set GOTOOLCHAIN to 'local'

- internal/bzlmod/default_gazelle_overrides.bzl
Other
internal/bzlmod
Disable github.com/containerd proto generation in default directives as [suggested in `rules_go` documentation](https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/bzlmod.md#gazelle-directives).
> Add default directives for github.com/containerd

- internal/bzlmod/default_gazelle_overrides.bzl
Other
bzlmod
Adds default directives needed for some go libraries
I realized we have some gazelle directives we use to make the listed libs build. Adding it to the default overrides so I don't need it in our libs.
> Add gazelle-overrides for argo, grpcgateway

- resolve/index.go
refactor
all
Minor cleanup, also working toward making `ruleRecord` being serializable.
> refactor: remove file reference from ruleRecord

- resolve/index.go
refactor
all
Refactor working toward serializing+caching of the rule index.
The `ruleRecord` should be as close as possible to what a language returns. All computed data such as that for indexing should be computed from the `ruleRecord` and persisted elsewhere.
Ref: #1181
Some ideas are similar to #1182 while trying to reduce the scope of the change and diff.
IMO this is a reasonable cleanup on its own, without even taking serializing+caching into account 🤷
> refactor: compute transitive embeds during indexing

- cmd/gazelle/fix-update.go
- cmd/gazelle/metaresolver.go
- language/go/resolve_test.go
- language/proto/resolve_test.go
- resolve/index.go
Other
all
Ensuring all fields in `ruleRecord` are primitive or easily serializable.
> refactor: remove reference to rule.Rule in mapResolver interface

- resolve/index.go
Other
all
Assert no new rules are added after rules have been indexed. This should never happen but an assertion is probably worth doing, especially as we move toward persisting the index and loading from a cache.
> refactor: ensure rule index not modified after indexing

- extend.md
- internal/generationtest/generationtest.bzl
> docs: fix incorrect gazelle_generation_test param name

- internal/generationtest/BUILD.bazel
- internal/generationtest/generationtest.bzl
Other
all
Try to reduce the re-compiling of the same go files for every single test. I think using `embed` is no faster because it is linking that is slow? Still seems like a step in the right direction though.
> refactor: embed gazelle generation_test_binary in gazelle_generation_test instead of recompiling

- resolve/index.go
Using `json.[Un]Marchal`  is one way of serializing the data and the easiest one to start with. This change just does the ugly diff renaming everything to work with those marshalling methods. Do we want to rename any of these fields while we have to change them anyway?
Other
all
Make the `ruleRecord` serializable to json in preparation for caching it.
> refactor: make ruleRecord serializable

- MODULE.bazel
- deps.bzl
- internal/go_repository.bzl
- tests/bcr/go_mod/BUILD.bazel
- tests/bcr/go_mod/MODULE.bazel
- tests/bcr/go_mod/tests.bzl
Feature
go_repository
All targets in a `go_repository` with generated build files are tagged with a `package_info` automatically created by the repo rule.
This PR does not add any license information yet.
Work towards #1314 
> Add package metadata to `go_repository`s

- cmd/gazelle/fix-update.go
- cmd/gazelle/metaresolver.go
- cmd/gazelle/update-repos.go
- config/config.go
- internal/gazellebinarytest/xlang.go
- resolve/config.go
- rule/rule.go
- rule/value.go
- walk/config.go
- walk/walk_test.go
Just something I find useful both for the assertion and devx when browsing the code. Now each struct explicitly declares which interface it's implementing and you'll get an error directly beside that struct if something is wrong.
> Other
all
Minor cleanup
> refactor: add nil assignments to verify interface implementations

- walk/config.go
- walk/walk.go
The `.bazelignore` should be loaded once upfront and not depend on the `config.Configurer` invocation order.
`.bazelignore` does not support globs like the gazelle `excludes` so a simple map lookup instead of glob evaluation is enough and faster.
Do not invoke `config.Configure` on a directory which is `.bazelignore`d, unlike `excludes` which only applies to sub-directories within a BUILD.
Other
all
Cleanup
> perf: preload .bazelignore before configure, do not use globs

- walk/walk.go
This function literal confuses me everytime I see it and imo is nicer as a plain function.
Other
all
Minor refactoring/cleanup.
> refactor: remove nested walk function literal

- label/label.go
- label/label_test.go
Bug fix
label
Previously, parsing and then stringifying a label would turn `@@canonical~name//pkg:target` into `@canonical~name//pkg:target`, which is no longer valid.
The new field on `Label` defaults to `false` if not set, which preserves the current behavior.
Fixes #1862
> Preserve canonical labels as such

- walk/walk.go
Other
all
Now that the `.bazelignore` is done before `configure` it can also be before the `os.ReadDir`.
> perf: check if directory in .bazelignore before readdir

- cmd/gazelle/fix-update.go
- cmd/gazelle/metaresolver.go
- language/go/resolve_test.go
- language/proto/resolve_test.go
- resolve/index.go
We need access to `rule.Name()` as well as `rule.Kind()` in mapped resolver.
> revert #1873

- def.bzl
Feature
bazel's gazelle_test
Supports removing noisy warnings like:
```
WARNING: //:gazelle_test: Test execution time (0.1s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
```
N/A
> Support timeout and size in gazelle_test

- MODULE.bazel
- deps.bzl
- internal/go_repository.bzl
- tests/bcr/go_mod/MODULE.bazel
- tests/bcr/go_mod/tests.bzl
Requires upgrade to the 1.0.0 release of rules_license, which is more appropriate than a pre-release anyway.
Follow-up to #1852
Note that I'm still unable to gather the resulting data from an end-user point of view using the aspects provided by rules_license. Will look for some help on Slack to see if there's still missing plumbing.
> feat: include package URL in package_info

- cmd/gazelle/diff.go
- cmd/gazelle/diff_test.go
- tests/diff_mode/expectedStdout.txt
- tests/loads_from_flag/expectedStdout.txt
Bug fix
cmd/gazelle
This PR adds a workaround to strip trailing newlines from the resulting diff when running Gazelle in `mode=diff`.  This aligns with the expected behavior of modern diff tools, which will ignore the last newline in a file.  This is implemented to resolve an issue where modifying the end of a file caused Gazelle to output a diff that was invalid, due to the newlines.  Applying patches generated in this case could not be applied when using `git apply` and would apply, but with a warning identifying this issues when using the system `patch` utility.
Fixes #1916 
How to Reproduce: …
> Fix patch file creation using Gazelle in diff mode

- merger/merger.go
perf improvement
gazelle core
This slightly improve runtime perf due to avoiding allocations of the error object and reduced GC pressure
[Profile](https://private-user-images.githubusercontent.com/94403429/367062767-c15a6a5d-e237-463e-beaf-332aa0fe4634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzcwMjAsIm5iZiI6MTcyNjE3NjcyMCwicGF0aCI6Ii85NDQwMzQyOS8zNjcwNjI3NjctYzE1YTZhNWQtZTIzNy00NjNlLWJlYWYtMzMyYWEwZmU0NjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmV …
> perf: Improve merger.Mergefile

- walk/BUILD.bazel
- walk/config.go
- walk/walk.go
Other
all
Walk the bazel workspace fs directories in parallel to build a structure representing the workspace *before* invoking the gazelle phases.
Similar to https://github.com/bazelbuild/bazel-gazelle/pull/1820 from @dzbarsky including using ~~the same~~ a simplified `pathTrie` struct but using a simple custom `walkDir` method instead of introducing a new external dep.
Fixes #1819
Closes #1820
> perf: walk workspace directories in parallel

- walk/config.go
- walk/walk.go
refactor / perf
> all
Reduce duplicate `path.Join` invocations. Remove duplicate `isBazelIgnored` invocations (it is not needed on the root dir, it is invoked before recursing).
Fixes #
> refactor: reduce path.join while walking repo

- internal/bzlmod/default_gazelle_overrides.bzl
I was just toying around with Gazelle and the rclone project (see https://github.com/rclone/rclone/issues/8093). These changes were necessary, but not sufficient, to build `//:rclone` with Gazelle-generated BUILD files.
I also needed to make a change for hdfs in my MODULE.bazel, but someone already beat me to it in https://github.com/bazelbuild/bazel-gazelle/pull/1867. I solved my problem with `gazelle:proto legacy`, but it looks like the existing override does something different.
>
> Bug fix
> Feature
Other
> For example:
>
> language/go
> cmd/gazelle
> all
bzlmod
Adds default …
> Add gazelle overrides to enable building rclone

- tools/override-generator/main.go
- tools/override-generator/main_test.go
If a repo specifies `gazelle_default_attributes` to be something
different than the `gazelle_override` tag defaults,
the user should be able to pass this to the override generator
so that the output takes this into consideration, and skips
outputing redundant information.
This PR allows the user to specify a default `build_file_generation`
and `build_file_proto_mode` that is used in their repo, and generate appropriate overrides.
These two tags need to be handled manually after the other tags because of the
non-trivial logic in them.
> override-generator: allow users to specify default values

- extend.md
- internal/generationtest/generation_test.go
- internal/generationtest/generationtest.bzl
- tests/BUILD.bazel
- tests/bazelignore/BUILD.out
Feature (testing enhancement for extension developers)
gazelle_generation_test
gazelle_generation_test uses the existence of a WORKSPACE file to indicate a directory is a test case. This PR extends gazelle_generation_test to also look for directories with a MODULE.bazel file.
A test case is modified to check the logic.
Fixes # 1947
Added as part of kotlin gazelle development.
> Support MODULE.bazel test cases for gazelle_generation_test.

- def.bzl
- internal/bzlmod/go_deps.bzl
Feature
all
I'm doing some experiments, where I'm trying to parse/analyze some existing Bazel rules using Go Starlark. This seems to be mostly successful, though I am noticing some small breakages.
It fixes an issue where dict.pop() is called with named arguments in a couple of places, even though it's only supposed to be called with positional arguments.
> Don't call dict.pop() with named arguments

- internal/bzlmod/go_deps.bzl
> Bug fix
> go_deps
Replaces https://github.com/bazelbuild/bazel-gazelle/pull/1949
> go_deps should fail with a clear message when 2 modules that only differ in case are used

- internal/bzlmod/go_deps.bzl
>Other
>go_deps
Follow up to https://github.com/bazel-contrib/bazel-gazelle/pull/1957 which set the behavior to a hard failure such this case. It's best to start as a warning and progressively tighten it up if need be.
> Warning users when versions requested via bazel_dep and go.mod differ for the same go module

- deps.bzl
- go.mod
- go.sum
- tests/bcr/go_mod/go.mod
- tests/bcr/go_mod/pkg/pkg_test.go
- tests/bcr/go_work/pkg/go.mod
- tests/bcr/go_work/pkg/pkg_test.go
- vendor/github.com/bmatcuk/doublestar/v4/README.md
- vendor/github.com/bmatcuk/doublestar/v4/match.go
- vendor/github.com/bmatcuk/doublestar/v4/utils.go
- vendor/modules.txt
- walk/config.go
doublestar now has an option to match without re-validating every time, see https://github.com/bmatcuk/doublestar/issues/92
> Other
> all
Performance
> perf: do not revalidate glob expressions on each invocation

- rule/platform_strings.go
- rule/value.go
> refactor: add rule.* type assertions

- MODULE.bazel
- internal/bzlmod/go_deps.bzl
Bug fix
`go_deps`
2a65ce83f2fc9cd7022139a621fe7fde8157a85f made it so that Bazel modules would no longer override Go modules if their versions don't match exactly.
Also do not report version mismatches for overridden Bazel modules.
Fixes #
> Fix Bazel module resolution regression in go_deps

- resolve/config.go
- resolve/resolve_test.go
Bug fix
resolve
This change resolves an issue with regex_replace where the default behavior attempts to perform a string replacement using regex, but results in an invalid label.
Fixes #1965
> Issue #1965 - Fix label resolution for non-captured regex

- walk/walk.go
Now the `pathTrie` aligns with the directory tree, not full fs tree which includes files. Aligning with the directory tree makes more sense to me, and I think will make it simpler to do things like load BUILDs concurrently while doing the fs-traversal (and persisting that in the `pathTrie`) etc.
> Other
> all
Performance + simplifying things for future changes.
> refactor: change pathTrie per-file to per-directory

- merger/fix.go
- merger/fix_test.go
> Bug fix
> For example:
>
> all
The changes introduced by #1164 largely support what I need – automatic loading of non-rule symbols from known loads – except it only supports `CallExpr`. For imported struct fields, these are not automatically picked up, and the ergonomics of getting them loaded in Gazelle has been tricky for me. I am hoping this is a reasonable fix to this. 
Fixes #1971 
I haven't written Go in a while so please forgive the mess.
> Support load fixing on struct members (dotexpr) instead of just callexpr

- MODULE.bazel
- WORKSPACE
- def.bzl
- deps.bzl
- docs/BUILD.bazel
- tests/bzl_deps/BUILD.bazel
- tests/cli/BUILD.bazel
- tests/visibility_attr/BUILD.bazel
- tests/visibility_attr/child/BUILD.bazel
- vendor/github.com/bazelbuild/buildtools/build/build_defs.bzl
Bug fix
all
Adds an explicit load (and dep) for sh_binary, which is no longer packaged inside Bazel 8. This is backwards-compatible with Bazel 7.
Fixes https://github.com/bazel-contrib/bazel-gazelle/issues/1959
> Use rules_shell for shell targets

- language/proto/fileinfo.go
- language/proto/fileinfo_test.go
- language/proto/generate.go
Summary:
In this commit, we make the protoFileInfo method public so that users interested in parsing the proto files can use the method directly.
Other
language/proto
This PR makes a previously private method public so it can be reused to parse proto files
Fixes #
> [Proto] Make protoFileInfo method public

- def.bzl
this makes sure that if testonly is set in the macro, it's propagated
both to the runner _and_ the wrapper sh_binary. as is, setting
'testonly' in the macro will result in an unbuildable sh_binary if there
are testonly dependencies.
why this is needed: slightly esoteric, but our build process currently
uses the gazelle plugin from contrib_rules_jvm. for uninteresting
reasons, this depends on the output of another tool, which itself needs
to process testonly dependencies.
it's a silly little patch we've been carrying for a while, but since currently
setting the property as is results in breakage, thought i might have a shot
at upstreaming it.
> runner: propagate 'testonly' property to sh_binary

- internal/common.bzl
- internal/go_repository.bzl
- internal/go_repository_cache.bzl
- internal/go_repository_config.bzl
- internal/go_repository_tools.bzl
Bug fix
go_repository
`ctx.path` and label attributes may no longer implicitly watch their contents in Bazel 7.4 and higher, so we need to explicitly watch them.
> Fix staleness issues with recent Bazel versions

- internal/go_repository.bzl
Bug fix
go_deps
This will print `@io_bazel_rules_go//go:go` if the user uses the legacy repo name. Before Bazel 8.1.0, it will emit `...//go:go` instead of `...//go`, but correctness is more important than brevity in this case.
> Use apparent repo name in `go mod tidy` suggestion

- internal/wspace/finder.go
> fix: use REPO.bazel and MODULE.bazel when finding repo root

- merger/fix.go
- merger/fix_test.go
Bug fix
merger
I found that used idents in assignment expression rhs position have their load statements removed. This PR adds those idents to used symbols collection in `FixLoads` fn.
> merger: handle ident load

- Design.rst
- README.rst
- language/go/config.go
- language/go/config_test.go
- language/go/fileinfo.go
- language/go/fileinfo_test.go
Gazelle already iterates over all supported os/arch combos to include go files. This is similar but expanded to custom tags. When adding a new build tag, we create a copy with the tag set to true and append to the original. This means that build tag evaluation will grow exponentially.
Fixes https://github.com/bazelbuild/bazel-gazelle/issues/1262
Feature
language/go
It changes the behavior of `build_tags` to defer evaluation to build time. Instead of assuming the tag is _always_ true, it treats the tag as both true and false when evaluating tags for a file.
Fixes #1262
> Evaluate build tags as both true and false

- internal/generationtest/generation_test.go
It seems 7f7af3b8d1942061c06850ff9a9115cab05b2665 broke `UPDATE_SNAPSHOTS`
Bug fix
all
Fix `UPDATE_SNAPSHOTS` to write to the correct BUILD.out filepath.
> fix: correct updated filepath when updating expected output BUILD files

- internal/bzlmod/go_deps.bzl
- internal/bzlmod/go_mod.bzl
- internal/bzlmod/non_module_deps.bzl
Other
internal/bzlmod
According to Bazel's documentation it is deprecated:
https://bazel.build/rules/lib/builtins/Label#workspace_name
We should use Label.repo_name instead.
I am working on an analysis tool that is capable of parsing BUILD/*.bzl files. It currently fails to process these files due to it not supporting Label.workspace_name. Instead of adding support for it to my tool, I think I'll just use the occasion to fix upstream rules.
> Stop using Label.workspace_name

- README.rst
Auto-resolving Google APIs to `@go_googleapis` was removed in 0.32.
> Update docs for Google API name resolution

- internal/go_repository.bzl
Bug fix
go_repository
Bazel 8 no longer watches `Label`s passed to `repository_ctx.path` by default, which can result in `go_repository`s not being refetched when the Go env or Gazelle changes.
Related to bazel-contrib/rules_go#4278
> Watch inputs to `go_repository`

- README.rst
- walk/config.go
- walk/walk.go
- walk/walk_test.go
Close #1832
Feature
> Other
> all
Add an option to enable only updating existing BUILDs and not creating any new ones.
I think this is common among extension authors, normally implemented with a quick-exit within `Configure` if the `*rule.File` is `nil`. However all the subdirs then need to be manually traversed to find files in subdirectories with no BUILD.
I've always maintained a patch similar to this PR to avoid plugins having to do manual fs operations.
Fixes #1832
> feat: support only updating existing BUILD files

- tests/bazelignore/BUILD.out
- tests/bazelignore/REPO.bazel
- tests/bazelignore/repo1/file2
- tests/bazelignore/repo2/file2
- tests/bazelignore/repo3/sub2/file1
- tests/bazelignore/sub2/repo1/BUILD.out
- tests/bazelignore/sub2/repo1/file4
- tests/bazelignore/sub2/repo1/repo2
- tests/bazelignore/sub2/repo2/file2
- tests/bazelignore/sub2/repo4-a/file4
- tests/bazelignore/sub2/repo4-b/file4
- walk/BUILD.bazel
- walk/config.go
- walk/walk.go
Feature
all
Support the bazel8 [ignore_directories](https://github.com/bazel-contrib/bazel-gazelle/issues/1994)
Fixes #1994
This is handled separately from `.bazelignore` because a) it only excludes directories and does not have to be checked on every file and b) it uses globs and is therefor a lot slower then `.bazelignore`
> feat: add support for bazel8 REPO.bazel ignore_directories

- rule/rule.go
Bug fix
rule
The attr.val field was introduced in the commit a2a604d as part of the R`ule.SetAttr` implementation. However, there is a bug where updating `attr.val` does not correctly propagate the change to `r.attrs[key].val`. The issue stems from Go's map value semantics. When a value is retrieved from a map, it is returned as a copy, not a reference. In the current implementation:
```go
if attr, ok := r.attrs[key]; ok {
attr.expr.RHS = rhs // Fine because RHS is a reference
attr.val = value  // Modifies the copy, not the original value in the map
}
```
As a result, changes to attr.val are not reflected in r.attrs[key].val.
**Related issue** …
> fix: attr.val is not updated when setting multiple times

- walk/walk.go
> Other
> walk
Changes parallelism from 6 to GOMAXPROCS. It doesn't seem to hurt and
may benefit large CI machines. Discussed in #2042.
Follow-up to #2042
Somewhat related to #1891
> walk: set parallelism to runtime.GOMAXPROCS

- config/config.go
- config/config_test.go
- walk/config.go
- walk/config_test.go
With the ongoing changes to fs-walking I think anything related to BUILD file location/generation should be part of the walk configuration.
I think this will be required or at least simplify the changes required for [parsing BUILD files during walk](https://github.com/bazel-contrib/bazel-gazelle/pull/1928) and [moving exclusion to walk](https://github.com/bazel-contrib/bazel-gazelle/pull/1928/files#r1962414111). Both of those require knowing the `ValidBuildFileNames` and `ReadBuildFilesDir` during the fs walk.
Refactor
all
> refactor: move fs/walk related configuration to walk/config

- internal/bzlmod/default_gazelle_overrides.bzl
Other
cmd/gazelle
Proto generation must be disabled as  gogo/protobuf is broken and generated proto bindings are already available in the repo.
> Add proto override for k8s.io/kubelet to default_gazelle_overrides.bzl

- cmd/fetch_repo/clean.go
Feature
go_repository
Sometimes it's not just build files in go modules that are trouble, but inconveniently constructed MODULE.bazel files in repositories you'd like to pinch some go code from can also ruin your day. This does away with them, as well as WORKSPACE files for good measure.
> fetch_repo: also remove WORKSPACE and MODULE files when cleaning

- language/go/build_constraints.go
- language/go/build_constraints_test.go
- language/go/config.go
- language/go/config_test.go
- language/go/fileinfo.go
- language/go/fileinfo_test.go
Bug fix
language/go
This PR provides an alternative way of implementing #1938 (i.e. evaluating both `tag` and `!tag` as true when evaluating build constraints).
The way it was implemented originally has exponential time complexity with the number of provided build tags. This made gazelle unusable on projects with a relatively large number of tags, as the run would never end.
This implementation leverages the existing `dropNegationForIgnoredTags` to manipulate the tag expression.
Fixes #1262 in a more efficient way than what #1938 implemented.
I'm still considering what the right place to apply …
> Improve performance of "Evaluate build tags as true and false" feature

- internal/bzlmod/default_gazelle_overrides.bzl
Other
cmd/gazelle
Proto generation must be disabled as github.com/hashicorp/go-plugin is broken and generated proto bindings are already available in the repo.
> Add proto override for github.com/hashicorp/go-plugin to default_gazelle_overrides.bzl

- internal/bzlmod/go_deps.bzl
Feature
language/go
As part of #1731, we disabled multiple go.work files due to only time
constraints and uncertainty about its implications. After thorough
consideration and nearly a year of running with this removed without
issues, I feel comfortable enabling it.
Reasoning: Since go.work files are essentially rollups of go.mod files,
and we already support multiple go.mod files, extending support to
go.work files is a natural and safe progression.
> [Feature] Enable support for go.work files in non-root modules

- internal/bzlmod/go_deps.bzl
- tests/bcr/go_mod/go.mod
- tests/bcr/go_mod/go.sum
- tests/bcr/go_work/pkg/go.mod
- tests/bcr/go_work/pkg/go.sum
Letting the bazel_dep and Go dependency participate equally in the version resolution is creating various inconsistencies. This can lead to to a root module having to either use `inject_repo` or `use_repo` and `override_repo`.
Resolve this by consistently preferring the `bazel_dep` over the Go dependency. Keep the existing code that warns (or can fail) if the dependencies are at different versions.
Example MODULE.bazel:
```
module(
name = "bazel_dep_should_win",
)
bazel_dep(name = "rules_go", version = "0.53.0")
bazel_dep(name = "gazelle", version = "0.42.0")
bazel_dep(name = "circl", version = "1.3.8")
go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
```
And the go.mod referring to a newer version.
Fixes #2060
**What type of PR is …
> Improve consistency by prefering bazel_dep over Go

- BUILD.bazel
- cmd/gazelle/fix-update.go
- internal/go_repository_tools_srcs.bzl
- tests/BUILD.bazel
- tests/fix_mode_strict/expectedStderr.txt
- walk/BUILD.bazel
- walk/cache.go
- walk/config.go
- walk/dirinfo.go
- walk/walk.go
- walk/walk_test.go
> Feature
> walk
Walk2 is a replacement for Walk. Walk is now deprecated and implemented
in terms of Walk2. We avoid an incompatible change here since packages
outside Gazelle import and use walk.
Walk2 takes a callback function that accepts its arguments and returns
its results via structs, similar to language.Language.GenerateRules.
This allows us to add more arguments and results without incompatible
changes. This also lets the callback function return errors instead of
simply printing and maybe exiting.
This change will enable lazy indexing. The callback function will be
able to return a list of additional directories to visit.
This change includes a major …
> walk: refactor and add Walk2 function

- walk/walk.go
> Bug fix
> walk
When visiting directories in RelsToVisit, if strict mode is enabled, check for errors and return early after every directory component.
Strict mode implies that we return as soon as we find an error elsewhere, so let's do that here too.
For #1891
Follow-up to [comment](https://github.com/bazel-contrib/bazel-gazelle/pull/2074#discussion_r2061002644).
> walk: better error checking in strict mode for RelsToVisit

- README.rst
- cmd/gazelle/integration_test.go
- language/go/config.go
- language/go/constants.go
- language/go/fix_test.go
- language/go/testdata/proto_file_mode/abc/BUILD.want
- language/go/testdata/service/BUILD.want
- language/go/testdata/service_gogo_subdir_reset/sub/BUILD.want
Set the default grpc compiler to go_grpc_v2 because go_grpc is considered deprecated.
https://github.com/bazel-contrib/rules_go/blob/8251e45ee86fd17f3fedb34caa2d06a40089f22e/proto/BUILD.bazel#L34
Feature
language/go
Fixes #
> go_grpc_compiler: default to go_grpc_v2

- MODULE.bazel
- deps.bzl
- internal/go_repository.bzl
- tests/bcr/go_mod/MODULE.bazel
- tests/bcr/go_mod/tests.bzl
> Feature
This change adds the `package_metadata` from `@package_metadata` to replace the deprecated `package_info` from `@rules_license`.
> Add `package_metadata` to `REPO.bazel`

- language/proto/known_go_imports.go
- language/proto/known_imports.go
- language/proto/known_proto_imports.go
- language/proto/proto.csv
Bug fix
language/go
Adds go_features.proto to the list of known protos to resolve for gazelle, in the hopes that this moves gazelle closer to supporting the new Go protobuf Opaque API.
**What issue is this part of?**
#2079 
Trying to figure out how to get the new Go protobuf Opaque API working with Bazel; one of the roadblocks I came across was that gazelle would resolve the import of `google/protobuf/go_features.proto` within `//google/protobuf` instead of `@com_google_protobuf`. Based on what I can tell, it seems like this change should at least remove that roadblock.
See also: …
> Add go_features.proto to list of known protos

- internal/bzlmod/default_gazelle_overrides.bzl
Other
internal/bzlmod
Enable build file generation for cel.dev/expr to fix `ERROR: no such package '@@[unknown repo 'dev_cel_expr' requested from @@gazelle++go_deps+com_github_google_cel_go]//` error.
> Add build file generation override for cel.dev/expr

- language/go/config.go
- tests/go_search/self/BUILD.in
- tests/go_search/self/BUILD.out
- tests/go_search/self/self.go
- tests/go_search/use/BUILD.out
- tests/go_search/use/use.go
- walk/walk.go
> Bug fix
> language/go
See title and issue.
Fixes #2094
Also skip a directory in RelsToVisit with any error, not just ErrNotExist. Before, the rest of this change caused //cmd/gazelle:gazelle_test TestMapKindEmbeddedResolver to fail because a .proto file gets added to RelsToIndex, and proto files are not directories. We should tolerate this kind of error.
> language/go: add implicit go_search path when prefix is set

- language/go/fileinfo.go
- language/go/fileinfo_test.go
Performance fix
language/go
Allocation from `strings.Split` shows up around 2-3% in pprof of Gazelle runs in my repo. We can parse these names without allocating.
While here, I removed the duplicate computation of `path.Ext(name)`, rearranged the initial computation of `ext` a bit to avoid computing a value that will be overwritten immediately, and used a switch to check the initial char instead of `strings.HasPrefix`, which should give the compiler the most freedom to optimize
The test coverage for this file is actually very good which gave me confidence that the new code is equivalent
Before:
```
goos: darwin
goarch: arm64
cpu: Apple M1 Max …
```
> Avoid allocations in fileNameInfo

- walk/walk.go
> Bug fix
> all
Normalize the language-returned `RelsToVisit` to ensure paths such as `"."` vs `""` and `"./a"` vs `"a"` do not cause duplicate visit + `Configure` invocations.
Fixes #
> fix: normalize RelsToVisit

- walk/dirinfo.go
- walk/walk.go
Perf/cleanup
all
I'm uncertain if we just need more test cases or if these changes are safe. WDYT?
Ideally only the `isExcludedDir` calls within `loadDirInfo` would be needed. That should filter out all files+dirs loaded from the fs-walk.
Are there scenarios in the `RelsToVisit` logic where we need to check as well? Can that not be done by inspecting the `loadDirInfo` result instead of duplicating the exclusion logic? For example the call within `walk()` that I moved and within `Walk2`... I feel like we shouldn't need either of those...
> perf: remove extraneous isExcluded(dir) checks

- walk/walk.go
- walk/walk_test.go
Feature
walk
This is an alternative implementation of #2101. As suggested in the comments in #2101:
> Alternatively, what do you think we should index all parent directories here unconditionally? It wouldn't be that much extra work since we're already parsing them and applying configuration.
This also simplify the logic, so we no longer need to distinguish between "visited" and "called", because once a directory is "visited", it's also indexed. This also means all directories are "visited" at most once.
This fixes the issue of `foo/BUILD.bazel` file contains targets that provides imports like `foo.bar` which is common in …
> indexing all parents of visited directories

- language/go/config.go
Bug fix
language/go
In #1802 the functionality was added, but the flag validation was not updated to allow specifying `clean` as an argument to `-build_file_generation` in `update-repos`.
With this change, we can now provide `-build_file_generation=clean` when running `update-repos`.
NaN (probably not worth creating one)
None
> language/go: allow clean as argument to -build_file_generation

- internal/go_repository.bzl
- internal/go_repository_tools.bzl
Feature
go_repository
This allows `go_repository` (with suitable attrs to ensure reproducibility) and the bootstrapped Gazelle binary to be shared across workspaces and `bazel clean --expunge` invocations. Requires Bazel 8.3.0 or later.
Running `bazel clean --expunge; USE_BAZEL_VERSION=8.3.0rc3 bazel test //...` in `tests/bcr/go_mod` with primed caches:
```
Before:
INFO: Elapsed time: 14.479s, Critical Path: 0.56s
After:
INFO: Elapsed time: 6.753s, Critical Path: 0.60s
```
> Add support for `--repo_contents_cache`

- language/proto/generate.go
- language/proto/generate_test.go
- language/proto/testdata/explicit_package_name/BUILD.old
- language/proto/testdata/explicit_package_name/BUILD.want
- language/proto/testdata/explicit_package_name/foo.proto
Bug fix
langugage/proto
**What does this PR do? Why is it needed?** 
`go_package` with explicit package name is discouraged but allowed. Under default mode `go_package` has some special handling that extracts the package name, e.g. for `example.com/protos/foo;package_name` it uses `package_name` as base for RuleName. 
In cases of other modes there is no special handling. `Package.RuleName` containing `go_package` under `proto:package` mode was being directly passed to the `RuleName` method to resolve the rule name. 
Before my other change in #2105 the `RuleName` ignored all segments of the input name seperated by non letter or digit characters, which by pure luck also contained the `;` seperating import …
> Add special handling for extracting explicit package name from rule name if being part of `go_package`

- language/go/def.bzl
Cleanup
language/go
The property has been marked deprecated for 9 months, we should stop using it to unblock rules_go from removing it
Fixes #
> Remove usage of deprecated package_list on Go context

- language/proto/config.go
- language/proto/config_test.go
Bug fix
`language/proto` and its downstream project, eg. `gazelle_cc`, `rules_jvm`
It adjusts the infering of proto.Mode - previously it was not taking account the `rules_go` added using bzlmod or its apparent names. 
It was affecting downstream gazelle extensions consuming `proto_library`, e.g `gazelle_cc`, `rules_jvm` 
No issue in this repo, see https://github.com/EngFlow/gazelle_cc/issues/76#issuecomment-3075688845
> Fix interfing proto.Mode - taking into account mode module apparent names 

- rule/value.go
- rule/value_test.go
Bug fix
`rule` and possible integration in downstram projects
**What does this PR do? Why is it needed?** 
It adds handling for more forms of `glob` expressions: 
- accepts named `include` argument 
- accepts positional `exclude` arguments 
Both of these are allowed in Build files
No dedicated issue 
Addendum to #2142 
> Accept more forms of glob values when parsing `bzl.Expr`

- merger/fix.go
- merger/fix_test.go
Bug fix
merger
FixLoads does not work for a list expression on the RHS of an assigment containing symbols.
This addresses #2146, but doesn't really solve the underlying issue.
> fix FixLoads issue with list of symbols

- MODULE.bazel
- deps.bzl
- tests/bcr/go_mod/MODULE.bazel
Other 
go_repository
downstream extensions
Downstream projects that depend on `gazelle` are adding the `package_metadata` to their builds, e.g. https://github.com/EngFlow/gazelle_cc/pull/72 
The `package_metadata` 0.0.3 has added `licenses` rules that are missing in 0.0.2. 
When adding `gazelle_cc` via WORKSPACE we typically want to include `gazelle` dependencies first before setting up extension specific dependenices, example: 
```
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
gazelle_dependencies()
load("@gazelle_cc//:deps.bzl", "gazelle_cc_dependencies")
gazelle_cc_dependencies()
```
Becouse older version of `package_metadata` would be requested …
> Upgrade `package_metadata` to 0.0.5 (was 0.0.2)

- pathtools/BUILD.bazel
- pathtools/path.go
- pathtools/path_test.go
- walk/BUILD.bazel
- walk/walk.go
> Feature
> pathtools
In the fix for #2132, I'll need to iterate over the prefixes of a given
slash-separated path. Rather than duplicate the logic from Walk2,
let's extract it into pathtools.
Prefixes returns an iterator over prefixes to avoid needing to allocate
a slice. The code should be much simpler after we adopt Go 1.23 and can
use range-over-iterator loops.
Fixes #2132
> pathtools: add Prefixes helper function

- cmd/gazelle/fix-update.go
- config/config.go
- config/config_test.go
- internal/module/module.go
Bug fix
cmd/gazelle 
config
`Config.RepoName` was never setup when using `MODULE.bazel`. 
With this change we now always try to extract repositoryName from either `module(name = ...)` in MODULE.bazel or `workspace(name = ...) in case of workspace files. 
The logic previously defined in `cmd/gazelle` was moved to `CommonConfigurer` as this is the place that should be responsible for setup of RepoName. 
No issue in this repo. I want to use have special logic in based on `Config.RepoName` in `gazelle_cc` 
The hack (for mapping of google_apis) was preserved in the new location`. I don't know if it …
> Extract either Module/Workspace RepoName in `CommonConfigurer`

- walk/dirinfo.go
- walk/walk.go
Populating the walk cache should be based on the same `shouldVisit()` which also determines what directories we will walk/visit later.
Bug fix
all
Today when passing a set of directories to update on the cli it makes the `populateCache()` less effective.
Fixes #
> fix: populate walk cache for all walk modes

- internal/bzlmod/go_mod.bzl
- tests/bzlmod/go_mod_test.bzl
- go.mod and go.work allow 'godebug' directive which can used to add in required GODEBUG settings
- this change is to support this godebug directive in go.mod and go.work by ignoring its contents since gazelle has no need for this GODEBUG settings
Feature
cmd/gazelle
This PR will ignore the `godebug` directive in the `go.mod` and `go.work` files for gazelle when used with bazel modules.
Fixes #2167 
> ignore godebug directive in go.mod and go.work #2167

- internal/bzlmod/go_mod.bzl
Go 1.25 introduces a new `ignore` directive to specify directories the go command should ignore.
`Feature`
`bzlmod/go_mod`
This PR ignore the `ignore` directive in go.mod file, to avoid causing the parsing of the _go.mod_ file to fail when this new Go 1.25 directive is used.
> support new ignore directive in go.mod

- walk/dirinfo.go
- walk/walk.go
Is there any reason to block waiting on this? We can most likely start `visit()`ing directories in parallel while the cache population is done async in the background...
Normally the cache population will always be a step (or many steps) ahead of `visit()` and this change should only make the 2 traversals overlap but introduce no change to who fills the cache or what order it is filled. The only scenario I can think of where `populateCache()` would no longer be the first to fill the cache would be if a language callback invokes `GetDirInfo`?
Other
all
> perf: populate walk cache in background

- language/go/generate.go
- pathtools/path.go
- pathtools/path_test.go
- tests/go_internal_nested_visibility/BUILD.in
- tests/go_internal_nested_visibility/BUILD.out
- tests/go_internal_nested_visibility/README.md
- tests/go_internal_nested_visibility/a/internal/BUILD.out
- tests/go_internal_nested_visibility/a/internal/internal.go
- tests/go_internal_nested_visibility/expectedStderr.txt
- tests/go_internal_nested_visibility/internal/BUILD.out
- tests/go_internal_nested_visibility/internal/a/internal/b/BUILD.out
- tests/go_internal_nested_visibility/internal/a/internal/b/b.go
- tests/go_internal_nested_visibility/internal/internal.go
Fixes #2186
> Bug fix
> language/go
Added pathtools.LastIndex to accomplish this: we should be looking for the last occurrence of "internal" in the path, not the first.
Added a test for Index in addition to LastIndex and changed the semantics. Previously, Index ran path.Clean on both strings, but this made the result meaningless in cases where it changed the strings.
Fixes #2186
> language/go: set visibility correctly for nested internal directories

- cmd/fetch_repo/module.go
Feature
go_repository
When the Go module sum mismatches, the most effective way is to delete the corrupted Go module, instead of deleting the whole Go module cache, which may contain many other unrelated modules. Because fetch_repo already know where the Go module is, it can automatically delete it and ask people to retry. 
New experience:
```
$ export GO_REPOSITORY_USE_HOST_CACHE=1
$ rm $(go env GOMODCACHE)/github.com/mattn/go-sqlite3@v1.14.15/static_mock.go
$ bazel clean --expunge --async
$ bazel fetch --force @com_github_mattn_go_sqlite3//:go-sqlite3
...
ERROR: com_github_mattn_go_sqlite3: fetch_repo: resulting module with sum …
```
> Automatically deleting corrupted Go module cache
